import * as React from 'react'
import Layout from '../components/layout'
import { StaticImage } from 'gatsby-plugin-image'

const AboutPage = () => {
  return (
   <Layout pageTitle="Den harmoniska kroppen">
<StaticImage
        alt="Clifford, a reddish-brown pitbull, dozing in a bean bag chair"
        src="../images/walk.jpg"
/>
 <h3>Att gå</h3>
   <p>Genom sin förmåga attt stå upprätt intar människan en position mellan himmel och jord. Så tar vi det allra första steget. Vi är inte längre bundna vid en och samma plats. Världen öppnar sig framför oss ett fält att upptäcka och ett fält att förändra.</p>
<p>Med röstens hjälp har vi lärt känna den sfär av utstrålning som öppnar sig utifrån vårt centrum. Nu kan vi förflytta detta centrum. Universum blir en sfär vars centrum finns överallt och periferin ingenstans. Så upplever vi det subjektivt. Vart vi än tar vägen upplever vi jorden som en sfär, vars centrum är vi själva. Hur vi än vandrar mot horisonten kan vi aldrig nå den. Överallt är det upplevelsen av ett centrum som dominerar och periferin som drar sig undan för vårt sökande.</p>
<p>Från och med de första vacklande steg som barnet tar krävs det flera år för att vårt gående skall nå mognad. Vårt sätt att gå speglar då den mänskliga kroppens universella lagar i lika hög grad som de karakteristiska personlighetsdragen, vilket gör att man känner igen en person på gången bland hundra andra.</p>
<p>I grund och botten kan det som är mest personligt hos oss, det som bidrar till variationsrikedomen inom den mänskliga arten, tas ifrån oss lika litet som kraniets form eller ögonfärgen. Vi kan alltså ha förtroende för det. Det kommer alltid till uttryck, bara vi inte sätter upp några särskilda hinder för det.</p>
<p>Det som är universellt mänskligt i vår gång inpräglas kraftfullt redan när vi lär oss gå, under ledning av en allsmäktig instinkt. Om vi avlägsnar oss alltför mycket därifrån riskerar vi att bryta vår inre enhet och hämma vår handlingskraft.</p>
 <h1>Den centrala övningen</h1>
<p>Att iaktta små barn är en källa till outtömlig kunskap. Om vi uppmärksamt betraktar ett barn som tar sina första steg slås vi i hur hög grad barnet anstränger sig som en helhet. De små barnen arbetar på intet sätt avskilda från den övriga kroppen. Det är en homogen helhet som tultar fram. Allt efter sina unga krafter följer benen helheten betydligt mer än de styr den. Det är detta vi nu skall återupptäcka i vår vuxna kropp.</p>

   


   
    <h1>BALANS</h1>
    <p>Vi kan öva oss genom att gå längs en rak linje till exempel på en lugn väg. Men det är ofta bekvämare, i synnerhet inomhus att gå i cirkel. Dess diameter beror på hur stort utrymme vi kan disponera. Till och med en cirkel  med en diameter av tre meter kan vara tillräckligt och gör det möjligt att öva i en lägenhet. Vi börjar med att gå runt i cirkeln och söka oss fram till den hastighet som vi känner är den bästa inom det givna utrymmet. Vi intresserar oss bara för att finna den hastighet i vilken gåendet fortsätter av sej själv i sin egen takt. Om vi går för snabbt bildas en konstant spänning inom oss, och om vi går för långsamt blir balansen vinglig precis som när man cyklar för långsamt.</p>
<p>När vi funnit den rätta hastigheten fortsätter gåendet som ett flöde som bär oss, och som vi uppehåller med ett minimum av ansträngning. På samma sätt som vi i en tidigare övning lärt oss att rida på andningens flöde försöker vi här att rida på vågrörelsen i vårt gående.</p>
<p>Allt eftersom gåendet fortsätter söker vi först och främst lodlinjen i kroppshållningen, på samma sätt som i den upprätta ställningen. Det handlar om att återfinna den totala upplevelsen av mittaxeln som är i balans från fötterna till hjässan. Att kroppen förflyttas ändrar inte den osynliga kontakten med tyngdkraften.</p>
<p>Detta försök att medan vi går återfinna kroppens lodlinje som vi redan hittat fram till i en statisk position kommer troligen inte att lyckas med en gång, Man måste börja om, tålmodigt och regelbundet, Tänk på alla tusentals ofruktbara försök du gjorde som barn innan du kunde gå stadigt. Instinktivt upplevde du den som en lek och upprepade försöken utan att bli otålig. Dessa försök har burit frukt. Det du nu gör kommer också att bära sin frukt.</p>
<p>Du kan växla mellan den stående statiska övningen och den gående. Ju fastare du har återupprättat reflexernas kretslopp genom den föregående övningen i sittande eller stående ställning, desto lättare kommer du att återfinna dem nu när du går.</p>
<p>När vi går fokuserar vi inte medvetandet speciellt på andningen utan låter den var fri och ser bara till att inte blockera den. Om du gjort de föregående övningarna regelbundet kommer du inte att ha svårt att liksom ur ögonvrån känna igen de ögonblick då andningen blockeras eller hejdas. Det är alltid en signal att du anstränger dig alltför hårt i övningen och att du måste fortsätta med större lätthet, i en anda av lek.</p>
<p>När mittaxeln kommit på plats kommer du att känna igen samma förnimmelser i rörelsen som när kroppen var stilla: lättheten som är ett resultat av balansen mellan hållningsreflexerna och tyngdkraften och paradoxalt nog också stabiliteten utifrån känslan att var fast rotad. Du svajar inte hit och dit utan glider fram i rummet i en enhetlig och stadig gång. Och jag upprepar än en gång att det är tack vare erfarenheterna från de tidigare övningarna som dessa ord kan få en konkret innebörd för dig.</p> 
<h1>CENTRAL NÄRVARO</h1> 
<p>De olika etapperna i den övning som nyss beskrivits har sitt särskilda värde när man försöker göra dem de allra första gångerna senare smälter de mer och mer samman till en helhet.</p>
<p>Sedan vi funnit den optimala hastighet som gör att gången kan flyta fram i ett jämnt flöde och sedan vi återfunnit mittaxeln som konkretiserar det riktiga samspelet med tyngdkraften, söker vi nu den enhet som föds ur den centrala utsiktspunkten. Precis som i den stående ställningen gör denna enhet det möjligt för vår mentala närvaro att ta kroppen i besittning som en helhet från fötterna till huvudet.</p>
<p>Denna helhet är nu i rörelse. Bålen, armarna och benen får liv av de rörelser som jag skall beskriva i det följande. Men om varje del spelar exakt sin roll, kommer helhetsförnimmelsen att förbli homogen. Ingen del träder fram separat för vår varseblivning.</p>
<p>Genom vårt sätt att gå glider hela kroppen fram i rummet, som en pelare, samlad runt sitt centrum. Det är inte mina ben som går, det är jag: "jag går". Helhetsintrycket kan liknas vid det svaga ljudet från en Rolls Royce-motor: ett enda ljud, knappt hörbart, men tillräckligt för att säga oss att motorn arbetar.</p> 
<h1>FRIHET</h1>
<p>Jag har redan nämnt andningens frihet. Men nu när kroppen rör sig kan rörelsens frihet förnimmas i varje led. </p>
<h2><b>Benen</b></h2> 
<p>I och med att man har funnit den riktiga mittaxeln och den centrala utsiktspunkten gjort integreringen av helheten möjlig, sker det också en avspänning i höfterna. Det ben som är fritt och rör sig från den bakre positionen framåt utför en mycket ekonomisk pendelrörelse. I själva verket får vi en helhetsförnimmelse av att de båda benen svänger fram och tillbaka under oss som två pendlar. Den väl integrerade rörelsen som benet gör när steget tas grundar sig på ett intryck av en fri pendelrörelse från höfterna.</p>
<p>Benen bidrar inte med någon särskild egen ansträngning vare sig för att nå ner till marken framför kroppen eller för att trycka den ifrån sig bakom kroppen. De följer den lodräta axeln som glider fram i rummet och pendlar snarare under än framför eller bakom den.</p>
<p>Observera att knäna inte i något ögonblick är översträckta. Till och med i sträckningsfaserna behåller de en lätt fjädring, som ger dem deras säkerhet.</p>
<p>En konsekvens av denna frigörelse är intrycket att de båda benen bildar ett integrerat system när man går. Gåendet följer inte längre en rytm i två olika faser: höger-vänster, höger-vänster. Det lokomotoriska systemet (förflyttning genom rörelse) tycks förena de båda benen till ett enda hjul som snurrar fram under oss, ungefär som när en cirkusakrobat balanserar på en enhjuling. Våra ben rullar åt oss.</p> 
<h2><b>Fötterna</b></h2>
<p>Om man kan säga att de båda benen i en integrerad koordination fungerar som ett enda hjul under oss, kan fötterna liknas vid däcket som omger hjulet. Fötternas komplexa leder med sina skyddande trampdynor av muskler och senor lockar till denna jämförelse. Trampdynorna dämpar och tar upp den stöt som fötterna utsätts för av det hårda och oregelbundna underlag vi går på. Foten tar först i marken med hälens yttersida.  Genom en reflexmekanism plattas foten ut mot marken, rullar mot den som hjulet på en vagn och lämnar marken med stortåspetsen. Det hela fungerar som ett system av hävstångsarmar som successivt viks upp samtidigt som man går.</p>
<p>Som jag redan påpekat apropå den stående lodräta hållningen är foten inte ett kraftogran utan ett känselorgan. När man går är benets viktigaste muskulära "motorer" belägna på bäckenets nivå. Med hjälp av låren och underbenen överför de sina impulser ända till fötterna som modifierar kontakten med marken.</p>  
<p>För att kunna upleva denna funktion bättre rekommenderar jag livligt att man övar sig attt gå. Gör det antingen barfota eller i mjuka skor utan klackar, tillräckligt vida så att tårna kan breda ut sig, vilket är nödvändigt för en perfekt koordination av foten.</p>
<p>Om kroppsaxeln är riktig och om benens hjul rullar reflexmässigt blir gången absolut ljudlös. Det är också ett säkert sätt att få en bekräftelse på om man hittat den optimala koordinationen. Man hör inget ljud och känner inga stötar när hälen når marken. Foten och benet rullas upp i ett komplext och mycket exakt system av reflexer, som man ine kan korrigera med någon framgång genom att ingripa lokalt i någon enskild del. Denna mekanism fungerar på nytt av sig själv som ett urverk som går runt, så snart spänningar och obalans eliminerats.</p>
<h2><b>Armarna</b></h2>
<p>Vi har känt hur den riktiga kroppsaxeln befriar benen och höfterna. På liknande sätt ger bröstkorgens och halsens balans frihet åt axlarna. Armarna börjar svänga fram och tillbaka. Man skall inte utföra rörelsen utan låta den ske av sig själv. Armarna kommer utan ansträngning  i en pendelrörelse. Fortsätt att gå ända till dess armarna börjar röras av sig själva utifrån avspänningen i axlarna. När rörelsen hittat en rytmisk regelbundenhet anpassar den sig av sig själv som en motvikt till benens rörelse. Vänster ben och höger arm förs framåt samtidigt och balanserar varandra runt mittaxeln och följs av höger ben och vänster arm.</p>
<h2><b>Bålen</b></h2>
<p>Armarnas och benens rörelser när man går är i själva verket en förlängning av bålens röreler. Eftersom bålens rörelser är mindre, lägger vi i allmänhet inte märke till den. De är lättare att iaktta utifrån hos någon som har en fullständig koordination, till exempel ett barn.</p>
<p>Bålens spel är beronde av en fri rörlighet i lederna runt mittaxeln. I beskrivningen av den stående lodräta hållningen skilde jag mellan de djupa reflexerna som gör den vertikala kroppshållningen möjlig, och avspänningen på ytan, som gör halsen, bröstet och bäckenet fria att roterande spela runt mittaxeln.</p>
<p>När man går arbetar denna ytligt liggande muskulatur genom en kontinuerlig rörelse av vridningar och motvridningar mellan bäckenet och bröstkorgen. Den viktigaste motorn för denna rörelse är de sneda bukmusklerna. Här har vi ett slags gångjärn av muskelsystem mellan reflexbanorna och de viljestyrda musklerna. Vi har redan berört dessa muskler apropå andningen som de samarbetar med när den engageras i en intensiv ansträngning. Vi möter dem nu på nytt i deras betydelse för gåendet.</p>
<p>Genom sina båda skikt av korsade fibrer utför båda muskelsystemen samtidigt vridningar och motvridningar, som gör att höger axel lätt kan föras framåt samtidigt med vänster höft och sedan vänster axel med höger höft.</p>
<p>Den inre sneda bukmukelns fibrer förlängs upp genom bröstkorgen av den stora bröstmukelns fibrer. Tillsammans bildar detta två kraftlinjer som förenar axlar och höfter på diagonalen.</p>
<p>Den rörelse som åstadkommer denna balans och som drar med sig bäckenet och axlarna utgår från gångjärnsområdet kring de nedersta bröstkotorna och de översta ländkotorna. Det rör sig om det område som jag ofta beskrivit som centrum för kroppskoordinationen. Ovanför detta centrum pendlar axlarna fritt kring mittaxeln precis som höfterna gör under det.</p>
<p>Denna pendling kan vara mer eller mindre markerad beronde på personlighetstyp. Hos vissa personer har ligamenten en så slapp struktur att de möjliggör ganska omfattande rörelser. Hos andra däremot begränsas rörelserna av mycket strama ligament. Det viktiga är inte så mycket rörelsernas omfång som balansen mellan den övre och den nedre delen i fritt samspel.</p>
<p>Om koordinationscentrum är normalt beläget medför det alltså en befrielse i bröstkoren och höfterna. Lemmarna pendelrörelser möter inga hinder. Höfterna och axlarna är som vidöppna dörrar, genom vilka bålens koordination förlängs ut i armarna och benen.</p>
<p>Men om koordinationscentrum på konstlad väg flyttats upp mot övre delen av bröstkorgen, vilket alltför ofta är fallet på grund av omedvetna spänningar, kan detta område stelna som en vägg och förlora sin fria rörlighet runt mittaxeln. Axlarna stelnar och armanrna tycks inte längre hitta sitt fria pendlande.</p>
<p>Om centrum har tryckts alltför långt ner mot bäckenet kommer detta att stelna på samma sätt för att behålla sitt läge och deltar inte längre smidigt i benens rörelser.</p>
<p>När man upplever gången medvetet på detta sätt visar det tydligt i hur hög grad handlingens frihet och enheten kring centrum i själva verket är oskiljaktiga.</p> 
<h1>Att ta sig utrymme</h1>
<p>Vi har börjat med att fördjupa vårt gående i en uppmärksamhetssfär som hittills begränsats av kroppens dimensioner.</p>
<p>När vår gång fungerar som ett väloljat urverk väcks en önskan inom oss att utvidga vårt territorium. Liksom en ryttare har vi gjort inridningen i manegen, fullständigt koncentrerade på samspelet med hästen. Nu har ögonblicket kommit att vidga sfären så att vi också kan omfatta yttervärlden.</p>
<p>De första stegen i denna riktning blir att låta uppmärksamhetssfären omfatta hela den cirkel vi går i. Vårt medvetande kan behålla kontakten med hela cirkeln fastän kroppen rör sig igenom den punkt för punkt. Cirkeln upplevs då inte längre som en stelnad abstraktion utan som ett dynamiskt flöde som skapas av vår intention att agera och vars våg bär kroppen. Vi konstaterar alltså att denna utvidgning, som förenar vår kropp med det omgivande rummet, också ger den en större frihet. Kroppen blir lättare. På samma sätt får en musikers instrument ett slags transparans när han efter att ha stämt det låter det delta i musikens stora flöde.</p>
<p>Det är nödvändigt att först koncentrera uppmärksamheten på kroppen, för att hjälpa den att åter komma i total harmoni med sina reflexer. Men den fullständiga friheten kommer inte förrän vi integrerat koppen i en helhet som når utöver den.</p>
<p>Efter att ha gjort övningen i cirkeln kan vi tillämpa erfarenheten när vi förflyttar oss, särskilt ute i naturen. När gåendet har kommit på plats kan vi medvetet utvidga uppmärksamhetsfältet. I stället för att snegla från den ena sidan till den andra, som en ovan jägare gör, försöker vi som den vane jägaren att stabilisera blicken framför oss och samtidigt öppna det perifera synfältet så att det omfattar hela omgivningen. I detta vidöppna fält uppfattar vi då minsta förändring och vår gång integreras lätt och naturligt i omgivningen.</p>
<h2><i>Gåendet och de enskilda stegen</i></h2>
<p>Vi har försökt att förstå gåendet genom att koppla samman den praktiska erfarenheten med vissa teoretiska förklaringar. På denna grund bygger otaliga tillämpningar i det dagliga livet: att hoppa, springa, skjuta framför sig, dra, bära och många flera. Jag kan inte beskriva dem alla här och det är för övrigt inte nödvändigt. Jag skall bara visa hur man i några  speciella fall kan applicera grundprinciperna.</p>
<h2>Att gå baklänges</h2>
<p>Hela koordinationen är mest lämpad för att gå framlänges på bekostnad av baklängesgåendet. Vi vet ju att det är möjligt att gå baklänges, men med mindre kraft och hastighet än framlänges. Eftersom vi inte har ögon i ryggen kan vi inte riktigt se efter hur vi går och baklängesgåendet upplevs därför som något oroande.</p>
<p>Och ändå har jag efter många års erfarenhet förstått vilken utmärkt övning det är att gå baklänges för att stärka kroppsmedvetandet och koordinationen av reflexerna.</p>
<p>Dessutom är detta mindre välbekanta sätt att gå inte lika starkt betingat av våra kroppsliga vanor och deformeringar. Och eftersom det inte är möjligt att fokusera blicken på målet inbjuder baklängesgången till att utnyttja det perifera seendet maximalt för att se så långt som möjligt åt sidorna. På så sätt går vi i kontakt med hela omgivningen och inte bara med en enda målpunkt.</p>
<p><i>Under alla omständigheter bör vi välja en yttre miljö som är så betryggande som möjligt: gott om plats utan några hinder. Vi kan gå baklänges i en rak linje eller i cirkel. Cirkeln är till en början svårare, men med lite övning blir vi vana vid den också.</i></p>
<p><i>Det är viktigt att öva utan att ideligen vända på huvudet. Om blicken hålls fast och stadigt riktad framåt kommer det perifera seendet att vidgas. Övningens etapper är densamma som när vi gick framlänges.</i></p>
<p><i>Man söker sig först fram till den optimala hastigheten, som blir långsammare nu än då man går framlänges, men tillräckligt snabb för att skapa ett nämnt flöde i rörelsen utöver förflyttningen steg för steg. Tänk på att när man cyklar så måste man ha en viss minimihastighet för att kunna hålla balansen.</i></p>
<p><i>När vi är i detta flöde söker vi oss fram till mittaxeln som frigör benen och gör det möjligt för det osynliga hjulet att rulla mellan dem. Stegen blir kortare än när man går framlänges och foten rullar upp nu i omvänd ordning, dvs från trampdynan till hälen. Hjulet rullar i motsatt riktning.</i></p>
<p><i>Om motaxeln är riktig blir ochså axlarna fria och armarna finner sin pendlande balans i harmoni med benens. Eftersom stegen är korta reduceras också bäckenets och axlarnas rotation. Friheten upptill och nedtill som koordinerats runt centrum blir förmodligen mera bräcklig och sårbar nu än när man går framåt, med det går att finna den.</i></p>
<p><i>Man kan alltså vidga uppmärksamhetens sfär så att den omfattar hela cirkeln, eller målet om man går bakåt längs en rak linje.</i></p>
<p>Genom denna övninng når man en ytterligare förfinad medvetenhet om de processer som sätts i spel under gåendet.</p>
<p>Sedan man har övat baklängesgången under några minuter går man på nytt framlänges och smakar av det man uppnått: vilken ökad lätthet och precision och vilken glädje!</p>
<h2>Med höga klackar</h2>
<p>När gångens ursprungliga mekanism är återställd blir det möjligt att behålla den till och med när man går med höga klackar.</p>
<p>Ju högre klackarna är, desto mer begränsas fotens upprullning och desto mindre blir benhjulets radie. Stegen blir därför kortare. De höga klackarna hörde ursprungligen till teatrarnas och hovens skodon. De inbjuder inte till några långa, raska kliv, efterom hela benets koordination då blir fel med oundvikliga och förödande konsekvenser för ledernas och i synnerhet ryggradens hälsa.</p>
<p>Om man vill gå med höga klackar ibland är det bra att växla om med lågklackade skor, precis som när dansarna kompenserar sin tåspetsträning genom djupa böjningar som tänjer vaderna och hälsenorna.</p>
<p>Ju högre klackarna är, desto mer måste man tänka på att benens koordination blir riktig. Om den är det, kan man gå nästan ljudlöst till och med i högklackade stövlar.</p>
<h2>Att bära bördor</h2>
<p>Vi kan inte undgå att bära mer eller mindre tunga bördor emellanåt. Då är det viktigt att känna till hur man på bästa sätt skall integrera bördorna med gången.</p>
<p>Först och främst kan vissa rörelsetekniska regler göra uppgiften lättare. Ju mer symmetriskt och ju närmare kroppens mittaxel man bär ett paket, desto bättre intetgreras det med kroppen. Man kan antingen bära det på ryggen eller på bröstet på det sättet. Att bära en börda på huvudet ger största möjliga effektivitet och frihet. De västerländska kulturmönstren accpterar dock knappast detta, och jag nämner det bara utan några större illusioner om att det någonsin skulle bli praktisk verklighet.</p>
<p>Om bördan bärs med hängande armar som en väska eller en spann vatten, bör man försöka fördela vikten i balans mellan båda armarna. Om det inte går bör man bära växelvis i vänster och höger hand för att arbeta lika mycket med båda sidor.</p>
<p>Förutom dessa rörelsetekniska aspekter spelar den psykologiska aspekten en viktig roll, oavsett hur man bär. Det handlar om hur det föremål som man bär är integrerat i ens uppmärksamhetsfält.</p>
<p>När jag till exempel iakttar resande på en station får jag ofta intrycket att det finns en osynlig mur mellan dem och deras bagage. De har inte integrerat väskorna med sig själva utan behandlar dem som främmande föremål och tvingar sig att bära dem, liksom i konflikt. Resultatet blir en ökad spänning, vanligen koncentrerad till armarna eller axlarna.</p>
<p>Låt oss alltså undersöka om det finns en effektivare metod.</p>
<p>Vi har redan noterat att när den centrala utsiktpunkten gör gången enhetlig får vi en subjektiv förnimmelse av att spänningarna är homogent fördelade över hela kroppen. Varje del fyller sin funktion utan att avvika från helheten genom några speciella förnimmelser.</p>
<p>För att bevara denna kvalitet då man bär ett föremål är det nödvändigt att införliva föremålet i vår sfär som en del av oss själva. Vi gör det redan omedvetet i många fall. En hatt som vi haft länge integreras med huvudet liksom glasögonen med ansiktet. Det som i detta fall är resultat av en lång tids vana kan åstadkommas med en medveten ansträngning när vi bär en börda.</p>
<p>Utifrån den centrala utsiktspunkten försöker vi omfatta hela föremålet, inte bara dess handtag, i vår medvetandesfär. Dess massa integreras med vår egen, som en förlängning av kroppen. Den extra ansträngning det innebär att bära fördelas då över hela muskulaturen. Genom att lederna är fria kan kroppens form automatiskt förändras för att på bästa sätt anpassa sig till den ökande belastningen.Så kommer till exempel axlarnas lutning mot bördan att spontant balanseras av en motsvarande förskjutning i bäckenet.</p>
<p>Om vi alltsså tillämpar priciperna för balans, frihet och integrering runt centrum på den helhet som bildas av kropp och bördan kommer vi att se att detaljerna anpassar sig och faller på plats utan någon avsiktlig inblandning. Denna nya enhet kommer att vara homogen, liksom kroppen ensam var det, och ansträngningen blir mindre tröttande eftersom den fördelas bättre.</p>
<p>På samma sätt kan vi med fördel tillämpa denna metod när vi bär nya kläder eller när vi hanterar verktyg eller musikinstrument. Ju bättre vi kan integrera föremålen i vår medvetandesfär, desto lättare och naturligare kommer det att kännas att använda dem, om vi tränar i samma grad. Det är fantastiskt att hos gamla hantverkare se hur människan, verktygen och materialet bildar en oupplöslig fysisk men också psykisk enhet från och med det ögonblick då de sätter sig till arbetet.</p>
<h2>Att springa</h2>
<p>Genom en analog grundmekanism är det en skillnad av samma slag mellan att gå och att springa som mellan hästens skritt och trav. Det är en förändring i rörelsesättet, en total omorganisering av koordinationen.</p>
<p>Den tydligaste förändringen när man övergår från gående till springande är en anpassning av hela kroppens spänningsnivå. Den visar sig omelbart och påtagligt i armarna och benen, vare sig man springer fort eller långsamt.</p>
<p>Kropptyngden passerar nu genom fotsulorna och hälarna lyfts från marken. Varje avstamp görs på främre delen av foten. När man går bibehålls hela tiden kontakten med marken och föttera avlöser varandra i denna kontakt utan avbrott. När man springer är kontakten med marken inte kontinuerlig. Om man låter hälarna gå tillbaka till marken i varje steg skulle det framkalla en serie stötar som vore farliga för organismen.</p>
<p>Armarna böjs så att underarmarna hålls horisontellt och armbågarna pekar lätt utåt. Att försöka låta armarna hänga ner längs bålen medan man springer, till och med i kort trav är inte någon avspänning. Det skulle bara resultera i en tröttsam konflikt mellan den allmänna tonusnivån och ansträngningen att uppnå denna lokala avspänning.</p>
<p>När man en gång har erfarit denna spänningsförändring i armar och ben förstår man bättre att springandet, liksom gåendet, inte bara engagerar benen utan hela kroppen. Vi återfinner igen de grundläggande elementen: balans kring mittaxeln, andningens frihet, enheten runt centrum, i en jämn fördelning av energin. Också här rullar hjulet osynligt mellan de båda benen. Dess radie ökar, men inte på grund av en ansträngning lokaliserad till benen. Utan att bryta av från helheten rullar hjulet under oss, i lodlinje med mittaxeln.</p>
<p>I ett långdistanslopp är det ytterst viktigt att denna integrerade cirkelrörelse är regelbunden. De vackraste exemplen på detta är de stora etiopiska maratonlöparna. Här är det uppenbart att det är den koncentrerade mentala närvaron som ger löpningen dess funktionella enhet. De rörelsetekniska detaljerna kommer sedan. Men också här beror ekipagets prestationer ytterst på ryttaren.</p>
<p>I ett sprinterlopp eller i en slutspurt är det på samma sätt inte den kraft som direkt driver fram kroppen som är effektivast utan i stället kraften i intentionen, fokuserad på slutmålet som drar kroppen med sig. Den mentala mobiliseringen mot målet frigör den fysiska koordinationen, men om vår medvetna uppmärksamhet var riktad just mot koordinationen själv skulle den hämmas.</p>
<h2>Övningens frukter</h2>
<p>Att gå engagerar hela människan. För den vuxne som helt medvetet försöker återfinna sin förlorade enhet och kraft finns det få övningar som är så allsidiga och samlande som just att gå.</p>
<p> Den nedre människan får ökande krafter genom ett mjukt och regelbundet arbete som alla kan utföra, starka och svaga, unga och gamla. Var och en kan hålla på längre eller kortare tid, allt efter sina möjligheter. Men alla kan höja sin energinivå genom att gå regelbundet.</p>
<p>Den övre människan kan genom att gå befrias från överskottet av spänningar som beror på oro, bekymmer eller alltför intensiv intellektuell ansträngning. Dessa spänningar har annars en tendens att göra axlarna och halsen stela och att krympa ihop bröstkorgen. Under gåendet frigörs armarna av det enkla samspelet med tyngdkraften, deras rytmiska pendlande leder till att axlarna och bröstkorgen släpper all pemanent spänning. Halsen hittar på nytt sin balans och den mentala klarheten kommer tillbaka i och med att ansiktet spänns av.</p>
<p>Den centrala zonen integrerar den övre och den nedre delen av kroppen och omfördelar på ett harmoniskt sätt energin i helheten. Andningsrytmen kommer på plats igen och finner sitt samspel med stegens snabbare rytm.</p>
<p>Rytmens balanserande effekt ger sig till känna som en känsla av välbefinnande och lättnad, som visar att vi vågat ge efter. Det går inte att öppna sig för rytmen om man krampaktigt håller sig fast vid olika slags ideer, känslor eller attityder.</p>
<p>Om vi har möjlighet att gå ute i naturen eller åtminstone i en park och på  så sätt vidga vår uppmärksamhetssfär, kan vi ta in grönskans lugnande ro i oss. Denna utökade sfär ställer våra bekymmer på ett narurligt sätt i ett perspektiv som gör dem relativa.</p>
<p>För att vi ska kunna märka dessa resultat krävs det en viss tid. Några tankspridda och okoncentrerade steg mellan andra aktiviteter räcker inte. Det viktiga är att gå för nöjet att gå, i kontakt med sig själv, för att låta balansen, friheten och enheten komma på plats.</p>
<p>Det var länge absolut nödvändigt för människan att gå. Många kan nu nästan helt och hållet undvika gåendet i sina liv och ersätta det med mekaniska transportmedel. Att gå blir i stället något som man gör efter fritt och medvetet val.</p>
<h1>Pisksnärten</h1>
<p>Med hjälp av andningen har vi i den sittande och stående ställningen funnit grunden för ett sätt att vara som först var begränsat inom kroppens sfär.</p>
<p>Genom att använda rösten har vi vidgat denna sfär så att den också omfattar allt som rösten upprättar en känslomässig eller intellektuell relation till. Förutom ett sätt att vara är detta det första stadiet i ett sätt att handlla, där gåendet sedan vidgade sfären ytterligare.</p>
<p>Vi har också sett hur armar och ben utgör en förlängning av bålen. Även om lemmarnas rörlighet är mycket stor har rörelserna sitt urspung i ett begränsat antal koordinationer i bålen, som i sin tur svarar för kroppens enhet i handlingen.</p>
<p>Den första av dessa stora koordinationer har vi redan träffat på i gåendet. Det är relationen mellan vridning och motvridning som runt den centrala zonen förbinder axlarna och bröstkorgen med bäckenet. När vänster axel förs framåt förs även bäckenets högra sida framåt som en motvikt. Armar och ben förlänger och förstorar rörelsen.</p>
<p>Den andra av de båda stora koordinationerna i bålen bygger också på vridningsrörelsen. Men nu rör sig hela bålen, dvs bäckenet och bröstkorgen, och även huvudet i samma riktning runt mittaxeln. Denna andra koordination tillåter inte någon förflyttning som den första gjorde. Genom att hela muskulaturen verkar i en och samma riktning gör den rörelser som till exempel att kasta eller att slå mycket effektiva. Detta kapitel handlar om denna andra koordination.</p>
<p>Slutligen finns det en tredje grundläggande koordination i bålen, som kommer att behandlas i nästa kapitel.</p>
<p>Så vitt jag kan se utgör alla väl koordinerade och enhetliga rörelser hos människokroppen förlängningar av bara dessa tre koordinationer eller kombinationer av dem. Det är då lätt att inse hur viktigt det är att bli medveten om dem och att samordna dem på bästa sätt. De är avgörande för kvaliteten i alla våra handlingar.</p>
<h2>Den centrala övningen</h2>
<p><i>Vi utgår från den upprättstående ställningen som vi redan känner till, med höftbredds avstånd mellan fötterna.</i></p>
<p><i>När vi har återfunnit den lodrätta axeln som ger lederna största möjliga frhet och givit andningen tid att finna sin rytm och plats, låter vi armarna hänga ner från axlarna och söker därefter rätt på den numera välbekanta centrala utsiktspunkten, som tar kroppen i besittning i dess helhet.</i></p>
<p><i>Därpå vrider vi på oss från vänster till höger och sedan från höger till vänster, runt den lodrätta mittaxeln. Rörelsen engarerar hela kroppen, från huvudet till fötterna. Alla delar startar rörelsen och slutar rörelsen på samma gång: huvud, brötkorg, bäcken, knän och fotleder. Rörelsen utvecklas inte succesivt, led för led, utan absolut samtidigt.</i></p>
<p><i>Allt vrids åt vänster eftersom 'jag vrider mig åt vänster', allt vrids åt höger eftersom 'jag vrider mig åt höger'. Ingen del skiljer sej från helheten, ingen del leder helheten. Det är den mentala avsikten att vrida sig, som styr och rör hela kroppen samtidigt.</i></p>
<p>Ryggen och bröstet vrider sig inte som ett kompakt block. Ryggrandens alla ledförbindelser och alla revbensparen deltar i rörelsen. Detta är möjligt bara om den riktiga mittaxeln behålls.</p>
<p>Vi fann när vi övade den stående ställningen att bröstkorgen härigenom förblir helt fri.</p>
<p>Rörelsen i fotlederna och knäna är inte speciellt stor men tillräcklig för att delta i hela kroppens vridning utan att avbryta den. Kroppstyngden är jämnt fördelad mellan fötterna.</p>
<p>Om ingen del av kroppen belastas med alltför mycket energi som gör att den skiljs ut från helheten, bör inte heller någon led försvagas så  mycket att det blir ett avbrott i den elastiska fjädring som likt en spiralfjäder rör sig upp och ner, från fötterna till huvudet. Om det fungerar så, stimuleras den övre och den nedre människan lika mycket och smälter samman i en homogen helhet.</p>
<p>De sneda bukmusklerna spelar här, liksom vid gåendet, rollen som samordnare av vridningen i nivå med kroppens centrum.</p>
<h2>Optimalt och maximalt omfång</h2>
<p>Vid de första försöken är rörelsens omfång inte särskilt stort. Det krävs ingen ansträngning att utföra rörelsen som sådan; den är mycket enkel att göra, utan strävan är att behålla den riktiga mittaxeln och den fria andningen under vridningen. Rörelsen skall utföras så ekonomiskt som möjligt, medan man försöker nå maximal otvungenhet. Varje led ska vridas lika lätt som om den gick på kullager - vilket den i själva verket gör om ingen obalans stör dess funktion.</p>
<p>När denna fria och enhetliga rörelse blivit allt mer säker ökar den helt naturligt i omfång. Armarna dras med av rotationen och förlänger den passivt liksom piskans snärt förlänger skaftets rörelse. Om man avspänt ger sig hän åt rörelsen kommer armarna att slingra sig spiralformigt om bålen vid varje rotation.</p>
<p>Om vi låter rörelsen bli större märker vi att dess kraft också ökar - men bara upp till en viss nivå. Om man går utöver denna nivå resulterar en överdrivet stor rörelse inte längre i ökad kraft utan minskar den istället. Om vi upprepar övningen uppmärksamt kommer vi att upptäcka en tydlig gräns för handlingen, ett optimalt omfång som ger den kraftigaste impulsen åt rörelsen att gå tillbaka i den andra riktningen. Detta optimala omfång ligger långt ifrån ledernas maximala rörelseomfång.</p>
<p>Det är skillnaden mellan det optimala och det maximala omfånget som ger rörelsen dess kraftreserv och lederna deras säkerhetsmarginal. Att arbeta med det maximala omfånget berövar inte bara den muskulära impulsen dess kraft utan är i själva verket farligt för de leder som ansträngs alltför nära bristningsgränsen.</p>
<p>Hos djuren kan vi se att de alltid handlar inom gränserna för det optimala omfånget och bara använder det maximala omfånget när de direkt tvingas till det av yttre omständigheter.</p>
<p>Under övningen bör vi alltså försöka respektera det optimal omfånget. Detta innebär att vi får vara lyhörda så att vi känner inifrån när vi riskerar att passera gränsen. Vi placerar oss alltså i balanspunkten mellan att känna och att handla.</p>
<h2>Bettet</h2>
<p>Första delen av denna övning består därför av att enbart söka efter minsta möjliga ansträngning. Att i rörelsen återfinna den balans, den frihet och den enhet som vi har smakat i den statiska övningen är ine helt lätt. Men med några minuters daglig övning kommer vi emellertid att nå en exakt och tydlig förnimmelse av reflexfaktorerna och samtidigt av den yttre rörelsen som sammanfaller med dem. Den upprepade rörelsen blir allt lättare att göra. Man utför den som man andas.</p>
<p> Det är först nu man kan gå över från ett rent kvalitativt sökande efer den riktiga rörelen till det kvantitativa samspelet med energin. Kanske har du lekt med en piska när du var barn? Det finns en handrörelse som man måste försöka hitta, utan vilken den kraftigaste knyck inte ger annat än ett kaotiskt och till och med farligt resultat. Men när man till sist hittat koordinationen och piskan snärtar som man vill går det att i denna exakta koordination intensifiera piskslagen så att de klatschar allt kraftigare och snärtigare.</p>
<p>När koordinationen av vridningsrörelsen blir riktig känner vi på samma sätt en möjlighet att börja angripa rummet utanför oss, 'bita' efer det. Då kan vi leka med bettet, intensifiera det eller minska det, allt efter behag. Det får oss att allt tydligare känna hur effektiv denna vridningsmotor är, en av kroppens allra starkaste.</p>
<p>Detta 'bett' är av en rent dynamisk karaktär. Det är beroende av samarbetet mellan de reflexer som ger balans och frihet och den mängd energi som viljemässigt engageras i handlingen. 'Bettet' är beroende av hur riktigt helheten fungerar och inte av att vi sätter in stor muskelkraft. Tvärtom gör bettet det möjligt för den kraft vi sätter in, hur stor eller hur liten den än är, att ge högsta tänkbara effektivitet. Bettet mister sin kraft så snart rörelsen forceras, eftersom koordinationens kvalitet då försämras. I förhållande till den energi som används ger en forcerad rörelse alltid ett klent utbyte. Den känslighet som gör det möjligt att under själva handlingen känna koordinationens kvalitet är då borta. Balansen mellan att känna och att handla har brutits.
Man handlar i blindo.</p>
<p>Det är alltså lätt att förstå att det här är en övning som väsentligen grundar sig på det rätta sättet att vara och att handla. Kraften växer av sig själv, helt enkelt genom det faktum att övningen repeteras regelbundet. Det är inte nödvändigt att koncentrera sig direkt på den. Det är till och med så att senare, när kraften ökat och det blir behagligt och nödvändigt att använda den, integreras den i balansen, i friheten och helheten utan att förstöra den, och ökar helt enkelt deras uttrycksfält.</p>
<h2><i>Övningens frukter</i></h2>
<p>Pisksnärtövningen har jämfört med gåendet fördelen att kräva mycket litet utrymme. Det är alltså lätt att utföra den när man är ensam en stund. Liksom gåendet gör den det möjligt att återföra de neuromuskulära reflexernas kretslopp och de kretslopp som den viljestyrda handlingen engagerar till deras rätta samspel. Övningen bidrar också till att minska de ytliga muskelspänningarna, i synnerhet i axlarna och bröstet, medan den samtidigt aktiverar de reflexer som svarar för hållningen och andningen.</p>
<p>Det är inte nödvändigt att försöka medvetet koordinera andningsrymen med rörelsen. Denna samordninng kommer att modifieras allt efter den hastighet och den styrka man använder.</p>
<p>Rent allmänt blir övningen mer välgörande om man varje gång försöker hitta den kraft och hastighet som känns behagligast. Detta varierar från person till person. För en och samma individ kan det också variera från gång till gång. Den hastighet som är lämplig på kvällen passar inte på morgonen. Varje gång måste man utforska de för ögonblicket bästa villkoren, känna medan man handlar, handla medan man lyssnar medvetet.</p>
<p>Övningen bör pågå i flera minuter, till dess att spänningarna och det som inte är i balans tonar bort som i ett bad av välgörande rörelse.</p>
<p>Det 'bett' som jag har talat om kan upptäckas och användas i alla rörelser som är riktigt koordinerade.</p>
<p>Pisksnärten passar emellertid särskilt bra som en intensiv ansamling av energi som skall riktas mot ett yttre mål. Man skulle kunna kalla den att koordinera 'punchen', slagkraften i fysisk mening, men också, märkligt nog, i psykologisk bemärkelse. Jag har ofta lagt märke till att de som i livet saknar 'punch' eller 'bett' i sitt förhållande till tingen och till människorna också har svårigheter att mobiisera sin kropp i denna koordinerade vridningsrörelse.</p>
<p>Under antiken baserades de grekiska idrottsmännens träning på femkampens olika grenar. Två av dessa, löpning och hopp, betonade koordinationen av gången med vridningar och motvridningar, Diskuskastning och spjutkastning och utnyttjade pisksnärtens koordination. Den femte grenen slutligen koordinerade alla dessa koordinationer och nu i mötet med en motståndare i brottningen.</p>
<p>Också för oss kan gångöviningen och pisksnärten ge nycklarna till en väl anpassad koordination i våra handlingar,som sedan kan tillämpas spontant efter det dagliga livets behov.</p>
<h2>Vågen</h2>
<p>Bålens två stora koordinationer som nyss har beskrivits och vars prototyper vi har funnit i gången och i pisksnärtens rörelse, bygger båda på den vertikala sträckningen av kroppen. De gör det möjligt för oss att handla kraftfullt och effektivt visavi yttervärlden. Känslomässigt är de neutrala. Om de används så som jag har beskrivit dem blir de ett uttryck för våra möjligheter till medveten kontroll och behärskning av våra handlingar.</p>
<p>Det finns också en tredje koordination som kan kombineras med de båda andra men som är annorlunda till sin karaktär. Också den engagerar hela kroppen runt dess centrum men nu inte längre i en rotation utan i en böjnings- och sträckningsrörelse. Genom att den står i nära förbindelse med andningskoordinationen blir den ett uttrycksmedel inte bara för en viljestyrda 
handlingen utan också för det känslomässinga och instiktiva livet.</p>
<h2><i>Förberedande övning</i></h2>
<p>Denna övning har vi redan träffat på i kapitlet om andningen. Vi skall nu upprepa den mera preciserat.</p>
<p><i>Lägg dig på rygg och dra upp knäna mot bröstet. Lägg händerna om knäna. Huvudet och bäckenet vilar mot golvet.</i></p>
<p><i>Ljuda med sluten mun på 'MMM', som vi gjort tidigare, och pressa samtidigt knäna mot bröstet genom att trycka till med armarna. När utandningen når sin gräns och alltjämt känns behaglig släpper du efter på armarnas tryck men behåller händerna kvar runt knäna. Inandningen kommer då av sig själv under avspänningen. Upprepa öviningen till dess att andningen och rörelen bildar en homogen helhet. Det allmänna intrycket blir då att hela kroppen sluter sig som en boll runt sitt centrum med utandningen och utvidgas med inandningen under avspänningen. Rörelsen förlänger och intensifierar koordinationen av andningen.</i></p>
<p>Om man fortsätter övningen utan att forcera den kan man iaktta hur ryggen rundas när kroppen sluts under utandningen. Det gör att bäckenet och axlarna höjs lätt från golvet och ökar nackens 'svank', vilket i sin tur balanserar ryggens svank.</p>
<p>Vid inandningen sträcks ryggraden ut genom avspänningen, axlarna och bäckenet återvänder till golvet och nacken 'svank'planas ut i och med att ryggen sträcks.</p>
<p>Lika aktiv som utandningen är, lika passiv är inandningen. Dess rörelse uppstår i en kombinerad samverkan av andningsreflexerna och tyngdkraften.</p>
<h2><i>Den centrala övningen</i></h2>
<p>Genom att förstärka sammandragningen av bålen då vi pressar knäna mot bröstet har vi i den förberedande öviningen kunnat känna växlingen mellan böjning och sträkning som förenas naturligt med andningens båda faser.</p>
<p>Vi skall nu söka hitta denna koordination utan yttre tryck.</p>
<p><i>Lägg dig på rygg igen men med böjda knän och fotsulorna mot golvet, nära bäckenet.</i></p>
<p><i>Lägg händerna på kroppens centrum, mellan revbenen och naveln, precis som den första andningensövningen.</i></p>
<p><i>Upprepa flera gånger den ljudande utandningen på MMM till dess att rösten funnit sin plats.</i></p>
<p><i>Fortsätt övningen och försök att vid varje utandning på M förstärka bukens naturliga sammandragning.</i></p>
<p><i>Den intensifierade utandningen för att stänga till bågen blir naturligtvis kortare än vanligt. Efter varje sammandragning återför inandningen kroppen tillbaka till utgångsläget i en total avspänning.</i></p>
<p><i>Den dynamiska kraft som ligger bakom bågens sammandragning är analog med 'bettet' som jag beskrev i föregående kapitel. Under denna sammandragning fungerar för övrigt hela kroppen som ett par 'käkar' som sluter sig för att bita mot centrum. Bäckenet bildar då 'underkäken', bröstet och huvudet 'överkäken'. Dessa båda stora käkar har sin ledförbindelse runt det gångjärn som bildas av de nedersta bröstkotorna och de översta ländkotorna i nivå med kroppens centrum.</i></p> 
<p><i>Liksom i den förberedande övningen deltar halsen i ryggradens rörelse genom att förstora sin 'svank' när bågen sluts vid utandningen. Halsen sträcks samtidigt med ryggraden i inandningens avspänninng. Huvudet skall inte lämna golvet. Halsens rörelse sker alltså av sig själv, om ingen speciell spänning hindrar den.</i></p>
<p><i>Öviningen upprepas till dess den blir som en rytmisk våg under vilken andning, röst och rörelse integreras till en behaglig helhet.</i></p>
<p>Denna koordination är inte så lätt att hitta. För vissa kommer den helt naturligt medan andra måste söka länge innan de är säkra på att ha hittat den. Alla de föregående övningarna har berett vägen för de känsligare övningarna i detta kapitel. Om du har några svårigheter med dem, forcera inte. Upprepa dem försiktigt, om och om igen, och återvänd regelbundet till de statiska övningarna i liggande, sittande och stående ställningar, som förberedeer och förstärker reflexrörelserna. Det är inte fråga om att imitera något som påtvingas utifrån utan om att åter knyta an till och använda de djupa koordinationernas kretslopp, som man kanske förlorat kontakten med.</p>
<p>Denna övning hjälper oss att känna förbindelsen mellan andningskoordinationen och en viljestyrd handling som kan fungera på ytan medan den samtidigt förlänger reflexernas spel.</p>
<p>Här ser vi på nytt de sneda bukmusklernas betydelse. De kan koordinera bålens vridrörelser eller som här arbeta symmetriskt för att sluta kroppens stora 'käkar'. Genom att de på samma gång deltar i den intensifierade andningen och i bålens tre stora koordinationer (böjning, vridning, och vridning-motvridning) bildar de en av de stora broarna mellan de reflexstyrda musklerna och det viljestyrda systemet. Deras centrala placering i kroppen accentuerar denna betydelse. Vi kan med rätta betrakta dem som en av de stora samordnarna i den muskulära koordinationen.</p> 
<h2><i>Två tillämpningar</i></h2>
<h2>Att ge sig hän</h2>
<p>Vi skall nu utgå från balansen i den stående ställningen för att hitta samma koordination när kroppen befinner sig i vertikalläget.</p>
<p>I denna övning att ge sig hän sker slutandet av kroppen passivt. Det utgår från vågens kretslopp av koordination för att öppna sig för en kraft som kommer utifrån.</p>
<p><i>Vi står upprätt och söker först efter rörelsens form. Låt kroppen sjunka samman och sluta sig och liksom veckas ihop i sick-sack runt sin mittaxel. Det är fråga om en lätt avspänning av ledförbindelserna på alla nivåer, som ger följande resultat: halsen sluter sig bakåt,buken sluter sig framåt, och knäna och fotlederna böjs. Ledförbindelserna stängs samtidigt som de spänner av. Det rör sig om en allmän avspänning i tyngdkraften utan att balansen runt mittaxeln rubbas. Sträck därefter upp kroppen för att återfinna den lodräta hållningen i utgångsläget.</i></p>
<h3>Två beståndsdelar i övningen hjälper oss:</h3>
<p>-- kroppsligt skall rörelsen organiseras kring den centrala zonen. Det är därifrån 'jag ger mig hän'. Den centrala sammandragningen balanseras och förlängs då av att halsen stängs till upptill och knäna nertill. Låt detta ta sig ett konkret uttryck i en djup suck på ljudet AAA, när du ger dig hän i och med böjningen.</p>
<p>--psykologiskt underlättas rörelsen om vi låter den förknippas med en känsla av att ge efter, som här för en yttre kraft. Man kan till exempel föreställa sig att kroppen under stor trötthet ger efter för tyngdkraften eller att den 'smälter' av värmen från solens heta strålar. Den djupa sucken på AAA blir då ett naturligt uttryck för denna känsla.</p>
<p>Också här bör man upprepa rörelsen till dess överlåtelsen på AAA och sträckningen på inandningen bildar en rrytmisk vågrörelse som kommer och går utan avbrott.</p>
<p>En svårighet med övningen är att bibehålla balansen i mittaxeln. Fördelninngen av kroppstyngden skall vara lika på båda fötterna. Under böjningen liksom under sträckningen balanserar ryggens krökar varandra. Det är möjligt bara om den mentala närvaron behåller kontakten med kroppen som en helhet. Den riktiga ledförbindelsen bekräftas i ett intryck man får av homogen enhet i varje moment av vågen. Kroppen uttrycker i sin helhet den psykiska intentionen: 'jag ger mig hän i böjningen' eller 'jag reser mig på nytt'.</p> 
<p>De första försöken upplevs kanske som fumliga, till och med lite löjliga. Fortsätt ändå att leka med övningen utan att pressa dig. Genom övningen kommer din kropp att få uppleva smaken av hur det känns att med viljan ge sig hän, en medveten överlåtelse, under vilken du ändå behåller kontrollen i varje ögonblick.</p>
<h3>Motståndet</h3>
<p>Den föregående övningen har visat oss ett 'spår' utefter vilket hela kroppen kan böjas och resas upp utan att förlora nånting av sin lodlinje. Att ge efter via musklerna öppnade vår känslighet så att vi tydligt kunde uppleva detta 'spår'.</p>
<p><i>Vi skall nu göra en motsatt erfarenhet. Nu är koppens böjning inte längre passiv utan aktiv, och man sluter sig in mot sitt centrum som uttryck för att skydda sig mot en yttre fara.</i></p>
<p><i>Spåret och rörelsens form längs kroppsaxeln är desamma. Det är den dynamiska kraften som ändras fullständigt. Slutandet sker nu snabbt och intensivt, som när man skyddar sig mot ett slag i magen.</i></p>
<p><i>Rörelsen kompletteras av armarna: händerna hamnar framför kroppen med handflatorna riktade framåt som en sköld, armarna är lätt böjda.</i></p>
<p><i>Låt andningen och rösten delta i sammandragningen genom att stöta ut ett explosivt'Ho!'</i></p>
<p><i>Därpå rättar kroppen upp sig under avspänningen, medan inandningen följer av sig själv och armarna faller ner längs med bålens sidor.</i></p>
<p><i>Fortsätt också denna övning till dess den blir en våg av harmonisk helhet, men mycket kraftigt förstärkt under sammandragningen genom rösten 'Ho!'</i></p>
<p>Den dynamiska kraft som jag har kallat 'bettet' är grunden för denna övning. Varje 'Ho', varje sammandragning är som ett intensivt bett av kroppens stora 'käkar'. Runt centrum kan vi till och med, bättre än vid horisontalläget, känna att'underkäken' inte begränsas till bäckenet utan färlängs ut i benen ända till golvet, och att 'överkäken' sträcker sig ovanför bröstet ända till huvudet och armarna. Genom denna 'käkes' aktivitet engageras hela kroppen i handlingen.</p>
<h3><i>Övningens frukter</i></h3>
<p>Denna våg som kan sluta kroppen kring sitt centrum med hjälp av de stora 'käkarna' öppnar ett nytt erfarenhetsfält för oss.</p>
<p>Vi känner redan till i hur hög grad andningen och känslolivet hör samman. Det är inte möjligt att nå en total känslomässig frihet så länge andningen är hämmad.</p>
<p>När känslorna intensifieras är det för övrigt alldeles naturligt att de fördjupar andningen och kommer till uttryck genom vågen. Gråt som bemäktigar kroppen får den att hulka under vågens inverkan. Ett enormt skratt som skakar hela kroppen drar den också med sig in i vågen. En sorg eller en kronisk rädsla har en tendens att hålla bågen sluten. Ett ögonblick av lycka eller entusiasm öppnar den, spänner av buken och fyller bröstet med luft.</p>
<p>Men denna koordination når ännu djupare ner i det instinktiva livet. Utan kroppens och andninngens frihet, utan att musklerna är fritt disponibla för denna våg att komma och gå, förblir den sexuella njutningen begränsad, vare sig man är den givande eller mottagande parten.</p> 
<p>Det är också denna våg som startar i kvinnan när hon skall föda. Den gör det möjligt att sätta barnet till världen i en flytande, dynamisk kraft och utan spänning, vilket är lika viktigt för modern som för barnets välbefinnande.</p>
<p>Vi ser alltså hur betydelsefull denna koordination är för vår känslomässiga och instinktiva hälsa.</p>
<h3>Djuret, roboten och människan</h3>
<p>Koordinationen av sträckninngen har däremot till uppgift att hålla tillbaka vågens intensitet till fromma för en medveten kontroll och effektivitet i den yttre aktiviteten. Den upprätta positionen underlättar också tankens klarhet.</p>
<p>Ur vissa aspekter kan dessa båda stora koordinationer (sträckningen längs kroppsaxeln genom hållningsreflexernas samspel och vågen som uppfyller hela kroppen med liv när andningen förlängs) uppfattas som antagonister till varandra. I själva verket blir de det, om vi inte ser till att de kommer till användning inom skilda men kompletterande områden.</p>
<p>Båda är nödnvändiga för människan. Enbart andningens och instinktens frihet leder till ett rent djuriskt handlande. Enbart kroppens sträckning på en hämmad inandning leder å sin sida bara till en torr abstrakt tanke, ett stelt och okänsligt handlande. Det skulle göra oss till robotar.</p>
<p>Det är det harmoniska samspelet mellan dessa båda poler som gör människan hel.</p>
<p>Vågen kan för ett ögonblick ta överhanden i vårt emotionella och instinktiva liv. Kroppens sträckning som frivilligt har avstått terräng har dock kvar tillräckligt med aktivitet för att medvetandet skall kunna behålla sitt ansvar. Det gör det möjligt att integrera den erfarenheet som man frivilligt genomlever, utan att helt och hållet uppslukas av den.</p>
<p>När det är kroppens sträckning som tar över, i situationeer då tanke och handling är viktiga, försätter andningsvågen sitt fria kretsloppp men utan att gå till den yttersta gränsen för sina möjligheter. Andningsvågen gör det möjligt att utföra handlingen smidigare, att förena den precisa tankens klarhet med den värme som kommer av ett öppet känsloliv.</p>
<p>På så sätt uppstår det ett ständigt samspel mellan de inre parterna, som broderligt förenas eller kontrasterar mot varandra för att ge uttryck för människolivets hela fullhet.</p> 
<h3>Appolon och Dionysos</h3>
<p>Under antiken personifierade Apollon den medvetna kontrollen, som kommer till uttryck genom att den övre människan har ett dominerande inflytande i kroppens sträckning. Appolon hade ansvaret för att leda solens lopp i harmoni med världsalltets gång.</p>
<p>Hans bror Dionysos berikade livet genom allt som naturen och instinkterna kunde skänka människan. Han var i högre grad lierad med den nedre människan och  förkroppsligade all den rikedom som ligger i jordens egna krafter.</p>
<p>På samma sätt som vi inom oss själva kan iaktta växlingen mellan dessa båda stora apolloniska och dionysiska flöden kan vi i historien se olika perioder då de stått i motsättning eller harmonierat. Också i geografiskt avseende kan vi i vissa länders traditionella danser se hur tonvikten lagts vid den dionysiska vågrörelsen eller den apolloniska kroppssträckninngen.</p>
<p>Vilka möjligheter till dialoger och till ömsesidiga fruktbara utbyten finns det inte! Med vilken utarmning för oss om vi enbart identifierar oss med en av dessa poler och därigenom försöker utplåna den andra!</p>
<p>Såväl till det yttre som till det inre blir det mycket lättare för oss att känna igen och acceptera dessa båda poler om vår mentala närvaro blir fastare förankrad. Den ensam kan omspänna ytterligheterna utifrån en högre belägen  utsiktspunkt, där det rena 'jag är' framträder som den oföränderliga bakgrund mot vilken alla förändringar utspelas.</p>
<h3>Innan vi skiljs åt</h3>
<p>Det är inte alltid lätt att förstå oss människor. För att lära känna oss bättre, för att mer kunna öppna oss för det som det omedvetna gör för oss och för att kunna fungera fulltonigare i vår medvetna frihet har vi tvingats att göra oss en klar bild av de existensnivåer som verkar inom oss.</p>
<p>Utifrån dessa observationer har vi kunnat urskilja fyra olika nivåer: en  materiell, en fysiologisk och en psykologisk sam en nivå som möjliggör upplevelsen av 'jag är', av det rena jagmedvetandet.</p>
<p>Vid sidan om dessa fyra existensnivåer, som finns tillsammans i den levande och vakna människan, har vi i den mänskliga organismen upptäckt en trefaldig struktur, i vilken två motsatta poler för en dialog kring ett centrum. Tre stora funktioner kan urskiljas, som deltar i både våra psykiska och våra kroppsliga uttryck:</p>
<h4>- en sensibilitetspol som kommer till uttryck i nervsystemet och i föreställningsvärlden;</h4>
<h4>- en motsatt pol, koncentrerad kring ämnesomsättningen och den viljestyrda handlingen;</h4>
<h4>- mellan dessa båda ytterligheter en balanserande funktion, vars rytmiska aktivitet är förbunden med hjärtat och andningen och som manifisteras i känslolivet.</h4>
<p>Men under denna komplexitet känner vi djupt inom oss längtan efter enhet. Varje inre konflikt, varje motsättning med världen utanför oss orsakar oss lidande.</p>
<p>Vi upplever emellertid vissa ögonblick av fullhet och enhet, ögonblick av lycka, då konflikterna tonar bort. Men de är ogonblick av en balans som lätt kan rubbas. De har skänkts oss av ödet och förefaller vara oberoende av vår vilja och helt bero på de yttre omständigheternas spel.</p>
<p>Vi upplever dem ofta i ett tillstånd av dämpat medvetande som i en dröm. Senare är smärtaan över att ha lämnat dessa tillstånd så mycket större som vi inte vet varken genom vilken dörr vi kom dit eller genom vilken dörr vi gick därifrån.</p>
<p>Dessa ögonblick av fullhet kan inte skapas avsiktligt, liksom blommorna inte kan driva på den växtprocess som de själva är resultatet av.</p>
<p>De yttre realiteterna finns där alltid, till stor del helt oberoende av oss. Men en sak vilar helt på oss själva, nämligen hur vi går in i relation till dem. Vår enhet och vår frihet beror mycker mer på hur vi förhåller oss till de yttre omständigheterna än på omständigheterna sjäva.</p>
<h3>Från den synliga till den osynliga övningen</h3>
<p>Det är således ett bestämt sätt att vara och handla som vi har sökt oss fram till i övningarna.</p>
<p>I balansen har vi funnit grunden till ett bättre förhållande till kroppens fysiska massa och till tyngdkraften. Kring den riktiga kroppsaxeln ökar hela det muskulära systemet sin effektivitet när vi handlar.</p>
<p>Med hjälp av andningens frihet har vi kunnat överlåta åt kroppen egen vishet uppgiften att utan hinder reglera förbindelserna mellan våra organiska funktioner. Den fria andningen har också visat sig höra samman med accepterandet av våra känslor, vilket är själva grunden för ett rikt och öppet känsloliv.</p>
<p>Och slutligen återger den mentala närvaron den centrala rollen åt den kleenod som människan inte delar med någon annan jordisk varelse,detta 'jag är'. Här har vi vårt rikes verklige härskare. Eftersom vi inte längre har kvar den djuriska instinktens omedvetna säkerhet återstår oss inget annat val för att förverkliga vår enhet än att gå på, att väcka och ge näring åt vår slumrande lille kung. Våra psykiska funktioner:tanke, känsla, vilja, är alla ensidiga. Ingen är i den positionen att den kan styra helheten.</p>
<p>Ingen av dem kan ensam bli något annat än en otillräcklig diktator. Men var och en kan bli en utmärkt minister inom sitt eget område, om kungens öga är öppet, om en klar jagmedvetenhet styr och omfattar alla tre.</p>
<p>På så sätt har vi genom övningarna i balansen, friheten och den mentala närvaron funnit villkoren för en inre enhet som är oberoende av omständigheterna och i stånd att anpassa sig till goda eller dåliga villkor för att göra det bästa möjliga av dem, utan inre konflikt och utan att avskärma oss från yttervärlden.</p>
<p>Vi utgår oundvikligen från ett kaotiskt och smärtsamt stadium, som verkligen tvingar oss att ge oss i kast med ett konkret sökande. Därför att vi inte vet hur vi skall nå fram till enheten måste vi utgå från sådana övningar som  jag här beskrivit och använda dem regelbundet. De är fortfarande synliga övningar och vi bör anslå bestämda tider åt dem.</p>
<p>Men genom att öva kommer vi allt oftare att få uppleva ögonblick då övningarna beståndsdelar smälter samman till en naturlig helhet. Dessa ögonblick upplevs som att komma hem, att komma tillbaka till sig själv. Alla hittar sin rätta plats igen. En enhetlig närvaro styr över helheten.</p>
<p>Detta kommer också en dag då denna enhetliga närvaro framträder av sig själv i vårt dagliga liv, till en början bara under korta stunder och med långa mellanrum.</p>
<p>Detta är tecken på att vi är redo att gå över från den synliga till den osynliga övningen, redo att integrera denna enhetliga närvaro i våra dagliga handlingar. Detta är ryttaren som kan rida på och styra inte bara vår andning eller vår gång, utan vårt livs hela flöde, den oavbrutna följd av omständigheter som framträder för oss.</p>
<h3><i>Från den osynliga till den ständiga övningen</i></h3>
<p>Varje ögonblick kan alltså bli ett tillfälle att åter försätta sig i vår enhetliga närvaro.</p>
<p>Tre praktiska råd kan vara till hjälp för att tillämpa detta under strömmen av aktiviteter:</p>
<p>1. Gör aldrig mer än en sak i taget. Ät när du äter, tala när du talar, tänk när du tänker. På det sättet undviker man den konflikt som alltid uppstår ur två aktiviteter som inte har något samband med varandra, som till exempel att lyssna på radio samtidigt som man äter.</p>
<p>2. Tänk på vad du gär . Precis som vi har väckt vår mentala närvaro genom att avsiktligt ta kontakt med andningen, behåller vi den nu i kontakt med den aktivitet vi utför för ögonblicket.</p>
<p>3. Jäkta aldrig. Jäkt är något helt väsensskilt från snabbhet. Man kan springa utan att jäkta. Jäktet leder alltid till en störning av vår naturliga rytm. Det hör alltid ihop med en medveten eller omedveten rädsla. Att leva utan att jäkta är att kunna hålla andningen fri och hjärtat öppet.</p>
<p>Ju mer vårt liv uttrycker vår medvetna, enhetliga närvaro, desto svårare blir det för ledan att smyga sig in. Vi upplever mer och mer hur varje ögonblick innebär något nytt, vilka de yttre omständigheterna än må vara.</p>
<p>När vi åter tar säte i den centrala utsiktpunkten innebär det också att vi kan utvidga vår medvetandesfär och omfatta den aktuella situationen i dess helhet. Denna helhetsuppfattning gör det möjligt för oss att i varje ögonblick avgöra vilken handling som är den riktiga. Den känns naturlig och självskriven med hänsyn till de inre och yttre omständigheterna.</p>
<p>Varje ögonblick av enhetlig närvaro tillåter oss att ersätta de stereotypa reaktioner som härstammar från våra omedvetna vanor med en verkligt kreativ handling, anpassad till det som är unikt i varje situation.</p>
<p>Genom att upptäcka 'hur man gör' kan vi också få insikt om 'vad man bör göra'i varje ögonblick.</p>
<p>Smaken av detta alltid nya och kreeativa liv blir till en kraftfull motivation för att fördjupa vår övning, att göra den till bakgrund till ett liv som inte längre är splittrat mot sig självt.</p>
<p>Inga yttre omständigheter kan hindra oss från denna centrala övning. Inget tvång kan förmå oss att stiga ner från denna inre tron som är vår födslorätt. Det enda villkoret är att vi gör oss ansträngningen att stiga upp på den.</p>
<p>Vad livet än för med sig finns det ingenting som vi inte kan göra till vårt och omfatta i vår medvetandesfär. Det finns ingen situation som vi inte kan göra enhetlig genom vår egen ansträngning att återvända till den centrala utsiktspunkten, där vår värld blir en helhet. Övning och liv är inte längre skilda åt.</p>
<p>Vad kan vara mer naturligt än detta sätt att leva?</p>
<p>Vad kan vara enklare?</p>
<p>Men hur många hinder, förvrängningar, avståndstaganden och låsningar, som vi inte kan nå direkt, har det inte hopats inom oss? Vi måste steg för steg följa den väg som leder från den synliga till den osynliga övningen och från den osynliga till den ständiga övningen.</p>
<p>Vi accepterar ju att ägna en viss tid varje dag åt toalettbestyr, åt en yttre rengöring av vår kropp. Är vi beredda att ägna samma tid åt övningar som ger oss den inre rengöring på vilken vårt livs frihet och enhet beror?</p>
<p>Om vi känner lust till detta och mer än så, behov av det, kommer vi att bereda plats i vårt liv för dessa dagliga övningar. De ger oss en konkret grund för att återerövra vårt kungarike.</p>
<h3>Då börjar vi alltså i morgon?</h3>

    </Layout>
  )
}
export default AboutPage
