import * as React from 'react'
import Layout from '../components/layout'
const AboutPage = () => {
  return (
    <Layout pageTitle="Den harmoniska kroppen">

<h1>Pisksnärten</h1>
<p>Med hjälp av andningen har vi i den sittande och stående ställningen funnit grunden för ett sätt att vara som först var begränsat inom kroppens sfär.</p>
<p>Genom att använda rösten har vi vidgat denna sfär så att den också omfattar allt som rösten upprättar en känslomässig eller intellektuell relation till. Förutom ett sätt att vara är detta det första stadiet i ett sätt att handlla, där gåendet sedan vidgade sfären ytterligare.</p>
<p>Vi har också sett hur armar och ben utgör en förlängning av bålen. Även om lemmarnas rörlighet är mycket stor har rörelserna sitt urspung i ett begränsat antal koordinationer i bålen, som i sun tur svarar för kroppens enhet i handlingen.</p>
<p>Den första av dessa stora koordinationer har vi redan träffat på i gåendet. Det är relationen mellan vridning och motvridning som runt den centrala zonen förbinder axlarna och bröstkorgen med bäckenet. När vänster axel förs framåt förs även bäckenets högra sida framåt som en motvikt. Armar och ben förlänger och förstorar rörelsen.</p>
<p>Den andra av de båda stora koordinationerna i bålen bygger också på vridningsrörelsen. Men nu rör sig hela bålen, dvs bäckenet och bröstkorgen, och även huvudet i samma riktning runt mittaxeln. Denna andra koordination tillåter inte någon förflyttning som den första gjorde. Genom att hela muskulaturen verkar i en och samma riktning gör den rörelser som till exempel att kasta eller att slå mycket effektiva. Detta kapitel handlar om denna andra koordination.</p>
<p>Slutligen finns det en tredjae grundläggande koordination i bålen, som kommer att behandlas i nästa kapitel.</p>
<p>Så vitt jag kan se utgör alla väl koordinerade och enhetliga rörelser hos människokroppen förlängningar av bara dessa tre koordinationer eller kombinationer av dem. Det är då lätt att inse hur viktigt det är att bli medveten om dem och att samordna dem på bästa sätt. De är avgörnde för kvaliteten i alla våra handlingar.</p>
<h2>Den centrala övningen</h2>
<p><i>Vi utgår från den upprättstående ställningen som vi redan känner till, med höftbredds avstånd mellan fötterna.</i></p>
<p><i>När vi har återfunnit den lodrätta axeln som ger lederna största möjliga frhet och givit andningen tid att finna sin rytm och plats, låter vi armarna hänga ner från axlarna och söker därefter rätt på den numera välbekanta centrala utsiktspunkten, som tar kroppen i besittning i dess helhet.</i></p>
<p><i>Därpå vrider vi på oss från vänster till höger och sedan från höger till vänster, runt den lodrätta mittaxeln. Rörelsen engarerar hela kroppen, från huvudet till fötterna. Alla delar startar rörelsen och slutar rörelsen på samma gång: huvud, brötkorg, bäcken, knän och fotleder. Rörelsen utvecklas inte succesivt, led för led, utan absolut samtidigt.</i></p>
<p><i>Allt vrids åt vänster eftersom 'jag vrider mig åt vänster', allt vrids åt höger eftersom 'jag vrider mig åt höger'. Ingen del skiljer sej från helheten, ingen del leder helheten. Det är den mentala avsikten att vrida sig, som styr och rör hela kroppen samtidigt.</i></p>
<p>Ryggen och bröstet vrider sig inte som ett kompakt block. Ryggrandens alla ledförbindelser och alla revbensparen deltar i rörelsen. Detta är möjligt bara om den riktiga mittaxeln behålls.</p>
<p>Vi fann när vi övade den stående ställningen att bröstkorgen härigenom förblir helt fri.</p>
<p>Rörelsen i fotlederna och knäna är inte speciellt stor men tillräcklig för att delta i hela kroppens vridning utan att avbryta den. Kroppstyngden är jämnt fördelad mellan fötterna.</p>
<p>Om ingen del av kroppen belastas med alltför mycket energi som gör att den skiljs ut från helheten, bör inte heller någon led försvagas så  mycket att det blir ett avbrott i den elastiska fjädring som likt en spiralfjäder rör sig upp och ner, från fötterna till huvudet. Om det fungerar så, stimuleras den övre och den nedre människan lika mycket och smälter samman i en homogen helhet.</p>
<p>De sneda bukmusklerna spelar här, liksom vid gåendet, rollen som samordnare av vridningen i nivå med kroppens centrum.</p>
<h2>Optimalt och maximalt omfång</h2>
<p>Vid de första försöken är rörelsens omfång inte särskilt stort. Det krävs ingen ansträngning att utföra rörelsen som sådan; den är mycket enkel att göra, utan strävan är att behålla den riktiga mittaxeln och den fria andningen under vridningen. Rörelsen skall utföras så ekonomiskt som möjligt, medan man försöker nå maximal otvungenhet. Varje led ska vridas lika lätt som om den gick på kullager - vilket den i själva verket gör om ingen obalans stör dess funktion.</p>
<p>När denna fria och enhetliga rörelse blivit allt mer säker ökar den helt naturligt i omfång. Armarna dras med av rotationen och förlänger den passivt liksom piskans snärt förlänger skaftets rörelse. Om man avspänt ger sig hän åt rörelsen kommer armarna att slingra sig spiralformigt om bålen vid varje rotation.</p>
<p>Om vi låter rörelsen bli större märker vi att dess kraft också ökar - men bara upp till en viss nivå. Om man går utöver denna nivå resulterar en överdrivet stor rörelse inte längre i ökad kraft utan minskar den istället. Om vi upprepar övningen uppmärksamt kommer vi att upptäcka en tydlig gräns för handlingen, ett optimalt omfång som ger den kraftigaste impulsen åt rörelsen att gå tillbaka i den andra riktningen. Detta optimala omfång ligger långt ifrån ledernas maximala rörelseomfång.</p>
<p>Det är skillnaden mellan det optimala och det maximala omfånge som ger rörelsen dess kraftreserv och lederna deras säkerhetsmarginal. Att arbeta med det maximala omfånget berövar inte bara den muskulära impulsen dess kraft utan är i själva verket farligt för de leder som anstängs alltför nära bristningsgränsen.</p>
<p>Hos djuren kan vi se att de alltid handlar inom gränserna för det optimala omfånget och bara använder det maximala omfånget när de direkt tvingas till det av yttre omständigheter.</p>
<p>Under övningen bör vi alltså försöka respektera det optimal omfånget. Detta innebär att vi får vara lyhörda så att vi känner inifrån när vi riskerar att passera gränsen. Vi placerar oss alltså i balanspunkten mellan att känna och att handla.</p>
<h2>Bettet</h2>
<p>Första delen av denna övning består därför av att enbart söka efter minsta möjliga ansträngning. Att i rörelsen återfinna den balans, den frihet och den enhet som vi har smakat i den statiska övningen är ine helt lätt. Men med några minuters daglig övning kommer vi emellertid att nå en exakt och tydlig förnimmelse av reflexfaktorerna och samtidigt av den yttre rörelsen som sammanfaller med dem. Den upprepade rörelsen blir allt lättare att göra. Man utför den som man andas.</p>
<p> Det är först nu man kan gå över från ett rent kvalitativt sökande efer den riktiga rörelen till det kvantitativa samspelet med energin. Kanske har du lekt med en piska när du var barn? Det finns en handrörelse som man måste försöka hitta, utan vilken den kraftigaste knyck inte ger annat än ett kaotiskt och till och med farligt resultat. Men när man till sist hittat koordinationen och piskan snärtar som man vill går det att i denna exakta koordination intensifiera piskslagen så att de klatschar allt kraftigare och snärtigare.</p>
<p>När koordinationen av vridningsrörelsen blir riktig känner vi på samma sätt en möjlighet att börja angripa rummet utanför oss, 'bita' efer det. Då kan vi leka med bettet, intensifiera det eller minska det, allt efter behag. Det får oss att allt tydligare känna hur effektiv denna vridningsmotor är, en av kroppens allra starkaste.</p>
<p>Detta 'bett' är av en rent dynamisk karaktär. Det är beroende av samarbetet mellan de reflexer som ger balans och frihet och den mängd energi som viljemässigt engageras i handlingen. 'Bettet' är beroende av hur riktigt helheten fungerar och inte av att vi sätter in stor muskelkraft. Tvärtom gör bettet det möjligt för den kraft vi sätter in, hur stor eller hur liten den än är, att ge högsta tänkbara effektivitet. Bettet mister sin kraft så snart rörelsen forceras, eftersom koordinationens kvalitet då försämras. I förhållande till den energi som används ger en forcerad rörelse alltid ett klent utbyte. Den känslighet som gör det möjligt att under själva handlingen känna koordinationens kvalitet är då borta. Balansen mellan att känna och att handla har brutits.
Man handlar i blindo.</p>
<p>Det är alltså lätt att förstå att det här är en övning som väsentligen grundar sig på det rätta sättet att vara och att handla. Kraften växer av sig själv, helt enkelt genom det faktum att övningen repeteras regelbundet. Det är inte nödvändigt att koncentrera sig direkt på den. Det är till och med så att senare, när kraften ökat och det blir behagligt och nödvändigt att använda den, integreras den i balansen, i friheten och helheten utan att förstöra den, och ökar helt enkelt deras uttrycksfält.</p>
<h2><i>Övningens frukter</i></h2>
<p>Pisksnärtövningen har jämfört med gåendet fördelen att kräva mycket litet utrymme. Det är alltså lätt att utföra den när man är ensam en stund. Liksom gåendet gör den det möjligt att återföra de neuromuskulära reflexernas kretslopp och de kretslopp som den viljestyrka handlingen engagerar till deras rätta samspel. Övingingen bidrar också till att minska de ytliga muskelspänningarna, i synnerhet i axlarna och bröstet, medan den samtidigt aktiverar de reflexer som svarar för hållningen och andningen.</p>
<p>Det är inte nödvändigt att försöka medvetet koordinera andningsrymen med rörelsen. Denna samordninng kommer att modifieras allt efter den hastighet och den styrka man använder.</p>
<p>Rent allmänt blir övningen mer välgörande om man varje gång försöker hitta den kraft och hastighet som känns behagligast. Detta varierar från person till person. För en och samma individ kan det också variera från gång till gång. Den hastighet som är lämplig på kvällen passar inte på morgonen. Varje gång måste man utforska de för ögonblicket bästa villkoren, känna medan man handlar, handla medan man lyssnar medvetet.</p>
<p>Övningen bör pågå i flera minuter, till dess att spänningarna och det som inte är i balans tonar bort som i ett bad av välgörande rörelse.</p>
<p>Det 'bett' som jag har talat om kan upptäckas och användas i alla rörelser som är riktigt koordinerade.</p>
<p>Pisksnärten passar emellertid särskilt bra som en intensiv ansamling av energi som skall riktas mot ett yttre mål. Man skulle kunna kalla den att koordinera 'punchen', slagkrafteen i fysisk mening, men också, märkligt nog, i psykologisk bemärkelse. Jag har ofta lagt märke till att de som i livet saknar 'punch' eller 'bett' i sitt förhållande till tingen och till människorna också har svårigheter att mobiisera sin kropp i denna koordinerade vridningsrörelse.</p>
<p>Under antiken baserades de grekiska idrottsmännens träning på femkampens olika grenar. Två av dessa, löpning och hopp, betonade koordinationen av gången med vridningar och motvridningar, Diskuskastning och spjutkastning och utnyttjade pisksnärtens koordination. Den femte grenen slutligen koordinerade alla dessa koordinationer och nu i mötet med en motståndare i brottningen.</p>
<p>Också för oss kan gångöviningen och pisksnärten ge nycklarna till en väl anpassad koordination i våra handlingar,som sedan kan tillämpas spontant efter det dagliga livets behov.</p>

    </Layout>
  )
}
export default AboutPage
