import * as React from 'react'
import Layout from '../components/layout'
const AboutPage = () => {
  return (
    <Layout pageTitle="Den harmoniska kroppen">

<h3>Att använda rösten</h3>
<p>Att använda rösten är kanske den första handling vi utför när vi kommit till världen. Att sätta igång andningen är något vi gör för oss sjäva, men det första skriket är en signal avsedd för andra.</p>
<p>Denna första handling differentieras undan för undan. Till en början används den enbart för att uttrycka vårt inre tillstånd, vår smärta och vår glädje, vårt överflöd och våra behov, men snart utvecklas rösten till ett jollrande med stort innehåll. Under inverkan av det språk som talas omkring oss sker det sedan ett urval i denna ljudskatt. Allt eftersom vi kan urskilja människorna och föremålen omkring oss tydligare lär vi oss att ge dem namn. Till språkets första funktion, att direkt ge uttryck för känslorna, tillkommer nu en intellektuell komponent som gör det möjligt att uttrycka och utbyta idéer.</p>
<p>Röstens uttrycksskala ligger i korsvägen mellan tankar och känslor, på samma sätt som dess modulationscentrum i struphuvudet är beläget mellan huvudet och bröstet.</p>
<p>Även sedan språket differentierats till ett komplext verktyg i vuxen ålder vilar känslornas grova och oartikulerade röst hela tiden under ytan, färdig att bryta fram i form av rosslingar, klagan, skrik eller stön av smärta eller välbehag.</p>
<p>Genom vår intellektuella utveckling riskerar vi att inte längre fästa någon uppmärksamhet vid rösten utan bara vid ordens betydelse och att negligera de variationer i ljudklangen som är uttryck för idéernas emotionella ursprung, den levande kraft som bär dem och det tryckta ordet för alltid har förlorat.</p>
<p>Det är denna röstens klangkropp som vi skall skaffa oss erfarenhet av genom några övningar.</p>
<h3><i>De centrala övningarna</i></h3>
<h3>Ljudet M och rösten i sig </h3>
<p>Vårt sökande med rösten kan till en början ske antingen i den sittande ställningen eller i den stående, eller ännu hellre växelvis i båda. Senare kommer vi att kunna leka fritt med rösten oberoende av vilken ställning vi för ögonblicket intar.</p>
<p><i>Den första övningen utgår från kontakten med andningen. När den har funnit sitt rytmiska flöde låter vi utandningen försätta stämbanden i vibration på ett ljud med sluten mun, ett regelbundet tonande på "M". Så fortsätter vi med "MMM..." så länge utandningen känns behaglig. Mot slutet av utandningen släpper vi tonen och låter luften av sig själv strömma in genom näsborrarna. Om utandningen inte forceras kommer den efterföljande inandningen lätt, snabbt och ljudlöst, som när man släpper en hoptryckt spiralfjäder och låter den utvidgas. Om utandningen pressats för långt blir den efterföljande inandningen stötig och ljudlig och stör andningens lugnt flytande rytm.</i></p>
<p><i>Man fortsätter övningen genom att växla mellan ljudet "MMM" som förlängs genom uttandningen, och avspänningen då inandningen kommer av sig själv, som en elastisk spiralfjäder. Man kommer att märka att den ljudande utandningen blir längre och längre av sig själv, utan att man någonsin behöver forcera den.</i></p>
<p>Det är viktigt att inleda denna övninng med några minuters övning i tystnad, sittande eller stående. På så sätt kan vi hitta inte bara frihet för andningen utan också den riktiga balansaxeln. Hela bålen blir då genom sin otvunga, vetikala hållning i lodlinjen som en orgelpipa i vilken ljudet kan vibrera. När vi börjar ljuda på M skall det inte medföra att kroppsaxeln förändras på något sätt.</p>
<p>Å andra sidan kan vi genom den tysta övningen försätta oss till den centrala utsiktspunkten där vi förnimmer kroppen som en homogen helhet. Det är denna helhet som då svarar på intentionen att bilda ljudet.Det handlar alltså om att sjunga med hela kroppen. Stämbanden i struphuvudet spelar samma roll som det vibrerande rörbladet i en klarinett. Rörbladets vibrationer åstadkommer en resonans i hela klarinetten. Först då blir tonen hörbar och får den klangfärg som är typisk för detta instrument utifrån dess speciella form och material.</p> 
<p>Fortsätt övningen med "MMM" i några minuter i den tonhöjd som känns lättast och naturligast, och försök vid varje repetition att hitta en vibration som blir allt friare och klangfullare.</p> 
<p>Med "klangfull vibration" menar jag ett ljud som utgår från vår centrala utsiktspunkt och leder till en resonans i hela kroppen, från bäckenet upp till huvudet när vi sitter och ända från fötterna till huvudet när vi står.</p>
<p>Med "fri vibration" menar jag ett ljud som kan vibrera utan några hinder framkallade av muskelspänningar eller blockerade ledförbindelser.</p>
<p>Givetvis är den klangfulla och fria vibrationen bara tänkt att vara en arbetsinriktning till en början, och det krävs tid och regelbunden övining för att förverkliga den. En full resonans i kroppen beror inte på hur intensivt man anstränger sig utan på en riktig reflexmässig balans, på andningens frihet och på den centrala utsiktspunkten, varifrån helheten kan engageras på ett naturligt sätt. Om dessa förutsättningar är uppfyllda  kommer ljudets grundton att bli fylligare genom talrika övertoner som svänger samtidigt. Håligheterna i huvudet och i bålen ger resonans åt stämbandstonen, förstärker den och gör den mera klangfull.</p> 
<p>Ett rikt och fulltonigt ljud ger en behaglig känsla hos den som frambringar det. Ljudet upplevs som ett välgörande bad.</p>
<p>Jag har valt ljudet M för dessa första röstförsök eftersom det på ett naturligt sätt lämpar sig för att ljuda med sluten mun. Det sätter också bukmusklerna i rörelse på ett sätt som är speciellt balanserande. Detta återspeglas också i läpparna, som vibrerar symmetriskt.</p>
<h3>Vokalerna och att sända ut ljudet</h3>
<p>Ljudet M är vårt första hjälpmedel i övningen att sända ut ett ljud från hela kroppen i full resonans, fritt och övertonsrikt.</p>
<p>När vi genom denna övning blivit förtrogna med ljudvibrationen i sig kan vi öppna rösten och rikta den mot yttervärlden. För detta skall vi använda oss av vokalerna.</p>
<p><i>Vi ställer oss på drygt en meters avstånd från en vägg och tar mentalt kontakt med en bestämd punkt på väggen framför oss.</i></p>
<p><i>Denna intention kommer helt naturligt att rikta ögonen mot den punkt vi valt. För att inte riskera att spänna halsen eller komma i obalans väljer vi till en början en punkt som blicken lätt kan nå, inte högre än horisontallinjen eller i ögonhöjd.</i></p>
<p><i>Medan vi behåller kontakten med denna punkt öppnar vi munnen lätt och sänder med utandningen ut ljudet Å (som i "då"), som för att vidröra punkten på väggen med det. Vid slutet av utandningen låter vi tonen dö ut, och inandningen kommer av sig själv under avspänningen.</i></p>
<p><i>På samma sätt som blicken så att säga osynligt förlängs ända till kontaktpunkten på väggen sänder också rösten genom Å-ljudet ut ett slags antenn för att nå denna punkt. Genom att upprepa övningen under några minuter kan rösten undan för undan hitta den naturligaste platsen och med lätthet glida mot målet. Liksom med ljudet M låter vi rösten hitta sin egen plats på den tonhöjd som känns lättast.</i></p>
<p>Kontakten med punkten på väggen skall vara så avspänd som möjligt. Vi försöker tillföra den samma kvaliteter som vi fann när vi lyssnade till andningen. Fokus för uppmärksamheten flyttas helt enkelt från den inre världen till den yttre.</p>
<p>Om det verkar svårt till en början att under dessa nya villkor återfinna de kvaliteter som vi fann med hjälp av vårt inre M, kan man inleda de första Å-ljuden med konsonanten M genom att sjunga "MÅÅÅ.." När man sedan känner sig säker blir det lättare att rikta vokalen direkt mot målpunkten.</p>
<p>Vokalen Å som vi började med har fördelen att vara lätt att frambringa. Den är varken för sluten eller för öppen och ligger placerad varken för långt bak eller för långt fram i munnen.</p>
<p>När vi kan sända ut ljudet Å mot målet utan problem ersätter vi det med vokalen A (som i "han"), som är öppnare och ligger längre bak i svalget. Att sända ut ett tydligt A kräver en avspänd balans i halsen.</p>
<p>När vi också kan sända ut ett A-ljud med lätthet, klart avskilt från Å-ljudet, griper vi oss an vokalen I (som i "vit"). Den placeras naturligt i centrum av munnen, mellan svalget och läpparna men i motsats till A-ljudet medför det att ljudets utsändning koncentreras och pressas samman och det får härigenom en särskilt stark klangskärpa.</p>
<p>I och med att munnen öppnas för att sända ut vokalerna möter vi ytterligare en svårighet. Det är viktigt för röstens avspänning och frihet att halsens och huvudets balans inte störs av felaktiga spänningar när man ljudar. Vid en riktig och effektiv koordinering bildar överkäken tillsammans med kraniet en stabil och orörlig stödpunkt, gemensam  med halsen som förlängning av reflexerna. Det är bara underkäken som rör sig och sänker sig under avspänning för att öppna munnen och släppa fram det ljud som talas eller sjungs.</p>
<p>De tre vokalerna Å, A och I utgör genom sina kompletterande egenskaper en balanserad övning i att sända ut ljud. De har också den egenskapen gemensam att de riktar sig direkt och öppet mot yttevärlden.</p>
<p>Genom sin öppna karaktär förknippas A-ljudet helt naturligt med en stor mottaglighet, en välkommande, något hänförd attityd.</p>
<p>Genom sin klangfärg inbjuder I-ljudet till självbekräftelse och kan påtagligt sätta sin prägel på omvärlden.</p>
<p>Genom sin balans tycks Å-ljudet i ett jämlikt förhållande innefatta både möjligheten att ge och att ta emot.</p>
<p>För övrigt är det märkligt att se i vilken hög grad det latinska alfabetet ger uttryck åt dessa drag till och med i bokstävernas form. A är en vinkel som öppnar sig. I en hoklämd käpp och O en cirkel som sluter sig.*</p>
<p>Andra vokaler som E och U associeras lätt till rörelser tillbaka till sig själv som reaktioner på yttre inflytanden. Om de övas regelbundet kan de få en mer återhållande än befriande verkan. Jag arbetar inte systematiskt med dem annat än i speciell träning med skådespelare och sångare.</p>
<h3><i>Närvarons utstrålning</i></h3>
<h2>Strukturen hos vår organism</h2>
<p>Innan vi fortsätter med röstövningarna skall vi försöka sammanfatta och förtydliga vad vi uppnått när det gäller att förstå vår organism. På så sätt får vi en fastare grund att stå på.</p>
<p>De första övningarna drog oss delvis tillbaka från yttervärlden. Med uppmärksamheten riktad inåt har vi lärt känna de krafter som verkar i kroppen, andningen och den mentala inställningen. I balansen, friheten och den mentala närvaron har vi funnit de förutsättningar som för oss närmare ett sätt att vara friare, mer samlade.</p>
<p>Genom att iaktta sömen kan vi inom människokroppen uskilja en kroppslig och en psykisk del. Under den djupa sömnen är det psykiska frånvarande.</p>
<p>På samma sätt kan vi genom att iaktta döden klart skilja mellan kroppens materiella beståndsdelar som lyder under fysikens och kemins lagar i (tyngdlagen, förruttnelsen) och de vegetativa processerna av vilka livet beror och som är närvarande från befruktningen till döden, i sömnen lika väl som i vaket tillstånd, När dessa livskrafter nästan samtidigt dras tillbaka i dödsögonblicket förvandlas människokroppen till ett kadaver, prisgivet åt rent fysiska och kemiska krafter som undan för undan kommer att upplösa den.</p>
<p>Och slutligen har den lyhörda upplevelsen av det inre livet visat oss den viktiga skillnaden mellan de psykiska beståndsdelarna  - föreställningar, känslor, viljemässiga impulser - och det centrala subjektet inom oss; detta "jag är" som är det medvetna vittnet till dessa.</p>
<p>Vi kan alltså uppfatta fyra olika, väl åtskilka kompenenter inom oss själva:</p>
<h3><b> - den materiella kroppen som inte framträder i sitt rena tillstånd som kadaver förrän efter döden;</b></h3>
<h3><b> - de fysiologiska processerna på vilka livet beror från befruktningen till döden;</b></h3>
<h3><b> - de psykiska beståndsdelarna;</b></h3>
<h3><b> - den mentala närvaron, vars klarhet kan bli en ständig bakgrund för vårt medvetna liv.</b></h3>
<p>De två första komponenterna, den materiella och den fysiologiska, bildar en odelbar helhet från födelsen till döden. Det är den levande kroppen, som jag har kallat för hästen inom oss.</p>
<p>Psykiskt liv och mental närvaro, som är frånvarande från kroppen under sömnen, förenar sig med den under hela det vakna livet. Det är denna helhet som jag har kallat för ryttaren.</p>
<p>Den rent materiella kroppen har hos oss framförallt en existens i rummet. Den fysiologiska komponenten av vegetativ natur existerar däremot huvudsakligen i tiden: den manifesteras i rytmisk form i växandets och avtagandets processer.</p>
<p>I och med att vi kommer in på det psykiska livet, lämnar vi tidens och rummets omedelbara påverkan. Det som inte är närvaradne här och nu, det som redan skett, våra planer och våra minnen, kan vara lika aktivt inom oss som våra aktuella intentioner och förnimmelser.</p>
<p>När det gäller det centrala jagmedvetandet är nutiden alltid dess element. I detta närvarande nu kan det omfatta tiden och rummet i ett enhetligt medvetandefält. Jagmedvetandet begränsas bara av sin egen förmåga att utvidgas och koncentreras.</p>
<p>Det kan förstora eller krympa fokus för sin uppmärksamhet i rummet, koncentrera sig på en detalj eller omfatta hela världar.</p>
<p>Samma sak är möjlig i tiden: Det är lättast att notera denna förmåga inom musiken. En musiker kan för sin inre blick bevara ett helt stort musikstycke av vilket han spelar en sats i taget, takt för takt. En dirigent som leder en operaföreställning måste hela tiden vara medveten om den helhet som förenar akterna sinsemellan, annars skulle han förlora sambanden och överblicken i sin tolkning. I varje ögonblick måste han också ha en klar rumslig bild av var de olika instrumentgrupperna sitter i orkesterdiket och hur sångarna är utspridda på scenen.</p>
<p>Det finns ingen på förhand given gräns för vad vår mentala närvaro kan begripa, i ordets ursprungliga bemärkelse, det vill säga omfatta och göra till sitt eget.</p>
<h3>Den rumsliga expansionen</h3>
<p>Till att börja med upplevde vi en polaritet mellan den yttre världen, i vilken vår aktivitet spittrar oss, och den inre världen, där vi kan återfinna oss själva under övningarna.</p>
<p>Genom de övningar jag föreslagit växer krafter inom oss, kroppsliga krafter i hållnings och andningsreflexerna som enar vår organism, psykiska och mentala krafter i ett öppnare känsloliv och i en stabilare mental närvaro.</p>
<p>På denna nya grund ger röstövningarna oss tillfälle att på nytt utvidga vårt handlings- och förnimmelsefält till att också omfatta en del av den omgivande världen.</p>
<p>Men nu är utgångspunkten annorlunda. Det handlar inte längre om att välja mellan det inre och det yttre, inte ens om att växla mellan kontakten med den inre och den yttre världen.</p>
<p>Vi har upptäckt att medvetandefält som belyses av det centrala ljus som strålar ut från vår mentala närvaro. Utifrån denna centrala utsiktspunkt är både de fenomen som vi kallar inre och de som vi kallar yttre föremål för en analog varseblivning. De kan uppfattas var för sig som genom en kikare, som i tur och ordning ställs in på var och en av dem. De kan också uppfattas samtidigt, likt beståndsdelarna i ett panorama som öppnar sig grandiost från toppen av ett berg. Det är bara utifrån denna helhetsförnimmelse som vi direkt kan varsebli de rörliga förbindelserna mellan beståndsdelarna.</p>
<p>Redan under de första övningarna har vi upplevt andningen i form av en dynamisk vågrörelse som inte bara sätter de olika delarna av kroppen i förbindelse med varandra, utan också hela kroppen i förbindelse med det omgivande rummet. På samma sätt har vi i sökandet efter balans också kunnat uppfatta de jordiska krafter som verkar i tyngdkraften som en oupplöslig helhet. I kontakt med rummet omkring utvecklar dessa krafter oss i vår förlängning, och i vår kropp samspelar dessa krafter och kommer i balans.</p>
<p>Vi har först och främst försökt utvidga vårt medvetandefält till kroppens alla dimensioner. På så sätt har det skapats en första uppmärksamhetssfär, i vilken våra kroppsliga förnimmelser men också våra inre bilder och våra känslor frigjorts, liksom moln som rör sig mot bakgrunden av vår mentala närvaro.</p>
<p>När vi nu söker ett yttre mål för röstövningarna handlar det inte om att lämna denna sfär av enhet utan om att utvidga den så att den också omfatttar den nya kontaktpunkten. Vår uppmärksamhet fokuseras på detta mål, liksom den tidigare fokuserades på andningens rörelser. Vi skall därför behålla vår uppmärksamhetssfär tillräckligt öppen så att den inom samma fält samtidigt kan omfatta både vår integrerade  organism och fokus för vårt yttre handlande.</p>
<p>Det som händer ur psykologiska aspekter i uppmärksamhetssfärens spel är analogt med en fysiska process som utspelas i ögat. När ögat fokuserar ett yttre objekt kan man urskilja två zoner av seendet: ett centralt seende som är tydligt men begränsat, och ett perifert seende som är vidsträckt men otydligare, och i vilket vi lätt kan uppfatta rörelser. Vårt totala synfält omfattar båda zonerna.</p>
<p>I de tidigare övningarna har vi kunnat uppfatta en central zon i solarplexus-området genom vilket vårt medvetandets ryttare kan behärska vår kropps häst för att tillsammans med den bilda ett enhetligt ekipage.</p>
<p>Röstövningar visar nu tydligt att den centrala utsiktspunkten inte bara gör det möjligt att uppfatta och leda kroppen som en integrerad helhet. Det är också härifrån som vi kan förnimma helhetssituationen där vi är engagerade (i detta fall förbindelsen med målpunkten) som en homogen sfär, analog med ögats perifera synfält.</p>
<p>Central utsiktspunkt och helhetssyn visar sig i verkligheten vara oupplösligt förenade. Om vi söker den utsiktspunkt som gör det möjligt att omfatta heheten kommer vi att upptäcka den centrala utsiktpunkten. Att befinna sig i den centrala utsiktspunkten är att kunna omfatta helheten så naturligt som möjligt.</p>
<p>Central utsiktspunkt och helhetssyn har samma relationer till varandra som en cirkels centrum till dess omkrets. Man kan skilja den från varandra i analytiskt avseende men de äger ingen egen verklig existens utom i cirkeln som helhet.</p>
<h3>Att stråla ut och att återvända till sig själv</h3>
<p>En subjektiv egenskap hos denna centrala utsiktspunkt är att man kan uppleva hur den sänder ut sina strålar. Man kan jämföra den med en inre sol: liksom med solens ljus känner vi hur dess osynliga utstrålning har en tendens att utvidgas kontinuerligt. Detta rent inre ljus framträder i vår upplevelse som en beståndsdel av vårt centrala "jag är". Utifrån kroppens centrala zon kan det ta vår organism, men också det universum som omger oss i besittning. Det tar sin utgångspunkt i kroppen för att sedan uttrycka sig i den fysiska världen. Det faktum att vår kropp är uttröttbar sätter gränser för det inre ljusets utvidgning, som när ryttarens handlingsmöjligheter begränsas av hästens krafter.</p>
<p>Alltefter vår energinivå och våra intressen för ögonblicket kan denna centrala utstrålning vara mer eller mindre intensiv, sträcka sig mer eller mindre långt, omfatta en större eller mindre del av den värld som omger oss. Om vi är utmattade eller deprimerade kan det hända att vi inte ens orkar fylla vår egen fysiska organism med det. Vid sådana tillfällen är vi allra mest mottagliga för sjukdomar.</p>
<p>Hur är det då med introspektionen, att återvända till sig själv? Här finns i själva verket många möjligheter.</p>
<p>Det existerar en form av introspektion då självmedvetandet genom en framtvingad mekanism återvänder till sig själv i stället för att stråla ut. Men det är påtagligt hur det då alltid får en hämmande inverkan på såväl dess fria inre funktion som på den fria relationen till omvärlden. När detta inre ljus med konstlade medel fåtts att återvända till oss sjäva fungerar det som ett nät i vilket vi känner oss fjättrade.</p>
<p>Vi kan lättast känna igen exempel på detta där omständigheterna eller yttervärlden utövar ett tryck på oss. Inför detta tryck kan rädslan eller önskan att vara till lags göra att vår egen energi vänder tillbaka till oss och gör oss till fångar i våra egna krafter.</p>
<p>Älskaren som blir impotent inför den han älskar alltför passionerat eller skådespelaren som paralyseras av rampfeber är två kända exempel. Situationer som dessa är av annat slag än den skygghet som har att göra med en svaghet i den personliga utstrålningen eller den kraftansamling som är nödvändig för att möta en akut fara. I dessa båda senare fall behåller energin sin utstrålning från centrum.</p>
<p>Det händer också ofta att de hot som kommer utifrån inte längre finns kvar men ändå fortsätter att verka inom oss, även sedan de yttre omständigheterna förändrats. Det universellt mest kända exemplet är narcissismen som orsakas av en djup oro rörande identiteten. Den för oss oupphörligen tillbaka till oss själva, spärrar in oss i inbilskhetens och självrättfärdigandets mekanismer, som blir till verkliga barriärer mellan oss och omvärlden.</p>
<p>Så är nu inte fallet när vi, liksom i de första övningarna, begränsar uppmärksamhetssfären tii vår inre fysiska joch psykologiska värld för att kunna förstå den bättre och göra den mera samlad. Den är utstrålningen från vår inre sol som då gör det möjligt för oss att se och assimilera våra inre element utan att förlora något av vår frihet.</p>
<p>Då vi öppnar oss inför yttervärlden utsätter vi oss för en annan fara. I och med att vi utvidgar vår sfär kommer vi också att omfatta nya objekt. De är laddade med en mer eller mindre stark förmåga att engagera våra känslor. Om de är mycket kraftfulla eller mycket talrika kan de fascinera oss till den grad att vi glömmer inte bara resten av omvärlden utan också oss själva. Vi förlorar alltså medvetandet om oss själva och blir helt uppfyllda av det passionerade intresse som föremålet väcker.</p>
<p>Risken är då att den utåtriktade centrifugalkraften bir starkare än centripetalkrften som förenar oss med vårt eget centrum, som när ett hjul snurrar alltför fort. Situationen kan leda till en smärsam bristning en kris jämförbar med hjulets explosion när rotationshastigheten blivit för hög.</p>
<p>Röstövningen blir ett hjälpmedel att uppfatta, använda och utveckla denna utstrålande närvaro.</p>
<p>De nya objekt som vi öppnar vårt medvetandefält för kan då bli den berikande källa utan att vi förlorar vår enhet.</p>
<h3>Spelet med omgivningen</h3>
<p>Rösten förser oss med ett ljudande material som vi kan ta med oss när vi öppnar uppmärksamhetssfären utan att vara bundna till kroppsvolymen. Inom vissa gränser gör röstens utstrålning det möjligt att konkretisera utforskandet av rummet och att ge en synlig form åt våra intentioners spel.</p>
<p>Den fysiologiska mekanism som alstrar rösten är oerhört komplex. Också denna makanism grundläggs, utvecklas och förfinas under våra allra första levnadsår. Vår uppgift är nu inte så mycket att utveckla eller omforma den utan att lära oss att använda den som en helhet.</p>
<p>Att avsiktligt manipulera röstapparaten är ett alltför okänsligt ingrepp med tanke på dess fina mekanism. Det viktiga är alltså att förstå vilka förutsättningar som indirekt befriar rösten från allt konstlat tvång och tillåter den att på ett narurligt sätt fylla sina funktioner.</p>
<p>Röstinstrumentet är oskijbart från kroppen i dess helhet, från halsen och huvudet, men också från hela bålen, som kan sägas utgöra orgelpipan i vilken rösten får sin resonans, och andningen som kan liknas vid orgelns blåsbälg. Förutsättningarna för att stämma rösten i harmoni är precis desamma som svarar för organismens helhet: balans, frihet och central närvaro.</p>
<p>Erfarenheterna visar att om dessa förutsättningar är uppfyllda hittar rösten spontant sin plats och sin klangfärg. Förändringen är ibland uppseendeväckande: en röst som ditills varit uttryck för en splittrad människas tvång och konflikter befrias och ger en klangfull bild av hela organismen. Det är inte längre fråga om en liten röst i en stor kropp eller en konstlat djup röst i en liten kropp; rösten liknar nu sin kropp.</p>
<p>Och genom att inrikta sig mot målet drar vår centrala intention indirekt med sig hela röstapparaten i en integrerad handling</p>
<p><i>Vi kan alltså öva oss att kontakta målet så lätt som möjligt, eller tvärtom pressa kraftigt mot det.</i></p>
<p><i>Vi kan slunga rösten mot målet som en pil som fastnar lätt eller som ett spjut som tränger igenom långsamt och djupt.</i></p>
<p><i>Vi kan välja mer eller mindre avlägsna mål.</i></p>
<p><i>Vi kan minska målet till en liten punkt, som vi gjorde först, eller utvidga det till att exempelvis täcka en hel väggyta.</i></p>
<p><i>En mycket intressant övning är följande: Ställ dig mitt i ett rum, och medan du därifrån sänder ut vokaler föreställer du dig att du öppnar din utstrålningssfär så att du med rösten samtidigt rör vid alla fyra väggarna, taket och golvet. Du öppnar med andra ord din röstliga intentionssfär så att du med rösten uppfyller hela rummet.</i></p>
<p>Den skicklighet i att använda rösten som man förvärvar på detta sätt går inte att skilja från det spel genom vilket vår centrala intention styr uppmärksamhetssfären i förhållande till världen omkring oss. Genom sådana övningar utvecklas inte bara rösten utan också vår närvaros utstrålning på ett harmoniskt sätt.</p>
<p>Skådespelare, dansare, musiker och andra scenartister kan på så sätt utveckla sin sceniska närvaro och lära sig att medvetet anpassa den till spelplatsens storlek, vare sig det rör sig om en teatersalong eller en televisionsstudio.</p>
<p>Övningarna med de tre vokalerna Å A I kan också nyanseras på många sätt. Man kan till exempel ljuda på samma vokal i fortlöpande serier om flera minuter eller ta en ny vokal för varje utandning eller alla tre vokalerna i följd på en och samma utandning.</p> 
<p>Det är emellertid viktigt att använda alla tre vokalerna i ungefär samma utsträckning för att övningen skall få en balanserande inverkan på det emotionella livet. De få kommentarer som jag gjort om de känslomässiga associationerna till varje vokal kommer att berikas under övningen, om du uppmärksamt och liksom ur ögonvrån iakttar vilka känslor som väcks upp inom dig när du övar en längre tid med A, I eller Å. Du kommer oundvikligen att upptäcka att den ena eller den andra vokalen känns lättare och angenämare, medan du kanske känner motstånd mot den tredje. Iaktta detta och lägg det till vad du för övrigt vet om dig själv, och fortsätt att öva de tre vokalerna till dess att du känner samma lätthet inför var och en av dem.</p>
<p>Man kan utveckla många andra övningar utifrån denna grund, i synnerhet för professionella scenartister. Jag har här bara velat förmedla de element som bäst går att integrera i det dagliga livet.</p>
<p>Om det är svårt att göra övningarna med hög röst, med hänsyn till familj och andra omkring dig, så kom då ihåg att övningarna till stor del är lika effektiva även om de utförs med låg röstnivå. Och ingenting hindrar ju att du när tillfälle erbjuds försöker dig på dem med hög röst, till exempel ute i det fria.</p>
<h3>Vokaler och konsonanter</h3>
<p>Av erfarenhet vet vi redan att vokalerna i hög grad har förbindelse med den känslomässiga färgningen av språket.</p>
<p>Konsonanterna är av en helt annan karaktär. Var och en av dem kan sägas modulera den färgning som skapats av vokalerna. De flesta konsonanter kan inte uttalas utan att man lägger till en vokal: B till exempel skrivs ensamt B men uttalas "Be".</p>
<p>I vissa språk ger konsonanterna en skulptural karaktär åt språket. Detta framträder tydligt i de germanska språken och i Skandinavien. I andra språk ger vokalernas dominans språket en sjungande karaktär, som i italienskan.</p>
<p>De flesta uttalssvårigheter hör ihop med konsonanterna. Men man får inte glömma att språket, och särskilt konsonanterna, är neuromuskulära aktiviteter, som är beroende av en koordination av helheten. Min yrkeserfarenhet har lärt mig att det ofta är utsiktslöst att angripa uttalssvårigheter analytiskt och direkt.</p>
<p>I stället har jag ofta iakttagit att en återfunnen balans i hållningen, en frigörelse av andningen och en förnyad centrering av den mentala närvaron kunnat räcka för att reducera bristerna, som ofta inte är annat än symtom på bristande känslomässig och kroppslig balans.
När man närmar sig rösten ur detta perspektiv är arbetet med vokalerna i allmänhet mycket mera effektivt än analytiska övingar med konsonanterna. Detta beror på att vokalövningarna har en befriande och reglerande inverkan på hur själva ljudet bildas och på relationen till omvärlden.</p>
<p>Därefter blir det möjligt att ta itu med konsonanterna i deras totala sammanhang när eleven utifrån sin centrala utsiktpunkt får läsa en fritt vald text. Liksom fallet var med vokalerna kommer den lästa eller reciterande texten, om man kan den utantill, att riktas mot ett yttre mål: den verkliga eller tänkta lyssnaren. Man tar på så sätt itu med uttalssvårigheterna utan att framhäva den speciellt. Tvärtom kommer de att åter integreras på sin plats i en process som står i större överensstämmelse med jaget, med relationen till yttervärlden och med förmedlingen via orden av ett intellektuellt innehåll och en känslomässig laddning som eleven själv valde när han sökte efter sin text.</p>
<p>Jag kommer ihåg en amerikansk elev som nästan helt blev av med sin accent när hon läste en fransk text, sedan hon funnit koordinationens centrala enhet. Jag har också många gånger sett en envis stamning försvinna under den återintegreringsprocess som jag beskriver i denna bok.</p>
<p>Jag skulle också vilja säga något om det bortglömda värde som ligger i högläsning. Medan tyst läsning på egen hand syftar till att sluta oss inne i oss själva kan vi genom att läsa högt för andra dela med oss av bokens innehåll och på så sätt förena det intellektuella berikandet med den känslomässiga öppenheten. På samma sätt är det en helt annan sak att få innehållet i en bok förmedlat av en levande röst i jämförelse med små svarta och förtorkade tecken hopklämda på en vit sida! Naturligtvis bör läsaren och lyssnaren växla sina roller med varandra. Varför har högläsningen, som är en så givande upplevelse tillsammans med barn, blivit så sällsynt bland vuxna?</p> 
<h3>Rösten i tal och sång</h3>
<p>Ord och sång blandas i småbarnens joller men skiljs sedan åt under uppväxten och blir separata fenomen. Talet nyanseras undan för undan framför allt genom variationer i övertonsregistret och sången genom variationer i tonhöjd.</p>
<p>Också i musiken pendlar kompositionerna för rösten mellan två poler å ena sidan kan huvudvikten läggas vid dess instrumentala karaktär, å andra sidan vid en förlängning av den talande rösten.</p>
<p>Sedan några sekel tillbaka har man kunnat notera en tendens att tillmäta det högre röstregistret ett större värde inom den västerländska konstmusiken. Sångaren konfronteras här med ytterligare svårigheter eftersom normaltonhöjden undan för undan stigit en och en halv ton sedan Mozarts tid.</p>
<p>Analyser av ljudupptagningar av människorösten har visat att låga och höga övertoner inte fördelas regelbundet över hela registret. I själva verket kan de grupperas i två poler: ett högt område där de höga övertonerna koncentreras, ett lågt område där de låga övertonerna koncentreras och i mitten ett slags öppet område, fattigt på övertoner.</p>
<p>De höga övertonerna svarar för röstens klarhet och har också större förmåga att tränga igenom. De låga övertonerna ger rösten kropp och täthet. Om dessa båda grupper av övertoner är talrika och väl balanserade, blir resultatet ett klangfullt ljud. Naturligtvis är de höga tonerna rikare på höga övertoner och de låga tonerna rikare på låga övertoner.</p> 
<p>Ju högre tonerna är, desto högre upp i kroppen ligger deras grundvibration. Ju lägre de är, desto längre ner vibrerar de. De höga övertonerna har också en tendens att vibrera högre upp i kroppen och de djupa övertonerna att vibrera djupare.</p>
<p>Om rösten är alltför fattig på djupa övertoner blir den genomträngande och metallisk. Om den förlorar de höga övertonerna blir den dämpad och klanglös och bär inte.</p>
<p>Ju högre tonhöjd de sjungna tonerna har, desto mer riktar de röstutsändningens centrum upp mot huvudet, och ju lägre de är, desto mer har de en tendens att sänka detta centrum. I båda dessa fall riskerar rösten att förlora sin homogenitet.</p>
<p>Genom att arbeta med sångare och iaktta de mest framstående nutida sångarna på scenen har jag fått bekräftelse på att ett homogent register har att göra med att man använder ett centrum som har smält samman med den centrala zon som jag tidigare beskrivit.</p>
<p>Utifrån detta centrum reglerar andningen, som är röstens "motor", röstusändningens styrka med maximal lätthet. I sådana fall vibrerar hela kroppen som en flöjt eller klarinett, oberoende av vilken ton som sänds ut. De höga tonerna har kvar de djupa övertonerna som ger dem fyllighet och mjukhet, och de djupaste tonerna har kvar de höga övertonerna som gör dem ljusare och ger dem genomträngningsförmåga. Att sända ut rösten från ett centrum gör det också lättare att få ett tydligt uttal utan onödiga konstgrepp och möjliggör en harmonisk förening av både röstens tal- och instrumentalkaraktär.</p>
<p>Eftersom den sjungande rösten fordrar en mycket större skicklighet än den talande, kräver den i ännu högre grad ett kroppsligt instrument som är välstämt i sin helhet. Uppmärksamheten på hållningens rätta balans, andningens frihet och röstutsändningen från centrum bildar grunden för en röstträning som kan bära frukt ända upp i hög ålder.</p>
<p>Alla slags avsiktliga ingrepp i diafragmans, bukens och munnens arbete kan däremot bara leda till att balansen störs. Med tiden kommer denna bristande balans att accentueras så att sångaren undan för undan berövas sina röstresurser.</p>
<p>Rösten skall utvecklas som en biologiskt odlad växt utan inblandning av konstgjorda gödningsmedel. De kan visserligen ge partiella och tillfälliga resultat, men i det långa loppet suger de ut och fördärvar jordmånen.</p>
<p>Det är ljudet självt som utvecklar rösten. Gradvis stegrade övningar gör det möjligt att använda rösten i det register där den behåller sin homogenitet och lätthet. Genom en ständig övning kommer detta område av lätthet och frihet att utvidgas av sig själv, utan att man någonsin behöver ta till tvång.</p>
<p>För eleven känns det hela tiden behagligt att öva intensivt på detta sätt, eftersom det tar hänsyn till gränserna för hans organism och lägger tonvikten vid sångens kvalitativa och musikaliska värden. Sångaren blir då indirekt skickligare inom de tre områden som har med kvantitet att göra, nämligen röstens styrka, snabbhet och fyllighet. Från början till slut blir sångarens träning ett samspel mellan hela hans väsen  --  med kropp och själ i förening -- med musiken.</p>
<p>Lägg också märke till att en riktig användning av rösten, oberoende av musikaliska kvaliteter, är ett resultat av att helheten korrdineras. Denna koordination uppstår ur ett samspel mellan de neurosensoriska mekanismerna som ligger bakom varseblivningen av ljudet och de neuromuskulära mekanismerna bakom själva ljudbildningen. Att sjunga falskt är alltid ett uttryck för att helhetskoordinationen blivit "ostämd". Den inre splittring som hindrar rösten från att exakt återge en viss ton som man hört är av samma slag som när man till exempel missar att med slutna ögon röra vid nästippen.</p>
<p>På samma sätt hör en felktig användning av talrösten samman med ett mer eller mindre medvetet inre glapp mellan de känslor man upplever och det som rösten försöker uttrycka. Mina iakttagelser under ett tjugotal år har bekräftat att den människa hos vilken helheten är väl koordinerad och enad varken talar eller sjunger på ett felaktigt, "falskt", sätt, inte mer än ett litet lyckligt barn vid god hälsa.</p>
<h3>Övningens frukter</h3>
<p>Människan har två uttrycksmedel som vart och ett ger en sammanfattning av hela varelsen: det ena är blicken, det andra rösten.</p>
<p>Eftersom röstens totala register ger uttryck både åt våra tankar och våra känslor, och eftersom utsändningen av ljudet är beroende av hela kroppen, är rösten i sanning en trogen spegel av oss själva, av det som är oföränderligt inom oss, lika väl som av det som ändrar sig från stund till annan. Röstens klangfärg är lika individuell som ett fingeravtryck.</p>
<p>Att öppna och utveckla rösten och göra den flexibel det är att arbeta med hela vårt väsen. Rösten fungerar som ett vibrationsbad, och vi kan öka dess välgörande inverkan genom övningar som de jag har föreslagit. Till och med talrösten kan bli ett sätt att ge uttryck för vår konstnärliga sensibilitet. Men i stället för att forma den efter material utifrån, som en målare eller skulptur, modellerar vi fram den inifrån i intimt samband med våra känslor och föreställningar.</p>
<p>Utifrån centrum ger rösten färg och innebörd åt den utstrålande närvaro som osynligt bär upp vår förbindelse med omvärlden.</p> 

    </Layout>
  )
}
export default AboutPage
