import * as React from 'react'
import Layout from '../components/layout'
const AboutPage = () => {
  return (
    <Layout pageTitle="Den harmoniska kroppen">

<h3>Att sitta ner</h3>
<p>Barnet är visserligen redo att andas i samma ögonblick som det föds, men det kan varken stå eller gå. Medan den lilla kycklingen springer omkring från sin första levnadsdag krävs det mer än ett år innan människobarnet uppnår samma färdighet.</p>
<p>För att detta skall lyckas krävs att nervsystemet utvecklas. Ett skyddande fettämne, myelinet, måste undan för undan bildas runt nerverna för att möjliggöra överföringen av de impulder som skall sörja för kontrollen av muskelsystemet. Denna myeliniseringsprocess går i riktning från huvudet ner mot halsen för att så småningom nå ut till hela kroppen.</p>
<p>Efter några veckor lyder halsen de viljestyrda impulserna och det lilla barnet kan hålla huvudet upprätt. Och så kommer den dag då ryggen erövrats och barnet för första gången kan sitta själv, på sin egen bak, tack vare att det etablerat detta för människan unika samspel med tyngdkraften som leder till den upprätta kroppställningen.</p>
<p>Det rör sig inte här om en medfödd förmåga utan om något nytt som förvärvats. Denna koordination med anti-tyngdkraften är en inlärning med mycket gamla rötter. Den ombesörjs till stor del av den djupast liggande ryggmusklaturen, närmast ryggraden med sina korta fibrer. Den är konstruerad för ett stabilt, kontinuerligt och i det närmast outtröttligt arbete tack vare ett kontaktsystem mellan fibrerna. Bland dessa muskler är den längsgående ryggmuskeln (m erector spinae) den viktigaste. Den omsluter hela ryggraden, från den andra halskotan ända ner till korsbenet i förbindelse med bäckenet.</p>
<p>När denna koordination är etablerad fungerar den som en samlad reflektorisk aktivitet som utlöses av tyngdkraften. Den styrs av omedvetna centra i lillhjärnan och storhjärnans bas. Tack vare denna koordination kan en frisk människa utan medveten viljeansträngning bibehålla sin lodräta kroppsställning när han sitter genom att utnyttja de hållningsreflexer eller posturala reflexer som grundlagts under de första levnadsmånaderna. Reflexerna har till uppgift att ge oss ett stabilt stöd under hela vår vakna aktivitet.</p>
<p>Vi bör klart skilja mellan å ena sidan denna reflexmässiga aktivitet som gör den lodräta hållningens muskulära grundspänning mot tyngdkraften möjlig och å andra sidan den muskelaktivitet, som gör att vi kan sätta oss, böja oss eller resa oss upp.</p>
<p>Reflexaktiviteten i ryggens djupt liggande muskler gör det möjligt för koordinationen av våra viljestyrda muskler att undan för undan förfinas. Man använder bålens ytligare liggande, långfibriga muskler, uppbyggda för ett intensivt men kortvarigt arbete. Dessa muskler styrs huvudsakligen från vårt motoriska centrum i storhjärnans bark.</p>
<p>När man väl erövrat den lodräta balansen har man inte längre något behov av ryggen eller bukens ytligt liggande muskler för det statiska arbetet. Dessa muskler kan då disponeras dels för att möjliggöra den fria andningskoordinationen, dels för att engageras helt och hållet i eventuella viljestyrda rörelser.</p>
<p>Den nödvändiga förutsättningen för att hållningsreflexerna i ryggen skall interagera normalt är ett riktigt förhållande till tyngdkraften, eller med andra ord: den riktiga lodlinjen i bålens hela massa.</p>
<p>I och med att man har funnit den vertikala balansen framkallar tyngdkraftens ständiga dragning nedåt reflexmässigt den rätta muskelspänningen. Resultatet blir att tyngdkraften subjektivt tycks förlora sin verkan. Eftersom den motbalanseras exakt av hållningsreflexerna märker man den inte. Man känner sig fysiskt lätt och fri och psykiskt i god form. Kroppen har inte längre någon tyngd.</p>
<h3>Den centrala övningen</h3>
<p>I de liggande övningarna i föegående kapitel upplevde vi det horisontala läget, det stöd som underlaget ger oss alltifrån födseln, och samtidigt också andningens frihet. Längre fram kommer vi att återfinna samma element i den sittande ställningen då vi medvetet upplever det stadium som vi passerade under livets första månader; att resa upp bålen vertikalt i balans på bäckenet.</p>
<h3>Balans</h3>
<p>För denna övning behöver vi en stol eller en pall av normal höjd med horisontal sits. Det går inte bra med en fåtölj eller en soffa eller en sängkant och inte heller med en stol med alltför låg höjd, i alla fall inte till en början.</p>
<p><i>Sätt dig på främre delen av stolsitsen, utan något stöd för ryggen, så att sätet, men inte låren, får stöd mot underlaget.</i></p>
<p><i>Lossa på krage och skärp om det behövs, så att inga kläder sitter åt eller trycker mot halsen, bröstet eller magen. Många moderna, åtsittande byxor är bekväma när man står, men har en tendens att strama när man sitter. I så fall kan det bli nödvändigt att knäppa upp i midjan för att släppa magen fri.</i></p>
<p><i>Släpp isär knäna så att det bildas en vinkel mellan låren som kan variera melln 30 och 90 grader. När du kan behålla låren i detta läge utan ansträngning är den individuella vinkeln den rätta. I denna vinkel kan också låren och bäckenet spänna av.</i></p>
<p><i>Placera båda fotsulorna mot golvet, ungefär rakt under knäna. Vinkeln mellan fötterna skall motsvara vinkeln mellan låren. Justera ställningen till dess benen vilar stadigt och bekvämt.</i></p>
<p><i>I denna ställning är det önskvärt att knäna befinner sig något lägre än bäckenet.Det ger en bättre upprätningsreflex nedifrån och upp genom ryggen.</i></p>
<p><i>Om dina ben är mycket långa så att knäna kommer högre upp än bäckenet kan det vara nödvändigt att höja stolssitsen med en kudde eller en bok. En pianopall med reglerbar höjd kan också fungera bra.</i></p>
<p><i>För samman händerna på ett sätt som känns naturligt för dig och låt handlederna stödja på låren ganska nära bålen, så att armarna vilar avspända utan att dra dig framåt.</i></p>
<p><i>Du är nu redo att leka med tyngdkraften för att finna den optimala balansen för din kropp i dess nuvarande tillstånd.</i></p>
<p><i>Gör dig först medveten om din bål som en helhet, från bäckenets botten ända till hjässan. Sträck så på bålen, långsamt och utan ansträngning, som för att röra vid taket med hjässan. Spänn sedan av genom att låta bålen, utan ansträngning känna stödet från stolssitsen, som en pelare i balans,sten mot sten: bäcken, bröst och huvud i jämvikt utan någon spänning.</i></p>
<p><i>Upprepa denna sträckning av bålen två gånger och låt den varje gång följas av en vila i balans utan ansträngning. Med hela bålen på detta sätt avspänd och med buken, bröstkorgen och huvudet förenade till en helhet pendlar du nu ett tiotal gånger med små rörelser från sida till sida, till dess du hittar den lodlinje som du tycker ger dig det bästa balansläget mellan de båda sidorna.</i></p>
<p><i>Pendla sedan ett tiotal gånger med små rörelser framåt och bakåt. Försök också här att avsluta i den lodlinje där framåt och bakåt neutraliseras i en naturlig och stabil balans.</i></p>
<p>Om du nu har hittat den riktiga lodlinjen sitter du bekvämt, väl förankrad i stolssitsen, utan att känna någon spänning. Hållningsreflexerna stöder dig osynligt, medan den ytliga muskulaturen är i vila.</p>
<p>Särskilt halsen är avspänd. De hållningsreflexer som bär upp huvudet sträcker sig igenom hals och nacke som en förlängning av det stora flöde som stiger upp från bäckenet. Den viljemässiga kontrollen av muskulaturen genom nervsystemet utgår från huvudet, medan den reflexmässiga startar nedifrån kroppens underlag i en mäktig koordination som förfinas ju högre den når, precis som ryggradens kotor blir allt mindre ju närmare huvudet de är belägna. Längst upp bärs huvudet upp av halsen som blomman på sin stjälk, livnärd av en ström av sav som stiger upp från jorden.</p>
<h3>Former och processer</h3>
<p>Lägg märke till att även om det muskulära stödet hör samman med ryggraden skall kroppens mittaxel, kring vilken kroppen finner sin balans och kring vilken kontakten med tyngdkraften utspelas, inte förväxlas med ryggraden. Mittaxeln går lodrätt mitt igenom bålen och utmynnar i bäckenet i sittbenen, de skelettutskott som vi sitter på.</p>
<p>Mittaxeln kan liknas vid en osynlig lodlina som går genom hela buken, bröstkorgen och huvudet. Om dessa tre plan inte befinner sig i en riktig balans i förhållande till varandra blir bålen ett slags lutande tornet i Pisa och man måste spänna sig för att inte sjunka ihop. Då tvingas den ytligt liggande muskulaturen, som är avsedd för ett intensivt men kortvarigt arbete, att vara i funktion permanent på samma sätt som hållningsreflexerna, och det är härifrån som de kompensatoriska spänningarna i buken, ryggen, halsen och axlarna kommer. Med tiden utvecklas spänningarna till muskelkramper, smärtor och blockeringar. Leder som ständigt befinner sig i felaktiga lägen kan också gradvis utveckla sjukdomar som artrit och artros.</p> 
<p>För sådana kompensationsskador finns det inget annat varaktigt botemedel än att på nytt söka sig fram till en riktigare balans. När balansen gjort de kompensatoriska spänningarna överflödiga kan de avta eller åtminstone upphöra att öka. Balansen gör också att lederna kan återgå till sina funktionella lägen.</p>
<p>Sökandet efter balansen kommer att förfinas med tiden. de första försöken kan bara bli trevande, men det räcker med att varje gång, så gott man kan, försöka hitta den för ögonblicket bästa balansen. Redan detta kommer att lösa upp vissa spänningar, förbättra förnimmelsen av den egna kroppen och leda till ett bättre sätt att vara, som visserligen alltjämnt är relativt men redan fullt märkbart. Dessa första resultat jämnar vägen för de framsteg som följer sedan.</p>
<p>Musklernas vanemässiga sätt att arbeta måste undan för undan förändras så att de nuvarande kompensationerna kan ersättas med en funktionell enhetlighet som är äldre och ligger djupare i vävnaderna. Utom vid vissa undantagsfall (förlamning till exempel) finns det ursprungliga funktionella systemet alltid där, berett att fungera men dolt och insnört av spänningar som vi lagt oss till med senare. Det ursprungliga systemet etablerades under våra första levnadsmånader medan kompensationerna  är ytligare och yngre. Men vi kan inte bli av med dem utan att på nytt ingå en förening med de äldre reflexerna, som är vårt verkliga stöd.</p>
<p>Det sökande efter balans som jag föreslår här är en process som verkar på längre sikt genom att man regelbundet repeterar övningen. Hållningsreflexerna som helhet utgör också en process, som upprättar vissa förbindelser mellan bålens delar. Erfarenheten har visat att det på sikt är mycket effektivt att närma sig dem som en helhet som påverkar hela bålen.</p>
<p>Jag gjorde själv i början misstaget att negligera helhetsprocessen till förmån för den enskilda formen. Jag försökte lösa mina svårigheter genom att utifrån imitera det som jag tyckte var den rätta formen, jag härmade lärare eller andra beundrade förebilder. Alla dessa försök blev fiaskon, och hur många sådana fiaskon har jag inte sedan sett omkring mig!</p>
<p>Dessa felaktiga försök går bara att genomföra om man tar hjälp av det ytligare, viljestyrda muskelsystemet som egentligen inte har detta till uppgift. När allt kommer omkring lägger de bara ytterligare kompensationer till dem som redan finns.</p>
<p>Det är alltså med avsikt som jag inte beskriver ryggens, halsens eller bäckenets "rätta form" i den sittande övningen. Formen varierar från person till person och allt efter övningens förlopp. I varje ögonblick ger formen uttryck åt vårt aktuella tillstånd, fysiskt och psykiskt, men också åt hela vårt förflutna med de ärr det lämnat i vår kropp. Men formen ger också uttryck åt de underliggande, sunda processerna. Det är dessa som ger något universellt och allmängiltigt åt friska små barns rörelser och hållning.</p>
<p>Ryggraden bildar en integrerad helhet i vilken krökningarna i ländryggen, bröstryggen och halsryggen balanseras och kompenserar varandra.</p>
<p>Jag erbjuder övningar där dessa kompensationer reduceras undan för undan genom att de balanseras mot varandra i en enda orgaisk helhet.</p>
<p>Det muskulära systemet kan behålla sin styrka bara genom att arbeta. Men för att arbeta måste det ha ett motstånd. Liksom hantlar erbjuder ett motstånd så att armmusklerna kan stärkas, bjuder kroppens egen vikt genom tyngdkraften det motstånd som hållningsreflexerna behöver för att bli starkare.</p>
<p>Om vi alltså placerar bålen i en lodrät balans utan ryggstöd skapar vi på så sätt automatiskt de förutsättningar som tvingar hållningsreflexerna att arbeta och stärkas.</p>
<p>Av iakttagelser och praktisk erfarenhet har jag förstått vilken exceptionell visdom som reglerar dessa djupa processer och deras anpassning till de hinder som vi omedvetet sätter upp för dem. Inom vissa gränser naturligtvis, som dock är mycket vidare än vi föreställer oss, är du alltid i verksamhet för att dra största möjliga fördel av de usla villkor som vi påtvingar dem.</p>
<p>Om vi tar hjälp av den visdom som ligger i reflexerna, om vi under övningens lopp mer och mer utgår från dessa processer, kommer de att fördjupa sin verkan. Vi kan då få se hur samma, levande och fria former växer fram inifrån, former som liknar de storslagna exempel vi kan finna i antikens eller renässansens bildhuggarkonst.</p>
<h3>Frihet</h3>
<p>I vår kropp, sådan den är just nu, har vi alltså funnit tre nivåer som fungerar samstämmigt:</p>
<p>1. vår medvetna intension att fungera på bästa sätt;</p>
<p>2. mycket gamla och djupt liggande reflexer som till exempel hållningsreflexerna, som verkar från djupet av vårt kroppliga omedvetna för att ge oss ett sunt och effektivt stöd;</p>
<p>3. ett skikt av deformeringar och kompensationer som vi lagt oss till med under loppet av vår psykologiska och kroppsliga utveckling. Denna nivå framträder som ett mellanplan mellan de medvetna intentionerna och de djupare och mer omedvetna skikten, som trots allt ansvarar för vår överlevnad och vår fysiska integritet så långt omständigheterna tillåter.</p>
<p>Den första etappen i den sittande övningen gick ut på att återfinna bålens optimala lodräta
balans inom våra aktuella gränser. Vi har nått dithän genom att medvetet förnya kontakten med de ursprungliga hållningsreflexerna och genom att undan för undan koppla av de perifera spänningarna, som är vanemässiga uttryck för våra omedvetna svårigheter.</p>
<p>När vi går över från den horisontella kroppsövningen till den sittande, vertikala, kan man dessutom via ledförbindelserna mellan ryggrad och bröstkorg klart se samspelet mellan kroppshållning och andning.</p>
<p>En bröstkorg som genom felaktiga andningsvaror blivit alltför öppen eller alltför hopklämd påverkar bröstkotorna och indirekt också den övriga ryggraden. Denna fungerar som en integrerad helhet och kompenserar oundvikligen varje lokal deformering på någon annan nivå.</p> 
<p>Om nu sökandet efter den optimala balansen gjort det möjligt för oss att åter utgå från hållningsreflexerna så kan de emellertid inte spela sin roll helt och fullt förrän de deformeringar som beror på den felaktiga andningskoordinationen gradvis avtagit.</p>
<p>Redan i den liggande övningen har vi kunnat gå in i den process som frigörandet av andningen innebär. När andningen återfått största möjliga frihet kan den ge en inre massage som spänner av, ger tonus och balans åt den muskulära koordinationen som omsluter hela bålen från bäckenbotten ända till halsen.</p>
<p>När vi nu sitter i den lodräta ställningen kommer andningens muskelkoordination att samarbeta med hållningsreflexerna och undan för undan skulptera om kroppen. Dessa båda stora kretslopp av reflexer fungerar som en osynlig skulptör, som genom att aktivera de försvagade funktionerna och frigöra de ytliga spänningarna låter de ursprungliga, underliggande formerna träda fram på nytt.</p>
<p>Vi märker då att hållningsreflexerna och andningsreflexerna understöder varandra. Om man hittar den riktiga lodlinjen när man spänner av de perifera spänningarna öppnar detta kroppen och ställer den till förfogande för andningens flöde.</p>
<p>Dessutom strävar den allt friare andningen efter att återföra bålens hållning fill den riktiga lodlinjen, vilket i sin tur underlättar för andningsflödet att passera genom halsen, bröstet och buken.</p>
<p>När vi har hittat balansen kan vi med förtroende vila i de anti-tyngdreflexer som håller kroppen upprätt och vända uppmärksamheten mot andningen. Om vi har ägnat oss åt den liggande övningen en tid har vi redan känt den inre smaken av en friare andning. Det är denna som vi nu skall försöka återfinna i den lodräta ställningen.</p> 
<p><i>Nu skall vi inte hålla händerna mitt på kroppen utan i stället låta dem vila tillsammans på övre delen av låren.</i></p>
<p><i>Håll munnen stängd och andas bara genom näsan</i></p>
<p><i>Om man är förkyld eller kroniskt täppt i näsan bör snyta sig ordentligt för att göra den riktigt ren och därefter sluta munnen. Ta några djupa andetag, varannan gång genom vänster näsborre och varannan genom höger genom att hålla för den andra näsborren. Detta aktiverar blodcirkulationen och stimulerar nervändarna i näsans inre. Dessa senare påverkan genom reflexer diafragmans verksamhet. Håll hela tiden munnen sluten. Den luft som i den fria andningen som dras in genom diafragmans aktivitet räcker för att hålla näsan fri. Undan för undan kommer nästäppan att försvinna.</i></p>
<p><i>Vi lämnar andningen fullständigt fri att själv hitta sin plats. Vi  ger den tid att installera sig i vår lodräta kropp och ta den i besittning på sitt eget sätt</i></p>
<p>Acceptera att andningen kan göra avbrott och ta olika omvägar till dess att en viss regelbundenhet och stabilitet inträder av sig själv och som underlättas genom att kroppen är orörlig och i avspänd balans.</p>
<p>Alla mina kommentarer och alla de iakttagelser som du själv kunnat göra under den liggande övningen gäller också här.</p>
<h3>Mental närvaro</h3>
<p>De två första elementen i den sittande övningen var: balans för bålens fysiska massa utan någon ansträngning tack vare hållningreflexerna och frihet för aandningen och med den för alla de omedvetna fysilogiska processerna, för vilka den på sätt och vis är en budbärare.</p>
<p>Till detta kommer nu ett tredje element. Efter den fysiska aspekten med balansen som nyckelord och den fysiologiska med friheten som nyckelord kommer vi nu till den psykologiska, vars kännetecken är den mentala närvaron.</p>
<p>När balansen är stabil och andningen har funnit sin egen regelbundna rytm, fungerar dessa båda på egen hand genom reflexernas spel. Focus för övningen kan då i stället flyttas över till den mentala inställningen</p>
<p>Man kan likna den mentala närvaron vid en brinnande lampa och uppmärksamheten vid det ljussken den kastar. För att förstärka och stabilisera detta ĺjus riktar vi det mot ett bestämt mål och etablerar en medveten kontakt med detta. Det är denna kontakt som vi försöker behålla och medvetet återvänder till när vi har förlorat den.</p>
<p>Lägg märke till att när jag talar om uppmärksamhetens ljus så är det inte enbart en liknelse. Det kan hända, och det händer ofta, att vi med öppna ögon står rakt framför ett föremål eller en person men inte ser dem därför att vi har tankarna på annat håll. Och eftersom vi inte ser dem kommer vi inte heller ihåg dem. Det yttre ljuset är alltså inte tillräckligt för att vi skall se.</p>
<p>För att den fysiska perceptionen skall omvandlas till en medveten varseblivning krävs också detta uppmärksamhetens ljus, som vi liksom inifrån kastar på objekten, och inte bara på de yttre objekten utan också på de inre, dvs våra föreställningar, känslor och minnen.</p>
<p>Denna iakttagelse kan leda oss ytterligare ett steg. För detta ljus, som uppstått ur vår mentala närvaro, framträder den inre och den yttre världen som två beståndsdelar i ett enhetligt uppmärksamhetsfält. Att iaktta ett inre minne och därefter ett yttre föreemål är inte mycket annorlunda för detta ljus än att iaktta ett föremål på himlen efter att ha iakttagit ett föremål på marken. I båda fallen handlar det bara om att ändra den kontaktpunkt på vilken uppmärksamheten fäster sin ljusstråle.</p>
<p>Den mentala närvaron visar sig alltså vara en företeelse som radikalt skiljer sig från alla övriga i vårt psykologiska liv. Alla tankar, alla känslor, alla förnimmelser som vi är medvetna om kan bli objekt på vilka ljuset från den mentala närvaron projiceras. Det är endast denna närvaro som inom oss kan göra anspråk på benämningen subjekt.</p>
<p>Vi är ofta ovetande om detta elementära faktum, Det beror på att denna unika och centrala funktion, detta subjekt som är närvarande inom oss, mer eller mindre fefinner sig i dvala. Sovande försöker det, liksom i en dagdröm, identifiera sig med förnimmelser, idéer och känslor. Medvetenheten om detta subjekt kan på så sätt uttryckas som "jag är ledsen" eller "jag känner mig i form".</p>
<p>Men ibland händer det, under påverkan av en yttre intensiv eller oväntad situation, att denna sjlvständiga mentala närvaro, denna inre förnimmelse av "jag är" framträder tydligt. Då sker ett slag frigörelse, alldeles oberoende av hur intensiv vår känsla, vår glädje eller vår sorg är för stunden.</p> 
<p>I detta ögonblick vet man med bländande visshet: "jag är inte mina känslor. men jag är och har känslor".</p>
<p>Sådana intensiva upplevelser varar i allmänhet inte länge. Det förefaller som om praktiskt taget alla människor kan erinra sig ett eller ett par liknande ögonblick. I de flesta fall fäster vi ingen särskild uppmärksamhet vid dem och de faller i glömska. Men det är dessa ögonblick som kan tjäna som referensram och vara vägledande i en metod som den jag föreslår.</p>
<p>Detta centrala medvetande, denna förnimmelse av "jag är", visar sig alltså i den inre erfarenheten som en bakgrund mot vilken våra tankar, känslor och handlingar framträder, som när en klar himel skuggas av moln av alla de slag: lätta och tunga, moln som färgats rosa av våra glädjeämnen eller svarta av våra sorger. Liknelsen kan också bekräftas på ett annat område, nämligen i kontrasten mellan våra tankar, känslor och sinnesintryck som hela tiden är stadda i rörelse, förändras och utvecklas, och den alltid identiska men mer eller mindre intensiva förnimmelsen av detta "jag är", varje gång den blir medveten.</p>
<p>Existensen av denna mentala närvaro, detta centrala "jag är" som både medveten och personlig erfarenhet är något som radikalt skiljer den mänskliga arten från alla djurarter. Här föreligger ett kvalitativt språng i utvecklingen, analogt med det som skiljer växtriket från djurriket.</p>
<h3>Att sitta uppmärksamt</h3>
<p><i>Vi återvänder nu till vår övning</i></p>
<p><i>Denna gång ska vi ta blicken till hjälp: utan att sluta ögonen helt sänker du blicken mjukt ner mot golvet. Vid en vinkel av ungefär 45 grader från horisontlinjen kommer du att hitta ett viloläge där ögonen kan förbli halvslutna utan att fixera något föremål, men utan att stänga ute det yttre ljuset. Medan den liggande övningeen utfördes med slutna ögon skall vi hädanefter söka nå en tonisk balans mellan den djupa avspänningen och den spänning som råder i ett mera aktiverat tillstånd. Ögonens läge med halvt sluten blick svarar mot en sådan balans och har också en reflektorskt avspännande verkan på halsen.</i></p>
<p><i>Om man har en kraftig nervspänning i och kring ögonen med värk efter att ha läst, skrivit eller tittat mycket kan man gärna sluta ögonen i början av övningen, till dess de blivit så avspända att man kan återvända till balansen med halvslutna ögon.</i></p>
<p><i>Precis som i den liggande ställningen stabiliserar och utveclar man konkret sin mentala närvaro genom att ta kontakt med andningen. Sitt lodrätt med fri andning och känn lugnt efter hur du skall ta kontakt med andningen på ett nturligt sätt. Händerna skall inte längre vila på magen utan det är inifrån som du skall förnimma andningen.</i></p>
<p>Det rör sig om samma sökande som när en ryttare sitter upp p en häst utan sadel för att känna efter var och hur han skall sätta sig för att så naturligt som möjligt anpassa sig till sitt riddjur. Sitter han alltför nära halsen eller alltförnära bakdelen irriterar han hästen och sitter själv inte bra. När han hittar den rätta platsen blir resultatet en lättnad både för hästen och ryttaren.</p>
<p>När denna kontakt så småningom etablerats och vanan undan för undan gör det hela enklare, består hela övningen i att återvända hit varje gång vi blivit distraherade och fjärmat oss därifrån. Om den subtila och lätta övning upprepas lungt, stärker den precis som i den första övningen på golvet undan för undan vår mentala närvaro på samma sätt som när vi genom att böja armen stärker bicepsmuskeln. Detta är övningens hjärtpunkt.</p>
<h3>Övningens frukter</h3>
<h4><b>Balanskonstnären</b></h4>
<p>I förra kapitlet beskrev jag vilka verkningar andningsövningen kunde ha på vår organism. Samma effekter återfinns också och fördjupas i den sittande övningen. Den stor skillnaden består i att anti-tyngdreflexerna nu sätts i spel och gör det möjligt att behålla den upprätta vertikala hållningen.</p> 
<p>Ryggradens stabila upprätta hållning ger människan en särställning som radikalt skiljer henne från djuren. Det är runt denna vertikala axel, stöttad av hållningsreflexerna, som den fina koordinationen av bål, armar och ben undan för undan byggs upp. Den utgör grunden för all mänslklig aktivitet.Genom förmedling av det retikulära aktiveringssystemet i hjärnstammen är hållningsreflexernas banor några av de viktigaste reglerande funktionerna för kroppens tonus som helhet och psykologiskt sett för den vakenhetsgrad som är förbunden med kroppens tonus.</p>
<p>Vi kan dagligen lägga märke till hur fysisk trötthet eller psykisk depression minskar vår motståndskraft mot tyngdkraften. Denna ökar då sin dragningskraft nedåt, kröker ryggeen, tynger ner huvudet och pressar samman bröstet. Om vi är upphetsade och ivriga däremot kan anti-tyngdkrafterna inom oss aktiveras till den grad att vi inte längre kan hålla oss kvar på marken utan rusar upp, hoppar av glädje och dansar runt utan att kunna hejda oss.</p>
<p>Mellan dessa båda ytterligheter finns en balans. När den är sund är den varken statisk eller förstelnad utan snarare lik balansarmen på en våg som pendlar helt lätt mellan de båda viktskålarna, eller som balanskonstnären som går på den spända linan. Om han gjorde alltför stora rörelser skulle han ramla ner. Men om han inte rörde sig alls skulle han också ramla: man kan inte få en staty att hålla balansen på en lina. Det är paradoxalt nog den behärskade och koncentrerade rörelsen som ger balanskontnären hans stabilitet när han pendlar fram och tillbaka utan att vara stel.</p>
<p>Det är denna riktiga balans mellan den yttre dragningskraften från gravitationen och de framvällande inre vital krafterna som förstärker den sittande övningen.</p>  
<p>I detta tillstånd får hållningsrefexernas aktivitet och avspänningen i ryggens ytligt liggande muskulatur en reglerande inverkan på det vegetativa nersystemet, som är av största betydelse för vår hälsa. Två strängar autonoma nervganglier fäster på vardera sidan om ryggraden, utefter kotkropparnas sidor, precis som i den kinesiska medicinen de två parallela linjerna av akupunkturpunkter som omger ryggraden och på vilka alla inre funktioner projiceras. Som alla akupunktörer framkallar en muskelspänning på en bestämd plats i ryggen alltid hyperaktivitet i de tillhörande akupunkturpunkterna. Spänningen reflexteras alltså i de organ som har förbindelse med denna punkt eller i detta ganglion och skapar obalans i funktionen. En jämn tonus, till exempel den som resulterar i en riktig balans, kommer alltså med hjälp av dessa punkter och dessa sympatiska nervknutar att åstadkomma en reflexstyrd reglering av alla inre organ som helhet.</p>
<p>Även andningen spelar en roll när vi på detta sätt söker efter balans. Också här är det överdrifterna som bäst kan förtydliga fenomenet: en maximal utandning böjer oss ner mot jorden medan en extrem inandning lyfter oss uppåt. Dessa rörelser finner vi också, fast i en mycket subtilare grad, i varje andningscykel. Varje inandning fyller oss, med risk att vi förlorar kontakten med våra jordiska rötter.</p>
<h3>Hästen och ryttaren</h3>
<p>Erfarenheten visar att genom att söka efter den inre sadelplatsen varifrån vårt medvetandes ryttare på bästa sätt kan rida på andningen, får vi hjälp att upptäcka en central zon av balans och frihet.</p>
<p>Runt denna zon kan de båda uppåt- och nedåtgående krafterna komma i balans, dels i spelet mellan hållningsreflexerna och tyngdkraften, dels det alternerande andninngsflödet som i tur och ordning sluter sig mot den nedre delen av kroppen och öppnar sig mot den övre.</p>
<p>Om vi behåller kontakten med andningen kommer den själv att leda oss till denna centrala utsiktpunkt, den inre plats varifrån medvetandet "rider" på kroppen som en homogen helhet, levandegjord av andningens fria vågrörelse.</p>
<p>Vi kommer då att uppleva klart, inte "jag är min kropp", utan "jag är" i centrum av mig själv, och "jag har en kropp". Jag kan alltså rida på denna kropp fullt medvetet, så att jag helt blir ett med den. Jag kan bli en god ryyare och skapa en perfekt, funktionell enhet av detta ekipage utan att hemfalla åt misstaget att förväxla mig själv med hästen.</p>
<p>Erfarenheter från sömnen borde för övrigt vara tillräckliga för att undvika en sådan illusion. Om man iakttar en kropp under djup sömn ser man tydligt en häst som för tillfället är utan ryttare, det vill säga en fysisk massa (det framtida kadavret), som genomströmmas av fysiologiska processer (vegetativa funktioner) men har berövats de psykiska elementen (tankar, känslor, handlingsvilja) och medvetandet om sig själv ("jag är").</p>
<p>Om vi inte gör misstaget att förväxla hästen med ryttaren blir vi inte heller blinda för deras ömsesidiga påverkan. Ryttaren misstag kan skada och försvafga hästen på samma sätt som hästens sjukdomar minskae ryttarens uttrycksmöjligheter.</p>
<p>En levande med perfekt fysisk och psykisk hälsa får automatiskt tillbaka denna harmoniska enhet mellan ryttare och häst när han vaknar upp ur sömnen. Men det är tyvärr alltför sällsynt och tycks bara vara naturligt hos djur och små barn. Allt eftersom barnet växer upp blir dess psykiska liv rikare och mera komplicerat. det "jag är" som är medvetet om sig själv framträder och differentieras. Eller med andra ord: ryttaren utvecklas medan hans kontakt med kroppen, hans häst, blir allt mindre otvungen och naturlig. Olika påverkningar, i synnerhet psykiska och sociala, ökar störningspunkterna ända fram till den dag då han måste söka återvinna ekipagets enhet och frihet genom en medveten ansträngning. Och det är just detta sökande som ligger bakom denna bok.</p>
<h3>Den centrala utsiktspunkten</h3>
<p>De tre grundelementen i övningen: den fysiska massans balans, de fysiologiska processernas frihet och den mentala närvaron flätas i praktiken in i varandra för att leda till upptäckten av den enhet som råder mellan hästen och ryttaren, mellan kroppen och det mentala.</p>
<p>Men till sist beror ändå enheten i dettra ekipage på ryttaren. Det är från hans misstag och felaktiga vaanor som friktionerna och spänningarna härstammar. Integreringen beror på hans mentala klarsyn och på vilket sätt den står i förhållande till kroppen.</p>
<p>Vi kan inte medvetet påverka de omedvetna reglerande mekanismerna i vår kropp utan måste i stället välja en indirekt väg. Genom att återställa kroppens balans, befria de inre reglerande rytmerna och ta vägen via andningen skapar vi på nytt förutsättningarna för den djupa, omedvetna visheten att arbeta optimalt.</p>
<p>Undan för undan kommer då en central zon att uppenbara sig för oss och bli mer och mer tydlig för vår varsebildning. Den är belägen i maggropen, mellan revbenen och naveln.</p>
<p>Runt denna zon balanserar det omedvetnas pol med sitt centrum i bäckenet och det medvetnas pol med sitt centrum i huvudet. Den centrala zonen motsvarar den nivå där diafragman stöder sin muskulära kupol mot ryggradens insida. På denna nivå breder också nervknuten solarplexus ut sina förgreningar. För mig är termen solarplexus (ordagrant ungefär "Solfläta") mycket mer än bara en enkel bild. Det är verkligen fråga om en inre sol, kring vilken vår organism är strukturerad som ett planetsystem. Genom denna sol kan vårt medvetandes ljus förena sig med kroppen.</p>
<h3>Burens upplösning</h3>
<p>Den sittande övningen stänger av vår förbindelse med yttervärlden för en kort stund. Ensamma, orörliga och tysta reeducerar vi de handlingar och förnimmelser som riktas mot omvärlden till ett minimum.</p>
<p>Den inre världen kommer därigenom att få en ovanlig betydelse. Förnimmelser från vår egen kropp, våra känslor och föreställningar kommer att uppta större delen av vårt medvetandefält. Liksom stjärnorna fördunklas av dagsljuset men åter blir synliga då natten faller på, kommer många aspekter av vårt inre liv att framstå för oss i en ny dager.</p>
<p>Vi har redan noterat skillnaden mellan vår centrala mentala närvaro, vårt "jag är" som är unikt för människan, och det psykiska innehållet, tankar, känslor och förnimmelser, som i olika utsträckning också förekommer hos djuren. Vi har också sett att detta "jag är" är jämförelsevis svagt och därför ofta faller i dvala då det översvämmas av en ström av förändringar på det psykiska planet.</p> 
<p>Under dessa ögonblick tänker vi, handlar, är berörda, men vi är inte där som individer, för att kunna vara observanta vittnen till dessa inre förändringar. Vi är som den molntäckta himlen vars eget ljus inte syns någonstans utan bara visar sig blandat med molnen, som på så sätt och vis lånat sitt ljus av himlen.</p>
<p>När vi försöker behålla kontakten med andningens våg ger vi en fast hållpunkt åt uppmärksamheten.</p>
<p>Men vi får inte räkna med att vi kan klippa av alla andra föreställningar i och med detta. I stället verkar det efter några ögonblick som vår ansträngning att nå mental stabilitet ständigt hotas av vågor av bilder, tankar, känslor som oupphörligt dyker upp. Vår medvetna kontakt med andningen tycks gå förlorad nästan lika snabbt som vi hittade den. Vi måste ideligen gå tillbaka i en ständig kamp, där ögonblicken av mental klarhet är som glimtar av en blå himmel mellan oceaner av molm.</p> 
<p>Hur ska man då gå tillväga?</p>
<p>För det första bör man vara medveten om att detta inte händer bara därför att vi håller på med övningen. I stor utsträckning är det helt enkelt vår vanliga situation, som nu blivit mera tydlig genom ansträngningen att vara mentalt närvarande. Detta nya ljus gär det möjligt för oss att tydligare bli medvetna om vår vanliga svårighet.</p>
<p>För det andra har jag redan beskrivit hur alla de känslor som undertryckta sedan barndomenh på något sätt manifisterar sig i form av muskelspänningar. När dessa blivit kroniska bildar de vad jag kallar en bur en funktionell helhet av spänningar med uppgift att försvara organismen mot inre drifter och yttre retningar som den förkastar och säger nej till.</p> 
<p>Genom att återge kroppen en riktigare balans och frigöra andningen har vi löst upp ett antal av dessa spänningar. När de gamla spänningarna från olika livsepoḱer gradvis spänns av får det två olika följder.</p>
<p> -- på det fysiska planet har de kroniskt spända områdena undan för undan blivit okänsliga. I och med avspänningen återkommer en känslighet som ibland kan upplevas som smärta. Jag nämnde detta apropå andningsmassagen. Ett friskt finger gör inte ont; ett stelfruset finger gör inte heller ont, eftersom det förlorat känseln. Men medan det värms upp passerar det ett stadium då relationen mellan liv och känslighet, eller mellan blodcirkulationen och nervsystemet, ger upphov till en maximal smärta. När tillståndet åter blir normalt kommer smärtan att ebba ut. Något liknande kan hända när burens muskler spänner av som ett resultat av övningen;</p>
<p> -- på det psykologiska planet kan vi iaktta ett fenomen som ofta rapporteras av massörer eller avspänningsterapeuter: allt pekar på att i och med den muskulära avspänningen sker en psykolgisk reaktivering av de föreställningar och känslor som har trängts undan allt sedan buren utkrstalliserades, men som hela tiden omedvetet förblivit förknippade med den.</p>
<p>Detta bidrar till att öka turbulensen i vårt inre, men det öppnar också dörren så att en integrering av de förnekade elementen blir möjlig. De har ju blockerat vårt psykiska liv på grund av att de varken lyckats bli fullständigt bortträngda eller fullständigt assimilerade.</p>
<p>Men nu befinner vi oss i en situation som gör det möjligt att kännas vid och acceptera det som vi varken klart kunde kännas vid eller acceptera helt och hållet när vi upplevde det i verkligheten, mitt inne i en kris eller när vi var barn. Dessa element börjar vi nu uppfatta som våra egna. Nu är vi ensamma, tiden har gått, förhållandena är annorlunda och huvudpersonerna från det förflutna finns inte längre omkring oss. Det handlar alltså verkligen om våra egna önskningar, vår egen vrede, vår egen fruktan och inte om någon annans.</p>
<p>Och själva förutsättningarna för övningen hjälper oss att betrakta alla dessa känslor och minnen som en mer samlad helhet: vi kan känna oss mindre hjälplösa och mindre splittrade inför ett element från ett förflutet som stiger upp inom oss och fortfarande bränner.</p>
<p>Om vi å andra sidan inte forcerar övningen på något konstlat sätt visar erfarenheten att dessa psykiska återuppvaknanden kommer allt regleras omedvetet. De frigörs successivt, från de ytligare skikten till de mer djupliggande, utan att gränsen för vad vi kan integrera överskrids.</p>
<h3>Den psykiska förvandlingen</h3>
<p>Vad menas då med att "integrera" dem? Och hur skall det gå till?</p>
<p>Det enda man har att göra är att se klart och acceptera till fullo.</p>
<p>Att se klart innebär att vara närvarande för att se dessa inre företeelser exakt sådana som de är, utan att vare sig lägga till eller dra ifrån någonting. Att enbart vara vittne.</p>
<p>Att acceptera till fullo innebär att utan förbehåll eller invändningar säga "ja" till det som en stor del inom oss skulle vilja förneka: ja så är det, ja, detta finns inom mig.</p>
<p>Det finns två sätt att säga nej, och båda sätten innebär ett hinder för att vi ska kunna helt och fullständigt assimilera det som lever inom oss.</p>
<p> -- det första och mest uppenbara sättet är att förneka det som vi inte tycker om och som får oss att lida;</p>
<p> -- det andra är att med konstlade medel klamra oss fast vid det som vi tycker om och som gör oss lyckliga. Det innebär med andra ord att säga "nej" till att allting oundvikligen förändras, och det var just det som i det förflutna hela tiden fördärvade våra värdefullaste ögonblick.</p>
<p>Övningen leder oss drastiskt till en genomgripande upptäckt, som vi hitills kanske bara upplevt som någonting rent abstrakt: att allting går över, att allt förändras. Inget moln stannar för evigt på himlen, ingen smärta, ingen glädje varar beständigt utan förändras och försvinner. Vissa försvinner snabbare, andra långsammare.</p>
<p>Utan att vi varit helt medvetna om det är det detta grundläggande faktum om vår existens som vi så ofta förnekat: vägrat acceptera smärtorna och vägrat låta glädjen försvinna. Men varje vägran, varje "nej", har lämnat kvar ett ärr i oss, och det har hjälpt till att bygga buren som förgiftar oss och stänger oss inne.</p>
<p>Det är alltså dessa förnekande känslor från det färflutna som stiger upp på nytt när musklerna spänns av och andningen frigörs. De kan komma att projiceras på nuvarande relationer med omvärlden och förvränga dem, på samma sätt som färgade glasögon står mellan oss och omvärlden. De kan komma att fixeras vid framtiden i form av mer eller mindre orealistiska planer. Vad de än må vara när vi i ensamheten utför övningen, är de bara våra egna känslor och ingenting annat. Och det är som sådana vi kan möta dem ansikte mot ansikte, och acceptera dem utan att vare sig ge dem ytterligare näring eller förkasta dem.</p>
<p>Det är verkligen inte lätt att låta bli att förstora eller förkasta känslorna. Men övningen gör detta möjligt, även om det till en början bara sker till en del.</p>
<p>Och det som gör detta möjligt är att vi medvetet väljer en fokuseringspunkt för uppmärksamheten, i detta fall kontakten med andningen. När man till exempel vill betrakta himlen i lugn och ro stabiliserar man blicken genom att fästa den på månen. Om man medvetet behåller ögonkontakten med månen kan man låta molnen passera och betrakta dem utan att fixeras vid dem, utan att tillmäta dem någon särskild betydelse. De dyker upp på himlen, passerar över den och döljer sedan månen som för en stund syns bara som ett svagt ljussken genom molnen.</p>
<p>Kontakten med andningen stabiliserar uppmärksamheten. Men den gör den också klarare så att vi liksom ur ögonvrån kan iaktta allt som stiger upp och händer inom oss, som bubblor som stiger upp från botten av en damm för att spricka vid ytan och försvinna i luften.</p>
<p>Andninngens frihet hjälper oss att konkret och medvetet acceptera känslorna, eftersom det inte är möjligt att förneka dem utan att andningen samtidigt blockeras på ett eller annat sätt.</p>
<p>Denna kombination av en stabil och klar mental närvaro och ett ovillkorligt accepterande av allt som lever inom oss, utan att vare sig förstora eller förkasta det, gör det möjligt att undan för undan assimilera det som gjort oss till fångar i det förflutna.</p>
<p>Den energi som blockerades såväl fysiskt som psykiskt av vårt förnekande börjar på nytt cirkulera fritt och ökar våra handlingsmöjligheter.</p>
<p>Övning ger fördighet. Men resultatet visar sig oftare i det dagliga livet än under själva övningen: ett nytt lugn, en större enhet i våra handlingar.</p>
<p>När vi är mentalt närvarande och har ett öppnare hjärta kan vi möta livets svårigheter utan att spänna oss. Och frukten av detta blir en verklig självkännedom, inte någon teoretisk utan en levande och upplevd. Allt mer och mer lär vi känna, i själ och hjärta, denna oerhörda mångfald som lever inom oss.</p>
<h3>Öviningens frukter</h3>
<p>Den sittande övningen centreras kring "att veta" och inte kring "att handla": att vara i balans, vara fri, vara närvarande. Ur denna synvinkel är den en förberedelse för handlingen som vi skall gå in på i de följande kapitlen.</p>
<p>Genom handlingen sår vi också frön för framtiden. Den sittande övninngen hjälper till att göra nuet mera fullödigt. Den skapar ett fält där det förflutnas kvarlevor kan assimileras genom att de projiceringar som fördunklade nuet lyfts fram.</p>
<p>Oberoende av hur lång tid man ägnar övningen inrättar den en tillfällig fristad åt oss från yttervärldens kaos. Livet yttre villkor blir här förenklade och denna förenkling gör det möjligt att inom oss upptäcka vår grund. Den är kanske inte helt ny för oss men har hittills varit dold av aktiviteternas malström och alla yttre relationer.</p>
<p>En ny, djupare och mer intensiv känsla av "jag är" kan stiga fram och sprida klarhet över vårt yttre liv. Detta "jag är" framstår som vårt väsens centrum, det enda kring vilket vårt psykiska liv (tankar, känslor, förnimmelser), våra fysiologiska processer och kroppens fysiska massa kan finna verklig enhet.</p>
<p>Hur lång tid måste man hålla på med övningen för att den skall få en märkbar effekt? Liksom med den liggande övningen kan det vara tillräckligt att till en början ge den fem minuter om dagen. Till och med fem minuter, om möjligt på regelbundna tider, får en djupgående effekt som omedvetet verkar under resten av dagen, som en medicin av vilken man tar några droppar varje morgon.</p>
<p>Men övningen är i grund och botten inte någon medicin utan hellre en del av den dagliga födan. En medicin svarar alltid mot ett bestämt behov och skall bara tas under en begränsad tid. Men som ett kosttillskott kan övningen med fördel brukas under många år och på så sätt bli en integrerad del av livet.</p>
<p>Om övningen utförs utan överdrifter finns det inga kontraindikationer. Men vad menas i detta fall med överdrift? När vi rör oss inom de rätta gränserna för övningen känns det hela tiden hälsosamt och bra, och vi kan utföra övningen med lätthet.</p>
<p>Jämfört med den liggande övningen är den vertikala sittställningen mera fullständig eftersom den leder till en balans mellan den inre aktiviteten och vilan. Om den utförs på rätt sätt kan den alltså utövas under ganska långa pass utan att man blir uttröttad eller faller i sömn. Jag vill emellertid inte råda någon att hålla på mer än en halvtimme Om man vill kan man göra den flera gånger om dagen, när som helst utom omedelbart efter en måltid.</p>
<p>De korta ögonblick av ensamhet som det dagliga livet unnar oss då och då kan också användas till denna övning. Den skänker vila och förnyar krafterna.</p> 
   
    </Layout>
  )
}
export default AboutPage
