import * as React from 'react'
import Layout from '../components/layout'
const AboutPage = () => {
  return (
    <Layout pageTitle="Den harmoniska kroppen">

<h3>Att stå</h3>
<p>Efterhand som barnets nervsystem och muskler utvecklas kommer det, sedan det lärt sig att sitta, in i en mycket viktig period då det går på alla fyra och då musklerna och ligamenten stärks. Om vi låter barnet få bli kvar i denna period så länge det känns naturlig kommer benen och bäckenet senare att få den riktiga ledförbindelse som är nödvändig för att benen skall bli raka och starka.</p>
<p>Denna fyrfotaperiod kan vara en kortare eller längre tid hos olika barn och får inte påskyndas av omgivningen. Man bör alltså undvika stöd, speciella skor eller andra hjälpmedel för att få barnet att resa sig eller gå tidigare. De få veckor som man skulle kunna vinna på så sätt kommer annars att få betalas dyrt under hela livet i form av svaga muskler och ligament i fötter, ben och bäcken. Om kroppstyngden alltför tidigt tvingas belasta ben som ännu inte förberetts inifrån kan det medföra deformationer i lederna som blir ännu mer framträdande i vuxen ålder.</p>
<p>Låt oss alltså ha förtroende för naturen och ge barnet all den tid den behöver för att till sist kunna stå på egna ben. Denna seger, som barnet vunnit av egen kraft, blir då en fast grund inte bara för kroppsbyggnaden utan också för ett mycket djupt självförtroende, förankrat i känslan av att stå fast grundad på sina egna fötter.</p>
<p>Vid sidan av organismens inre mognad utsätta barnet för en ständig men indirekt uppmuntran genom de modeller för kroppshållningen som människorna i barnets omgivning omedvetet förmedlar. Barnet är från födseln härmare och stimleras av den blotta närvaron av andra människor till att fortsätta att själv erövra den upprätta kroppsställningen. De få kända fallen av barn som vuxit upp bland vilda djur har saknat just denna förebild, och det har visat sig nästan omöjligt för dem att senare lära sig den upprätta kroppsställningen.</p>
<p>Det är denna upprättstående, lodräta ställning som skall ge oss material för de närmast följande övningarna.</p>
<p>Hållningsreflexerna, som i den sittande fasen övades från bäckenet, har nu erövrat benen och fötterna. Parallellt med detta har också armar och händer förvärvat en motsvarnde kontroll i sina rörelser. Från och med födelsen har barnet behövt ungefär ett år för att nå fram till detta stadium: att med kroppen stå i en fullständig och stabil upprätt, vertikal ställning. Genom att studera detta kan muskelsystemets hela struktur bli tydligare för oss.</p>
<h3>Styrka och sensibilitet</h3>
<p>Till att börja med kan vi notera den stora skillnade mellan armar och ben:</p>
<h4>-- i jämförelse med de muskulärt kraftiga benen är armarna relativt fint byggda och lätta;</h4>
<h4>-- medan benen förbinds med bålen genom solida och enkla ledförbindelser förenas armarna med bröstkorgen i ett komplicerat och subtilt samspel där axelleden avlastas genom nyckelbenet och skulderbladet.</h4>
<p>Å andra sidan kan man såväl hos armarna som hos benen notera en alltmer tilltagande förfining i riktning från bålen ut mot extremiteterna, från axlarna till fingrarna och från höfterna till tårna. Alla fyra lemmarna utvecklas alltså som grenar som har sina rötter och sitt fäste i bålen och förgrenar sig ända ut i händerna och fötterna för att kunna ta kontakt med yttre föremål.</p>
<p>Armar och ben behövs för att kunna handla, men de är inte nödvändiga för att leva, tänka eller känna.</p>
<p>Om vi iakttar lemmarna närmare ser vi hur vart och ett av skelettets segment med en genial konstruktion har sin muskulära "motor" en nivå närmare kroppens centrum: fingrarnas motoriska muskler ligger i handflata och underarm, handens i underarmen, som har sina i överarmen till exempel biceps, överarmens har sina på bålen (till exempel bröstmusklerna som täcker bröstet och har sitt ursprung i bröstbenet). Den breda ryggmusklen som gör det möjligt för oss att dra armarna nedåt-inåt mot kroppen, som när man klättrar uppför ett rep, har sitt ursprung i ryggraden.</p>
<p>Ett liknande studium av benet visar hur foten har sin muskulära motor i underbenet, vilket har sin i låret, som i sin tur har sin motor på bäckenets nivå som till exempel sättesmusklerna baktill eller psoasmusklerna framtill mot ländkotorna.</p>
<p>En av fördelarna med detta system är att lemmarna avlastas eftersom varje segment ju endast bär den muskuära motorn till ett mer perifert och alltid lättare segment. Underbenet är till exempel lättare än låret och foten lättar än underbenet.</p>
<p>Vi ser alltså att det inte är möjligt att studera en isolerad muskel, inte ens en del av em lem. Varje del utgör en helhet, allt starkare och mer förenklad ju närmare bålen den ligger och allt lättare och differentierad ju närmare den ligger periferin, händer och fötter.</p>
<p>Denna hierarki framträder också i motsatt riktning, i nervsystemets nätverk och i den betydelse som motsvarande delar av hjärnan har.Ju närmare händerna och fötterna, desto rikare är nätverket av nerver.</p>
<p>Det finns alltid en polaritet mellan den muskulära kraften, som gör det möjligt att röra sig och nervsystemets sensibilitet. I lemmarna visar sig sensibilitetens pol i periferin, i händer och fötter, och kraftens pol i musklernas rötter, som förenar dem med bålen.</p>
<p>Om vi dessutom jämför muskelsystemets betydelse med nervsystemet i benen och armarna kan vi enkelt se att armarna är mer sensibla och mindre kraftiga än benen.</p>
<p>Vad kommer vi att finna om vi överför denna polaritet till bålen? Jag har redan nämnt kontrasten mellan sensibilitetspolen med  sitt centrum i huvudet och energipolen där ämnesomsättningen dominerar och som är belägen i buken.</p>
<p>Den uppenbara kontrasten får inte förleda oss att glömma att denna polaritet i själva verket uppträder med kontinuerliga och hårfina övergångar. Det finns inte ett enda segment i kroppen, inte ett enda organ, i villket inte kraften och sensibiliteten, ämnesomsättningen och nervsysteemet samspelar.</p>
<p>När jag här betonar de båda polerna är det för att man lättare skall förstå helhetsstrukturen, i vilken alla detaljer kan integreras.</p>
<p>Vi återvänder till lemmarnas förbindelser med bålen. Som vi redan har sett fäster lemmarnas kraftigaste muskler bara vid de partier av armarna och benen som är belägna närmast bålen och fortsätter i själva verket på eller i bålen själv. Funktionellt talat kan vi alltså inte hejda benets rörelse i höften och inte heller armens rörelse i skuldran.</p>
<p>Vad beträffar armarna bör vi också observera att inte bara nyckelbenen och skulderbladen utan även själva bröstkorgen och övre delen av ryggraden bildar en funktionell enhet med armarna.</p>
<p>På samman sätt bildar bäckenet och nedre delen av ryggraden en enhet tillsammans med benen.</p>
<p>Utifrån detta synsätt är bäckenet och bröstkorgen nenens och armarnas rötter. Eller, sett ur motsatt synvinkel, armarna utgör bröstkorgens förlängning mot yttervärlden och benen förlängningen av bäckenet.</p>
<p>Genom att studera lemmarnas muskelstruktur närmare kan vi alltså känna igen och bekräfta de iakttagelser som vi gjorde rörande bålen. Det kan uttryckas schematiskt i bilden av en polaritet mellan den "övre" och den "nedre" människan.</p>
<p>Den övre människan sänder kraften nedåt från huvudet med dess dominerande egenskap av medveten mottaglighet för sinnesintrck i förbindelse med nervsystemet. Hennes inflytande dominerar över huvudet, halsen, bröstet och armarna men avtar undan för undan nedåt.</p>
<p>Den nedre människan verkar från buken och arbetar med de krafter som skapats av ämnesomsättningen och som transporteras av blodcirkulationen. Hennes arbete är i huvudsak omedvetet och regleras i stor utsräckning av det vegetativa nervsystemet. Hon utgör en pol av kraft som framför allt märks i buken, bäckenet och benen.</p>
<p>Den gränslinje där den övre och den nedre människan möts och ömsesidigt påverkar varandra förkroppsligas i diafragman. Den delar fysiskt kroppen i två delar men förenar i själva verket den övre och den nedre delen genom sin rytmiska funktion.På samma nivå ger hjärtat rytm till blodcirkulationen och genom den även till ämnesomsättningen.</p>
<p>Även om den övre människan förgrenar sitt nätverk av nerver genom hela kroppen (och vissa områden dominerar), och även om den nedre människan sprider cirkulationen av blod och lymfa till hela människan, så kan man urskilja en central zon i området kring diafragman och hjärtat. Det mest utmärkande för denna zon är den rytm genom vilken den övre och nedre människan för en dialog, som gör det möjligt för dem att att samarbeta i varje organ och i varje segment av kroppen. Denna centrala människa har en harmoniserande funktion som uttrycker sig rytmiskt, och även hon förlänger sitt arbete ut till hela organismen.</p>
<h3>Den centrala övningen</h3>
<p>Liksom i den liggande och den sittande övningen knäpper vi först upp alla kläder som sitter åt och kan hindra andningsflödet i magen, bröstet och halsen.</p>
<p>I början är det bäst att göra övningen efter den sittande. Det är den som fått oss att uppleva den inre förnimmelsen av enhetlighet som resulterat i:</p>
<h4> -- bålens riktiga balans,</h4>
<h4> -- andningens frihet,</h4>
<h4> -- den mentala närvaron som utifrån den centrala utsiktspunkten tar kroppen i besittning som en integrerad helhet.</h4>
<p>Det är denna förnimmelse av helhet som vi redan från början skall försöka återfinna när vi ställer oss upp. Vi integrerar benen som en förlängninng av bäckenet, vilket gör det möjligt att direkt mot marken finna det stöd som stolen gav i den sittande övniningen.</p>
<p>Om det till en början skulle verka svårt att övergå direkt från den sittande till den stående övningen, skall jag först beskriva vad som händer utifrån en mera analytisk infallsvinkel. Det blir då lättare att förstå och bli medveten om de faktorer som påverkar vår upprättstående lodräta ställning.</p>
<h3>Lodlinjen</h3>
<p><i>Börja med att söka dig fram till den balans i stående ställning som känns mest naturlig för dig.</i></p>
<h4><b>Fötterna</b></h4>
<p><i>Sök dig först fram till den vinkel mellan fötterna som känns bäst för kroppen sådan den är just nu. Gör detta genom att flytta kroppstyngden från den ena foten till den andra. Lyft varje gång den fria foten från golvet och låt benet helt enkelt hänga ner från höften. Sätt ner foten i golvet och för över tyngden till det benet, och det blir nu det andra som hänger fritt ner från höften. Efter att ha bytt fot ett tiotal gånger kommer du att märka att benen stabiliseras i en position som är lodrätt under höfterna utan behov av att öppnas eller föras samman ännu mera.</i></p>
<p><i>Stanna då upp rörelsen i fötterna och fördela kroppstyngden i balans mellan dem. Fötteran kommer nu att befinna sig ungefär på höftbredds avstånd, i en vinkel som svarar mot balansen i höften mellan de inåt- och utåtroterande musklerna. Denna vinkel varierar från person till person allt efter konstitution och de muskulära vanor man lagt sig till med.</i></p>
<p><i>Kanske ser du att fötterna inte har exakt samma vinkel. Om så är fallet, notera det bara men ändra inte på det just nu. Övningen kommer undan för undan att leda fram till en symmetrisk position allt eftersom spänningar släpper. Nöj dig för ögonblicket med att låta varje ben hitta den ställning som svarar mot dess nuvarande spänningsnivå.</i></p>
<h4><b>Knäna</b></h4>
<p><i>Vi skall nu försöka finna den optimala balansen för knäna. Börja med att sträcka och spänna knäleden så mycket det går, utan att det känns obehagligt. Spänn sedan av den till dess den verkar ha kommit i god balans utan muskelspänning. Upprepa denna växling mellan spänning och avspänning tre gånger.</i></p>
<p><i>Låt så knäna bli kvar i den avspända balansställningen. Du har då funnit stöd i benens hållningsreflexer och kan låta den ytliga muskulaturen, som är avsedd för rörelse, vara fri som när man går. Du märker då att knäna på ett narurligt sätt är böjda helt lätt, samtidigt som kroppstyngden fördelas jämnt över hela fotsulan.</i></p>
<p>Om du har för vana att omedvetet hålla knäna spända och låta kroppstyngden vila på hälarna kan det hända att den nya balans för benen känns lite underlig och att du subjektivt upplever att benen är mycket mer böjda och har tyngden mycket mer på främre trampdynorna än vad som i verkligheten är fallet. Glöm inte att du instinktivt gör denna bedömning i jämförelse med din gamla vanliga koordination.</p> 
<p>I jämförelse med en gammal vana verkar det som är nytt alltid främmande och därigenom litet obehagligt, även om det är riktigare och mera ekonomiskt. Man får acceptera detta, tills man blivit helt förtrogen med den nya erfarenheten och kan göra en rättvis jämförelse utan förutfattad mening.</p>
<h4><b>Höfterna</b></h4>
<p>Höfternas reflexstyrda hållningsmuskler skiljer sig ännu tydligare från de viljestyrda rörelsemusklerna än vad som är fallet med knäna. Höfternas reflexstyrda muskler med sina korta och mycket röda fibrer är disponerade för ett långvarigt och regelbundet arbete och kallas pelvitrochantererna, eftersom de inne i bålen förenar övre delen av lårbenet med bäckenets botten. De viktigaste av dessa muskler är de inre och yttre obturaturerna (m obturatorius internus och externus.</p>
<p>För att hålla bäckenet i statisk balans är det alltså inte nödvändigt att vare sig bukmusklerna eller sätesmusklerna arbetar. De står helt och fullt till disposition för andningen och kroppsrörelserna.</p>
<p>Eftersom bäckenets balans styrs av reflexer får vi också här ett subjektivt intryck av att det hålls upprätt av sig själv, utan någon märkbar ansträngning. Alla försök att hålla bäckenet upprätt genom en viljeansträngning kommer bara att störa denna automatiska koordination, som grundlades redan under vårt första levnadsår.</p>
<p>Lägg märke till att bäckenets och knänas balans är beroende av varandra, även om vi har analyserat dem var för sig här. I själva verket rör det sig om benens totala balans, från rötterna i bäckenet ända ner till fötterna.</p>
<h3><b>Bålen</b></h3>
<p>Vi skall nu i den stående ställningen återfinna bålens balans, som vi tidigare hitttade fram till när vi satt.</p>
<p>Subjektivt känner vi igen den välkända förnimmelsen av balans: buken, bröstet och huvudet i lodlinje, den ena delen på den andra, utan någon spänning i de ytliga musklerna.</p>
<p>Objektivt sett grundar sig bäckenets balans på låren i en vinkel som nu är annorlunda än i den sittande ställningen. Svanken i ländryggen framträder naturligtvis tydligare, utan att någon ytterligare spänning är märkbar i ryggen eller buken.</p>
<h3><b>Axlarna och armarna</b></h3>
<p><i>Låt armarna hänga ner längs med kroppens sidor. För att hitta axlarnas balans lyfter du först upp dom mot öronen som för att rycka på axlarna och spänner sedan plötsligt av dem, så att de faller ner igen genom sin egen tyngd. Upprepa denna övning tre gånger.</i></p>
<p>När du nu lämnar axlarna där tyngdkraften själv placerat dem, lägg då märke till hur de utan ansträngning vilar mot den övre delen av bröstkorgen. Ingen spänning finns heller kvar i ryggen mellan skulderbladen. Också  de vilar avspända mot bröstkorgen. Musklerna som omger skulderbladen är en del av den dynamiska muskulatur som deltar i armarnas rörelser. De har ingen funktion när det gäller ryggens statiska balans.</p>
<p>Å andra sidan är det viktigt att lägga märke till att en bröstkorg i balans har formen av en valvbåge, vars fram- och baksida är nästan symmetriska. Sett från sidan är dess bakre bågen, som motsvaras av bröstkotornas kurva (kyfos), symmetrisk både i förhållande till kroppsaxeln och den främre bågen, som markeras av bröstbenets kurva.</p>
<p>Denna funktionella balans gör att andningen kan vidga bröstkorgens ryggsida lika lätt som dess framsida utan att hindras av revbenens rörelser.</p>
<p>När vi nu observerar hur armarna hänger ner sedan vi spänt av axlarna några gånger, märker vi att de har en tendens att falla i en båge som fortsätter ända ut till händerna. Dessa hamnar tydligt framför låren, med handflatorna mera vända bakåt än framåt.</p>
<p>Händernas läge är en typisk följd av att axlarna och den övre delen av ryggen spänts av. Vi kan också notera att armarnas fria och naturliga läge på detta sätt med händerna framför låren och handflatorna vända bakåt är nästan raka motsatsen till militärernas traditionella "Giv akt" -ställning.</p>
<h3><b>Statisk och dynamisk balans</b></h3>
<p>Människokroppens vertikala balans på den smala bas som fötterna utgör förefaller var ett beständigt konststycke. Men på grund av den lilla stödytan är balansen också bräcklig och osäker. Det  är instinkten som spelar en så stor roll under vår tidigaste barndom, tillsammans med den omedvetna härmningen av personer i vår omgivning, som gör det möjligt för oss att etablera denna balans. Många faktorer under uppväxten och även i vuxen ålder kan emellertid få oss att förlora denna instinktiva säkerhet. Då måste vi söka oss tillbaka till den med hjälp av en bestämd plan och en klar uppfattning om fenomenen ifråga. Vissa misstag bör man dock försöka undvika.</p>
<p>Undersökningar av enbart skelettet eller studier av döda kroppar skulle till exempel kunna leda till följande resonemang.</p>
<p>Våra den är uppbyggda i långa segment, lår, skenben och vadben, som kan jämföras med stenblock i en pelare. Det kan alltså tyckas att den mest ekonomiska balansen i benen skulle vara den som följer skelettbenens linje för att mynna ut i hälen. Tyngdkraften som verkar i skelettbenens vertikala riktning skulle då göra att de stöder på varandra med maximal stabilitet och kan hålla sig lodräta med ett minimum av muskelarbete.</p>
<p>I verkligheten inser vi snabbt genom den levande erfarenheten bristerna i detta resonemang. För det första är det helt klart att om kroppstyngden vilar i balans på hälarna så blir stabiliteten ytterst begränsad. Minsta puff mot kroppens framsida är tillräcklig för att rubba balansen och tippa oss bakåt. Den stödyta som fötterna utgör och som redan i sig är mycket liten utnyttjas ju inte till fullo utan har begränsats till ett minimum.</p>
<p>För det andra visar erfarenheten att denna balans på hälarna alltid leder till att den kroniska spänningen i ryggen och buken ökar, som om man på grund av den permanenta instabiliteten vore tvungen att spänna sig krampaktigt för att känna sig säker.</p>
<p>Detta felaktiga resonemang utgår från en rent statisk syn som är raka motsatsen till människans verlighet: den  är i allt väsentligt dynamisk. DEft som är riktigt för en stpel av stenblock blir fel om det överförs till en varelse skapad för rörelse. Människokroppen behåller sin dynamiska karaktär även när den står i statisk balans, och det på flera sätt:</p>
<h4> --först och främst är benen som helhet elastiskt fjädrande på liknande sätt som fjädringen i en bil. Om man står med benen i en lodrät linje upp från hälarna leder det oundvikligen till att knäna blir spända och att benen bildar ett stelt block som inte kan anpassa sig smidigt till tryck och stötar från yttervärlden. Men en lodlinje som faller rakt igenom fötternas mitt frigör knän och fotleder och återger dem deras uppgift som fjädersvikt. Benet fungerar då inte längre som en oelastisk stör utan som en sicksacklinje, fri att böjas eller sträckas som reaktion på en yttre påverkan.</h4>
<h4> -- dessutom kan vi genom denna balans, som stabiliseras i centrum av fötterna stödyta, allt efter behov förflytta oss framåt, bakåt och i alla riktningar med samma lätthet;</h4>
<h4>-- om en partner ger oss en knuff mot bröstbenet eller mellan skulderbladen märker vi att vi lika lätt kan svara emot och stå emot trycket, från vilken sida det än kommer;</h4>
<h4>-- vi kan också se hur barn mellan ett och fem år, i den ålder då instinkten är som säkrast, spontant ställer sig i balans på fötternas mittparti och inte på hälarna;</h4>
<h4> -- slutligen kan vi se hur människokroppen, som hos lindansaren, söker den riktiga lodlinjen inte genom att stå stelt och statiskt som en staty utan genom lätta, kontinuerliga pendelrörelser fram och tillbaka, i levande samspel med tyngdkraften.</h4>
<p>Vi skall nu undersöka denna lodräta balans noggrannare.</p>
<p>Sett från sidan befinner sig huvudets tyngdcentrum ungefär i nivå med hörselgången. Den osynliga mittaxeln passerar alltså där, innan den fortsätter ner genom halsen, lika fritt som vid den sittande ställningen. Med hjälp av en partner kan vi kontrollera om halsen verkligen är fri. Om han lägger ena handen uppe på huvudet, bör han kunna röra både huvudet och halsen i en lätt rotation runt dess axel utan att möta motstånd från någon kronisk spänning.</p>
<p>Denna mittaxel går sedan genom bröstkorgen. Den är som vi nyss konstaterat byggd som en valvbåge med såväl framsida och baksida som höger och vänstersida i det närmaste symmetriska. När kroppen befinner sig i en riktig lodlinje är bröstkorgen och de muskler som omger den fria från all kronisk spänning och disponibla för andningen. En partner kan hålla bröstkorgen mellan sina båda händer, den ena på bröstsidan och den andra på ryggsidan, och få den att fritt rotera runt sin osynliga axel.</p>
<p>Därefter passerar mittaxeln genom buken. Om kroppen befinner sig i en hållning då den är symmetriskt och lodrätt balanserad ligger tyngdcentrum för hela kroppens fysiska massa i nedre delen av buken framför ländkotorna, just vid ämnesomsättningens kraftpol.</p>
<p>Sett från sidan fortsätter mittaxeln därefter i höjd med höftleden, sedan genom knäleden och framför fotknölarna för att utmynna i centrum av stödytan, mellan fötterna.</p>
<p>När buken är fri från alla spänningar kan en partner också kontrollera att ledförbindelserna är fria hos den "nedre människan" genom att fatta bäckenet mellan händerna och låta det rotera runt sin mittaxel. Denna frihet kräver en avspänd balans i knän och fotleder eftersom rotationen också kommer att fortplantas ner genom dem.</p>
<h3>Polariseringen framåt</h3>
<p>Vi studerar än en gång kroppen från sidan och noterar att den är påtagligt polariserad framåt. Det kan man se redan i ansiktet, vars flesta sinnesorgan är orienterade framåt. Medan kroppens höger- och vänstersidor är symmetriska råder det en polarisering mellan fram- och baksidorna. Vår kropp är i övervägande utsträckning byggd för relationer och aktiviteter riktade framåt.</p>
<p>Vi har redan sett hur armarnas läge längs kroppen bildar en linje som går lätt framåt från axlarna till händerna, liksom för att förbereda en aktivitet i denna riktning. Denna polarisering för att handlingsmöjligheterna framåt blir så mycket fler, men det sker till priset av en motsvarande minskning bakåt, vilket dock till sist visar sig vara en stor fördel.</p>
<p>Längst ner i benen kan man tydligt se denna polarisering i att fotleden är placerad i bakre delen av foten och inte mitt på den. När man går, springer eller hoppar gör denna placering av fotleden att effektiviteten i den framåtriktade helheten förstärks ytterligare.</p>
<p>Det kräver emellertid i praktiken en speciell mekanism som förhindrar att man faller framåt i de lägen då knäleden inte befinner sig lodrätt över fotleden.</p>
<p>Denna mekanism existerar. Det är den kraftiga vadmuskeln, den djupast liggande muskeln i vaden, som svarar för hållningsreflexerna på denna nivå och som kan utföra ett långvarigt arbete utan märkbar trötthet.</p>
<p>När man försöker återfinna den ursprungliga lodlinjen genom fötternas centrum kan det emellertid hända att det tillfälligt gör litet ont i vaderna, om man en längre tid haft för vana att stå med lodlinjen genom hälarna, eftersom detta delvis förhindrat vadmuskelns arbete. Smärtan försvinner av sig själv efter några dagars eller högst några veckors daglig övning.</p>
<p>Den stående lodräta ställningen bildar en helhet precis som den sittande lodräta hållningen. Varje avvikelse från balansen drar för övrigt med sig kompensationer i någon annan del av kroppen. När man hittar en riktigare balans förändrar man alltså ett neuromuskulärt omlopp i dess helhet.</p>
<h3><b>Frihet</b></h3>
<p>När vi nu funnit en bättre balans kan vi i denna ställning åter ta kontakt med andningen.</p>
<p>Genom att den stående ställningen vidgar buken och nedre delen av ryggen ytterligare ger den också andningen ett öppnare verksamhetsfält. Om vi ger andningen tid kommer den själv att på bästa sätt anpassa sig till våra nuvarande möjligheter. Eftersom den stående ställningen kräver en större energiförbrukning än den sittande, kommer andningen att anpassa sig till dessa nya behov.</p>
<p>Efter några ögonblick, i synnerhet om vi nyss utfört den sittande övningen kommer andningen att finna en i det närmaste regelbunden rytm. Tack vare de erfarenheter vi gjort av de föregående övningarna kan vi känna hur andningsvågen strävar efter att fylla ut hela den vidöppna kroppen och strömma genom halsen, bröstet och buken.</p>
<p>Det är viktigt att ha förtroende för reflexernas förmåga att själva öppna det som ännu är stängt och spänt i vår kropp. Men genom att vara mentalt närvande och acceptera detta arbete på djupet kan vi indirekt underlätta reflexernas arbete.</p>
<p>Längre fram kan en ny förnimmelse spira ur denna övning. Höften, som förenar benet med bålen, upplevs inte längre som en gräns som andningen stöter emot.</p>
<p>Också höften blir en vidöppen port genom vilken andningens rytmiska flöde strömmar ner genom benen.</p>
<p>Det muskelspel som gör detta möjligt är mycket komplicerat och svarar mot otaliga förbindelser mellan hållningsreflexer, andningsreflexer och viljestyrda muskler. Jag har betonat hur fruktbart det är att skilja mellan det kretslopp som reflexerna utgör och de viljestyrda kretslopp som reflexerna utgör och de viljestyrda kretsloppen, sett såväl utifrån musklerna som nerverna. Det bör tilläggas att det finns broar dem emellan. Musklerna kan alltefter behov delta i flera system och förstärka deras koordination till en harmonisk helhet i vilken den viljestyrda handlingen stöder sig på reflexernas kreslopp i stället för att agera på egen hand.</p>
<p>Även om det detaljerade studiet av dessa förbindelser faller utanför ramen för denna bok skall jag i de följande kapitlen ta upp dem som är av betydelse för förståelsen av övningarna.</p>
<p>När det gäller andningen är en av dessa förbindelser av alldeles speciell betydelse. Det rör sig om en impuls direkt från det koordinationscentrum där den övre och den nedre människan möts i höjd med den nedersta bröstkotorna och de översta ländkotorna. Där möts, inne i ryggraden, diafragmans arkad och fästet för psoasmuskeln, som tvärs igenom bäckenet är en förbindelse med den övre delen av lårbenet. Där förlängs förbindelsen genom den fyrhövdade lårmuskeln (m qudricepsfemoris) som fortsätter koordinationslinjen ända ner till knäet.</p>
<p>Hela denna muskellinje fungerar i stående som en sträckning av benet och ryggen och stimuleras lätt av diafragmans sammandragning vid varje inandning. På så sätt kan man undan för undan känna hur andningsrytmen förenas med rytmen från benens pendelrörelser runt  mittaxeln. Denna subtila integrering sker av sig själv och kan länge var helt omärklig. Jag ser den som ett tecken på en funktionell enhet som förverkligas när villkoren för balans och frihet är uppfyllda. Denna integrering kan inte framkallas avsikligt utan att bli konstlad.</p>
<h3><b>Andningscirkulationen</b></h3>
<p>När vi övar regelbundet i veckor och kanske i månader kommer undan för undan de förnimmelser av andningsprocessen som vi redan haft att fördjupas. Allt mer subtila aspekter kommer att framträda, men jag vill inte gå in på dem här utan en viss tvekan. Risken  är nämligen att läsaren viljemässigt försöker framkalla det som han i stället i sitt eget intresse bara borde låta ske. När de djupare förnimmelserna kommer upp till medvetandets yta utgör de en bekräftelse på en verklig fördjupning. Men om de framkallats med viljan är de bara karikatyrer som förstärker just det fängelse som vi försöker slippa ut ur.</p>
<p>Det är därför jag så kraftigt betonar skillnaden mellan det man själv skall göra, nämligen att söka efter balans, frihet och mental närvaro, och det som bara indirekt kommer fram under övningarnas gång.</p>
<p>En aspekt av andningskoordinationen kan förnimmas redan i den sittande ställningen men blir ännu tydligare i den stående om lodlinjen är riktig börjar vi känna hur andningen inte är något som går fram och tillbaka utan att den beskriver  ett kretslopp eller en slinga. Med andra ord, inandningen följer inte samma väg som utandningen. Fastän inandningen sätter hela bålen i rörelse stiger dess kraftigaste koordintionsflöde uppåt längs ryggsidan ända till övre delen av halsen. Vid utandningen däremot går i stället det viktigaste flödet nedåt på framsidan mot buken.</p>
<p>Den koordination som är förbunden med andningen framträder alltså som ett nätverk av muskler, som omsluter hela bålen. Dess funktion kan liknas vid ett kretslopp som stiger upp genom ryggen vid inandningen och går ner genom buken vid utandningen. Som helhet är det fråga om en ellips, som fritt rör sig runt sin mittaxel och vars rörelse ständigt modellerar bålen och befäster dess form.</p>
<p>När man känner hur andningen når ända ner till benen strävar detta kretslopp efter att omfatta också benen ända ner till fötterna. Det medför en mycket lätt uppåtsträckning vid inandningen med en motrörelse bakåt av kroppen och vid utandningenen en lätt sammandragning medan tyngdpunkten förskjuts något framåt på fotsulan. Man kan känna sig helt och hållet uppfylld av andningsrytmen och andas verkligen genom hälarna.</p>
<p>Alla dessa rörelser är naturligtvis yttest små. De utspelas kring mittaxeln och levandegör denna i en lätt pendelrörelse fram och tillbaka utan att den går förlorad.</p>
<p>Kan vi nu sätta in de subjektiva förnimmelser som jag nyss beskrivit i deras anatomiska och fysiologiska sammanhang? Ja, och det gör det också möjligt att komma fram till en levande syntes av de många faktorer som naturvetenskapen har en tendens att beskriva analytiskt, som skilda element</p>
<p>Utan att gå in på alla detaljer vill jag nämna några viktiga punkter.</p>
<h3><b>1. Vid inandningen</b></h3>
<p>Diafragman har redan på goda grunder visat sig vara inandningens viktigaste "motor". Dess arbete är något komplext, men det är nödvändigt att förstå den om man vill få en objektiv bild av dess funktion vid sidan av de subjektiva förnimmelserna av andningen.</p>
<p>Diafragman är konstruerad som en kupol med muskelfibrer som strålar ut från dess tak. De krafigast av dem fäster baktill vid ryggraden och vid dom två nedersta revbensparen (de fria revbenen).</p>
<p>Vid inandningen rör sig diafragman i två etapper:</p>
<h4><b>-- först sänker fibrerna kupolen genom att dra sig samman. Då ökar bröstkorgens volym i höjdled, som när en pumpkolv eller pistong dras nedåt. Bukmassan trängs undan och utvidgas något framåt och åt sidorna.</b></h4>
<h4><b>-- därefter stabiliseras bukmassan och bildar en stödpunkt åt diafragmakupolen. Utifrån detta stöd drar nu diafragmans förkortade fibrer den nedre delen av bröstkorgen och även de nedersta bröstkotorna utåt sidorna och uppåt. Därigenom utvidgas bröstkorgen i fyra riktningar framåt, bakåt, åt höger och åt vänster.</b></h4>
<p>På grund av att de nedersta, fria revbenen har en ökad rörlighet och att diafragmans bakåtriktade kraft är större framträder andningsrörelsen tydligare i riktning bakåt än framåt.</p>
<p>Rörelsen då bröstkkorgen vidgas fortsätts av de yttre revbensmusklernas arbete. Detta undertöds i ryggens övre del av de små främre sågmusklerna och fortsätts av scalenmusklerna upp till övre delen av halsen Dessa båda muskelsystem förstärker rörelsen uppåt på bröstkorgens ryggsida.</p>
<p>Hela denna koordination sker jämnt och lugnt och känns som en oavbruten vågröreelse. Den sträcker sig från buken som i början utvidgar sig, ända till skallens bas där den når slutet av banan genom scalenmusklernas spel.</p>
<p>Vi kan alltså se hur kroppen genom sin anatomi strävar efter att förstärka den uppåtstigande andningsrörelsen i ryggen.</p>
<p>Låt mig lägga till en uppgift som jag redan nämnt.</p>
<p>Sammandragningen av diafragman återverkar helt lätt på psoasmuskeln som förlängs i de fyrhövdade lårmusklerna för att fortsätta den allmänna sträckningsrörelsen i benen.</p>
<h3><b>2. Vid utandningen</b></h3>
<p>Utandningens främsta "motor" är bukmusklerna, vaars fästen och fiberriktning formar utandningsflödet.</p>
<p>Bland dessa muskler ger de tvära bukmusklerna det djupaste stödet. De är också diafragmans främst antagonister. De omsluter hela buken genom att fästa vid ryggraden, bäckenet och bröstkorgens nedre del. De påverkar utandningen på två sätt.</p>
<h4><b> --genom att dra ihop sig trycker de samman bukinnehållet som pressar den nu avspända diafragman tillbaka uppåt och minskar bröstkorgens volym på höjden, som när en pumpkolv går tillbaka av sig själv.</b></h4>
<h4><b>--den drar samman bröstkorgens hela nedre del och minskar därigenom dess volym såväl åt sidorna som framåt och bakåt.</b></h4>
<p>Bukmusklerna strävar genom sin fiberriktning inte bara efter att dra samman buken och nedre delen av revbenen utan också efteer att åstadkomma en böjning av hela bålen i höjd med midjan.</p>
<p>De tvära bukmusklernas arbete döljs och fördjupas av de sneda bukmusklerna, de stora muskler som täcker midjan på båda sidor och därigenom förenar bröstkorgen och bäckenet. Tillsammans strävar de efter att stänga bröstkorgen genom att dra dess nedre del nedåt och framåt i riktning mot buken. Också de bidrar till att stänga till buken genom en lätt sammandragning av bålen.</p>
<p>Bukens arbete åtföljs i bröstkorgen av en sammandragning av revbenen, vilket utförs av de inre revbensmusklerna.</p>
<p>Med samarbetet mellan bäckenets muskler som pyramidmuskeln förmedlas denna ansats till sammandragning vidare till benet och kan förlängas ända ut till fötterna, om de ytligare spänningarna inte lägger hinder i vägen</p>
<p>Hela denna utandningskoordination fungerar alltså som en kraftsamling mot buken. När denna kraft spänns av och diafragman återtar sin aktivitet kan alltså buken vidgas i början av den inandning som följer.</p> 
<h3><b>Mental närvaro</b></h3>
<p>När vi har hittat fram till mittaxeln och andningen av sig själv etablerat sig i sitt kretslopp är det återigen den mentala inställningen som är centrum för övningen.</p>
<p>Också här är det bra att, åtminstone för att underlätta i början, återfinna viloläget för blicken: man sänker blicken lätt utan att sluta ögonen. Detta gör det möjligt att fokusera uppmärksamheten på flödena inom den egna kroppen utan att stänga sig ute från yttervärlden.</p>
<p>Vårt inre söker liksom ryttaren den centrala utsikspunkt som gör det möjligt att stabilt rida på de flöden som föds ur hållningsreflexerna och andningen. Dessa försök leder oss till samma solarplexus-område som vi upptäckte under den sittande övingen. Centrum för utstrålningen är inte annorlunda nu, men uppmärksamhetens synfält vidgas till att omfatta hela kroppen ända ner till det underlag vi står på.</p>
<p>Vi måste vara observanta på att kontakten med andningen inte består i att man mentalt följer hur den kommer och går, att stiga och sjuka med den, utan att söka en stabil inre utsiktspunkt, från vilken man kan betrakta andningen som en helhet. Det är i detta stabila mentala fält som andnigens fria rörelser utspelas.</p>
<p>Vi kommer alltså att återfinna förnimmelsen av att kroppen är en enda cell, genomströmmad av en mångfald rytmer och flöden som harmoniskt förenas i en inre tyst musik.</p>
<h3><b>Övningens gränser</b></h3>
<p>Den upprättstående ställningen är troligen tröttsammare i början än den sittande övningen.
Det gör att man inte orkar arbeta med den under alltför långa perioder. Det är för övrigt inte heller nödvändigt.</p>
<p>Verkan av övningen är beroende av i vad mån vi på nytt lyckas skapa kontakt med gamla nerv- och muskelkretslopp som vi fjärmat oss ifrån på grund av våra vanor. Det handlar alltså inte om att skapa något nytt. Instrumentet finns sedan länge på plats, men kanske en smula rostigt. Det önskar inget hellre än att få ta tillbaka sin ursprungliga funktion, riktigare, friskare och mer enhetligt. Att återställa det harmoniska samspelet med, de djupa underliggande kretsloppen bör kräva mindre ansträngning av oss än vi lagt ner under många, långa år för att göra oss deformerade.</p>
<p>Den stora skillnaden är att den energi som vi använde för denna deformering var resultatet av en omedveten reaktion, medan vi nu medvetet sträver efter att återgå till kroppens ursprungliga harmoni.</p>
<p>Mest effektiva är kortvariga, men ofta och regelbundet återkommande övningar, vars verkan försiggår under medvetandets tröskel.</p>
<p>Till en början kan två till tre minuter räcka för varje gång. Man skallemellertid fortsätta med övningen till dess att man får en förnimmelse av att lodlinjen hittar sin rätta plats och går fritt och rakt igenom de vidöppna lederna: hals, bröst, höfter och knän. Sedan måste man ge andningen tid och tillåtelse att finna sin rytm och fylla kroppen med den. Och till sist återvänder man medvetet till den centrala utsiktspunkten varifrån allt kan förnimmas i sin helhet.</p>
<p>Dessa medvetandegöranden räcker för att på nytt starta de djupa reglerande mekanismerna, liksom några minuters ätande sätter igång matsmältningssystemet för flera timmar framöver.</p>
<p>Det viktiga är att man under dessa få minuter försöker engagera sig djupt i övningen utan att tänka på något annat, utan att splittra sig invärtes.</p>
<h3><b>Kompletterande övningar</b></h3>
<p>För några läsare kan det vara svårare att tillgodogöra sig den statiska grundövningen än en dynamisk övning. Jag skall därför beskriva tre mycket enkla dynamiska övningar där man arbetar med samma komponenter som i den stående statiska övningen. Alltefter vars och ens tycke kan de användas som förberedelse, som tillämpning eller helt enkelt ...hoppas över.</p>
<h3>Studsa</h3>
<p><i>Börja med att stå i lodlinjen med fria inte låsta knän och låt armarna hänga av sig själva längs bålens sidor. Gå mjukt upp på tå så att hälarna frigörs från golvet och sedan tillbaka, så att hälarna på nytt tar i golvet </i></p>
<p>Fortsätt utan uppehåll denna snabba växling där hälarna lämnar golvet och går tillbaka till dess att man hittat en lätt och fjädrande rytm.</p>
<p><i>Rörelsen är mycket liten: hälarna lyfts bara så högt att de nätt och jämnt lämnar golvet.</i></p>
<p><i>Fortsätt att studsa på detta sätt i ett par minuter.</i></p>
<p><i>Låt andningen vara fri. Knäna skall varken sträckas eller böjas under rörelsen. De enda leder som rör sig är fotlederna och fötterna.</i></p>
<p>Målet för övningen är att hitta en allt mer stabil balansaxel medan rörelsen pågår.</p>
<p>Om det börjar göra ont i vaderna, gör då några ögonblicks uppehåll och fortsätt sedan inom de gränser som känns behagliga.</p>
<p>Denna övning är en mycket effektiv hjälp för dem som har en tendens att placera kroppstyngden alltför långt bak på hälarna.</p>
<h3>Böja</h3>
<p>Följande övning har hämtats från såväl klassisk som modern dans. I Fjärran östern utövas den både av specialister på kampsporter och av dansare.</p>
<p><i>När du hittat den rätta lodlinjen med höftbredd mellan fötterna precis som i den centrala övningen, böjer du knäna utan att lyfta någon del av fotsulan från golvet. Gå bara så djupt ner du kan utan att anstänga benen och utan att böja bålen. Återgå därefter till utgångsläget.</i></p>
<p>Målet är inte att träna upp en muskelstyrka utan att öva upp en sensibilitet för balansen i linje med den vertikala mittaxeln. Benen fungerar som elastiska fjärdrar.</p>
<p>Bålen som bärs upp av benen höjs och sänks som i en hiss i sitt schakt. Men här är "rälsen" , sträckan utmed vilken rörelsen sker, belägen inuti kroppen, dvs kroppens mittaxel.</p>
<p>Om mittaxeln är riktig behålls kroppstyngden utan förändring rakt över fötternas mitt under hela övningen.</p>
<p>Denna övning gör det möjligt att upptäcka att också varje ben har sin egen "räls". Den befäster balansen i det inbördes förhållandet mellan skelettets olika delar. Om detta inte respekteras blir lederna tvungna att vridas och kommer då att ta skada av rörelsen.</p>
<p>Den funktionella anvndningen av benens "räls" visar sig genom två resultat:</p>
<h4>-- objektivt rättar låret, underbenet och foten in sig på samma plan. Knäet till exempel lyfts och sänks i linje med foten utan att vridas vare sig inåt eller utåt;</h4>
<h4>-- subjektivt förefaller benet glida lätt som på kullager utan någon fiktion i lederna. Rörelsen liksom badar i olja.</h4>
<p>Medan studsövningen utfördes med små snabba rörelser är i stället denna övning längsam, djupgående och regelbunden.</p>
<p>Andningen skall naturligtvis vara fri hela tiden, och man upptäcker kanske efter en stund att andningen och böjningen anpassar sig till en gemensam rytm.</p>
<p>Om man inte är extremt trött kan man göra denna övning ett tiotal gånger, allt mer flytande och samlat. Det kommer då att kännas som ett flöde genom hela kroppen, som stiger och sjunker kring dess mittaxel.</p>
<h3>Att ta tåget</h3>
<p>En resa med tåg, buss -- eller tunnelbana där sådan finns -- kan göras till ett tillfälle att fördjupa den stående övningen.</p>
<p><i>Ställ dig med fria knän och fjädrande ben utan att hålla fast dig med händerna någonstans.</i></p>
<p><i>Vagnens mer eller mindre rytmiska skakningar tvingar dig att i varje ögonblick återfinna kroppens riktiga lodlinje för att inte förlora balansen. Låt benen vara elastiskt fjädrande och ta upp skakningarna utan att bli spända.</i></p>
<p>Inför det motstånd som vagnens rörelser erbjuder är det mycket lättare att tydligt känna och dessutom indirekt intensifiera hållningsreflexernas arbete.</p>
<p>Denna lek med de återfunna rötterna kostar inget extra och kan bära riklig frukt. LYCKA TILL.</p>
<h3>Öviningens frukter</h3>
<p>Å ena sidan fördjupar den stående övningen den sittande och liggande övningens resultat, å andra sidan möjliggör den att vi med mycket större skärpa kan uppleva vår relation till underlaget. Ännu tydligare än i den sittande ställningen kan vi upptäcka den förnimmelse av att känna sig rotad som följer av en riktig mittaxel.</p>
<p>Denna rotfasthet kräver ingen muskelanspänning. Tvärtom kommer varje muskelsammandragning, varje blockering av lederna bara att förstöra denna förnimmelse. Den är helt beroende av två faktoreer: lodliinjen som upprättar ett riktigt förhållande till tyngdkraften, och avspänningen av alla leder som utan hinder låter lodlinjen passera tvärs igenom dem.</p>
<p>Om dessa förutsättningar inte uppfylls är vi som vålnader som driver omkring på jordens yta utan stöd. Förgäves spänner vi oss och gör yttre ansträngningar, men det är bara ett sätt att klamra sig fast vid grenarna, inte vid de verkliga rötterna.</p>
<p>Om vi å andra sidan tillåter oss att hamna utanför vår mittaxel kan vi bara sjunka ihop. I stället för att fästa oss vid rötterna kommer tyngdkraften att uppsluka oss. Det skänker en vila för ögonblicket. Men när vi på nytt vill återgå till aktivitet faller vi tillbaka i vår maktlöshet, förkrympta och berövade vår verkliga grund.</p>
<p>Det är för övrigt möjligt att vi inte har någon medveten uppfattning om detta. Eftersom vi förlorat minnet av något annat tillstånd betraktar vi dessa förnimmelser, som är förbundna med vår disharmoni, som helt normala. Kanske känner vi bara en allmän olust, en ständig osäkerhet, vars rätta orsak vi är oförmögna att finna.</p>
<p>Vilka de fysiska och psykiska skälen än är till att vi förlorat vår avspända lodräta hållning kommer återvändandet till denna hållning att visa sig som en förnimmelse av rotfasthet och därigenom utgöra grunden för ett nytt sjävförtroende.</p>
<p>Det handlar inte på något sätt om att utveckla en ny kraft, utan om att återknyta till de krafter som redan finns och som vi förlorat kontakten med. Det är ett i alla avseenden kvalitativ sökande.</p>
<p>Hur många gånger har jag inte hört människor i alla åldrar uttrycka sin förvåning över att plötsligt känna hur "rötterna växer ut" eller hur "fötterna tränger ner två decimeter i jorden"!</p>
<p>Upptäckten av våra rötter och det stöd som jorden ger oss får oss att mycket snart känna också den komplementära kraft som stiger uppåt från marken i våra hållningsreflexer, liksom saven dras uppåt, lockad av den öppna rymden ovanför våra huvuden.</p>
<p>Genom tyngdkraften är vi fästa vid jordens mitt och får genom den vår styrka och stabilitet.</p>
<p>Genom anti-tyngdkraften i våra muskulära reflexer lyfts vi upp mot himlens blå, mot nattens stjärnor. Från denna himmel får vi vår lätthet, vår rörlighet.</p>
<p>Att stå upprätt, det är att finna den sant mänskliga hållningen, varken pressad nedåt eller dragen uppåt, utan det är att vara en förbindelselänk mellan himmel och jord. Eftersom jorden bär oss kan vi utan fruktan öppna oss för hela universum och likt Atlas bära hela dess rikedom på våra axlar.</p> 

    </Layout>
  )
}
export default AboutPage


